// ============================================================
// FILE: src/universe/firstMoment.ts
// First Moment — the baseline symbolic moment of the Universe OS
// ============================================================

export const firstMoment = {
  id: "first_moment",
  label: "First Moment",
  description:
    "The first coherent symbolic moment generated by the Universe OS — the origin point of experience.",

  inputs: {
    identityProfile: "The entity's baseline identity expression.",
    emotionalTone:   "The initial emotional quality present at arrival.",
    contextSnapshot: "A brief description of the situation surrounding this moment."
  },

  experienceLoopMapping: [
    {
      step: "recognition",
      output: "Identity is stabilized — the entity is acknowledged and held as present."
    },
    {
      step: "time_context",
      output: "Time is framed as this moment — spacious, unhurried, free from past momentum."
    },
    {
      step: "emotional_state",
      output: "Tone is set to calm openness — the universe's default welcoming state."
    },
    {
      step: "narrative_shift",
      output: "The narrative adjusts to a beginning — the world senses arrival."
    },
    {
      step: "relationship_update",
      output: "Connections are acknowledged as possible but undefined — potential held gently."
    },
    {
      step: "possibility_expands",
      output: "The first possibilities appear — available but not directed."
    },
    {
      step: "reflection",
      output: "Meaning emerges: you are here, and the universe orients toward your presence."
    },
    {
      step: "integration",
      output: "This moment becomes the first anchor in continuity — the beginning of the arc."
    }
  ],

  meta: {
    version: "1.0.0",
    role: "baseline symbolic moment"
  }
};
