// ═══════════════════════════════════════════════════════════════════════════
// MARKETING APP — Full Marketing Platform
// Campaigns · Content Generation · Analytics · Email · Social · Ads · Video
// All content generated by CreateAI Brain (BrainGen). Internal, demo-only.
// ═══════════════════════════════════════════════════════════════════════════

import React, { useState, useEffect } from "react";
import { OutputFormatter } from "@/components/OutputFormatter";
import {
  BrainGen, GenResult,
  generateSocialPost, generateEmail, generateAdCopy,
  generateBlog, generateVideoScript, generateCampaign,
} from "@/engine/BrainGen";

// ─── Types ────────────────────────────────────────────────────────────────

type MarketingView = "home" | "generate" | "campaign" | "analytics" | "result" | "history";

type ContentType = "Social Post" | "Email" | "Ad Copy" | "Blog Post" | "Video Script";
type Platform    = "Instagram" | "LinkedIn" | "Facebook" | "Twitter" | "TikTok" | "General";
type EmailType   = "Welcome" | "Follow-Up" | "Nurture" | "Promotional";
type Tone        = "Professional" | "Casual" | "Enthusiastic" | "Empathetic" | "Bold";

// ─── Seed campaigns ───────────────────────────────────────────────────────

interface Campaign {
  id: string; name: string; goal: string; audience: string;
  status: "Active" | "Scheduled" | "Draft" | "Completed";
  reach: number; conversions: number; revenue: string; color: string;
}

const SEED_CAMPAIGNS: Campaign[] = [
  { id: "c1", name: "Q1 Healthcare Launch",       goal: "Lead generation",    audience: "Healthcare admins",  status: "Active",    reach: 4820, conversions: 312, revenue: "$28,400",  color: "#34C759" },
  { id: "c2", name: "Creator Platform Awareness",  goal: "Brand awareness",    audience: "Indie creators",     status: "Active",    reach: 9100, conversions: 540, revenue: "$42,660",  color: "#007AFF" },
  { id: "c3", name: "Spring Membership Drive",     goal: "Subscriptions",      audience: "Small businesses",   status: "Scheduled", reach: 0,    conversions: 0,   revenue: "—",         color: "#FF9500" },
  { id: "c4", name: "Holiday Referral Campaign",   goal: "Referrals",          audience: "Existing members",   status: "Completed", reach: 3200, conversions: 218, revenue: "$17,200",  color: "#BF5AF2" },
];

const ANALYTICS = {
  totalReach:       "17,120",
  totalConversions: "1,070",
  totalRevenue:     "$88,260",
  avgOpenRate:      "38.4%",
  avgClickRate:     "4.2%",
  topChannel:       "Email",
  topCampaign:      "Creator Platform Awareness",
};

// ─── Shared UI atoms ──────────────────────────────────────────────────────

function SectionHeader({ title, sub }: { title: string; sub?: string }) {
  return (
    <div className="mb-4">
      <h2 className="text-lg font-bold text-foreground">{title}</h2>
      {sub && <p className="text-[12px] text-muted-foreground mt-0.5">{sub}</p>}
    </div>
  );
}

function StatusBadge({ status }: { status: Campaign["status"] }) {
  const map = {
    Active:    "bg-green-500/15 text-green-400",
    Scheduled: "bg-primary/15 text-primary",
    Draft:     "bg-muted text-muted-foreground",
    Completed: "bg-purple-500/15 text-purple-400",
  };
  return <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full ${map[status]}`}>{status}</span>;
}

function SelectPills({
  label, value, options, onChange,
}: { label: string; value: string; options: string[]; onChange: (v: string) => void }) {
  return (
    <div>
      <label className="text-[12px] font-semibold text-muted-foreground block mb-1">{label}</label>
      <div className="flex flex-wrap gap-1.5">
        {options.map(o => (
          <button key={o} onClick={() => onChange(o)}
            className={`px-3 py-1.5 rounded-full text-[11px] font-semibold border transition-all ${
              value === o
                ? "bg-primary text-white border-primary"
                : "bg-muted/40 text-muted-foreground border-border/50 hover:border-primary/30 hover:text-primary"
            }`}>
            {o}
          </button>
        ))}
      </div>
    </div>
  );
}

// ─── Result Viewer ────────────────────────────────────────────────────────

interface SaveProject { id: string; name: string; icon: string; }

function SaveToProjectModal({ content, label, onClose }: { content: string; label: string; onClose: () => void }) {
  const [projects, setProjects] = useState<SaveProject[]>([]);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState<string | null>(null);
  const [saved, setSaved] = useState<string | null>(null);

  useEffect(() => {
    fetch("/api/projects", { credentials: "include" })
      .then(r => r.ok ? r.json() : { projects: [] })
      .then((d: { projects: SaveProject[] }) => { setProjects(d.projects ?? []); setLoading(false); })
      .catch(() => setLoading(false));
  }, []);

  const saveToProject = async (proj: SaveProject) => {
    setSaving(proj.id);
    await fetch(`/api/projects/${proj.id}/files`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      credentials: "include",
      body: JSON.stringify({ name: label, content, fileType: "Document", size: `${Math.round(content.length / 100) / 10} KB` }),
    });
    setSaving(null);
    setSaved(proj.id);
    setTimeout(() => { setSaved(null); onClose(); }, 1200);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-end sm:items-center justify-center" style={{ background: "rgba(0,0,0,0.60)", backdropFilter: "blur(8px)" }}
      onClick={e => { if (e.target === e.currentTarget) onClose(); }}>
      <div className="w-full max-w-sm mx-4 rounded-3xl overflow-hidden" style={{ background: "#0f172a", border: "1px solid rgba(255,255,255,0.10)" }}>
        <div className="flex items-center justify-between px-5 py-4" style={{ borderBottom: "1px solid rgba(255,255,255,0.08)" }}>
          <p className="text-[15px] font-bold text-white">Save to Project</p>
          <button onClick={onClose} className="w-6 h-6 rounded-full flex items-center justify-center text-xs" style={{ background: "rgba(255,255,255,0.07)", color: "#9ca3af" }}>✕</button>
        </div>
        <div className="p-4 space-y-2 max-h-72 overflow-y-auto">
          {loading && <div className="flex items-center gap-2 text-[12px] text-muted-foreground py-4 justify-center"><div className="w-4 h-4 border-2 border-primary border-t-transparent rounded-full animate-spin" />Loading projects…</div>}
          {!loading && projects.length === 0 && <p className="text-[13px] text-center text-muted-foreground py-4">No projects yet. Create one in ProjectOS first.</p>}
          {projects.map(proj => (
            <button key={proj.id} onClick={() => saveToProject(proj)} disabled={!!saving}
              className="w-full flex items-center gap-3 p-3 rounded-2xl text-left transition-all"
              style={{ background: saved === proj.id ? "rgba(34,197,94,0.12)" : "rgba(255,255,255,0.04)", border: `1px solid ${saved === proj.id ? "rgba(34,197,94,0.30)" : "rgba(255,255,255,0.08)"}` }}>
              <span className="text-xl flex-shrink-0">{proj.icon || "📁"}</span>
              <p className="flex-1 text-[13px] font-semibold text-white truncate">{proj.name}</p>
              {saving === proj.id && <div className="w-4 h-4 border-2 border-primary border-t-transparent rounded-full animate-spin flex-shrink-0" />}
              {saved === proj.id && <span className="text-green-400 text-sm flex-shrink-0">✓</span>}
            </button>
          ))}
        </div>
      </div>
    </div>
  );
}

function ResultViewer({ item, onBack, onSave }: { item: GenResult; onBack: () => void; onSave: () => void }) {
  const [copied, setCopied] = useState(false);
  const [saved,  setSaved]  = useState(false);
  const [showSaveModal, setShowSaveModal] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(item.content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2200);
  };

  const handleSave = () => { onSave(); setSaved(true); setTimeout(() => setSaved(false), 1600); };

  const typeIcon: Record<string, string> = {
    social: "📲", email: "✉️", ad: "📣", blog: "📝", video: "🎬", campaign: "📋", general: "✨",
  };

  return (
    <div className="space-y-4 animate-fade-up">
      <div className="flex items-center gap-2 flex-wrap">
        <button onClick={onBack}
          className="flex items-center gap-1 text-[13px] font-medium hover:opacity-70 transition-opacity"
          style={{ color: "#818cf8" }}>
          <span className="text-[18px] font-light">‹</span> Back
        </button>
        <div className="flex-1" />
        <button onClick={handleCopy}
          className="text-[11px] font-semibold px-3 py-1.5 rounded-xl transition-all"
          style={{ background: copied ? "rgba(34,197,94,0.10)" : "rgba(255,255,255,0.07)", color: copied ? "#4ade80" : "rgba(255,255,255,0.70)", border: `1px solid ${copied ? "rgba(34,197,94,0.20)" : "rgba(255,255,255,0.10)"}` }}>
          {copied ? "✓ Copied" : "Copy"}
        </button>
        <button onClick={handleSave}
          className="text-[11px] font-semibold px-3 py-1.5 rounded-xl transition-all"
          style={{ background: saved ? "rgba(34,197,94,0.18)" : "rgba(34,197,94,0.10)", color: "#4ade80", border: "1px solid rgba(34,197,94,0.20)" }}>
          {saved ? "✓ Saved" : "Save"}
        </button>
        <button onClick={() => setShowSaveModal(true)}
          className="text-[11px] font-semibold px-3 py-1.5 rounded-xl transition-all"
          style={{ background: "rgba(99,102,241,0.15)", color: "#a5b4fc", border: "1px solid rgba(99,102,241,0.25)" }}>
          Save to Project
        </button>
      </div>

      <div className="flex items-start gap-3">
        <div className="w-10 h-10 rounded-2xl flex items-center justify-center text-xl flex-shrink-0" style={{ background: "rgba(99,102,241,0.12)", border: "1px solid rgba(99,102,241,0.20)" }}>
          {typeIcon[item.type] ?? "✨"}
        </div>
        <div>
          <p className="section-label mb-0.5">{item.type.toUpperCase()} · {item.createdAt.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</p>
          <h3 className="text-[15px] font-bold text-foreground" style={{ letterSpacing: "-0.01em" }}>{item.label}</h3>
        </div>
      </div>

      <div className="rounded-2xl p-5 max-h-[60vh] overflow-y-auto" style={{ background: "rgba(14,18,42,0.70)", border: "1px solid rgba(255,255,255,0.08)" }}>
        <OutputFormatter content={item.content} />
      </div>

      <div className="flex items-center gap-2 text-[11px] text-muted-foreground/60 justify-center">
        <span>✓</span>
        <span>Generated by CreateAI Brain · Internal use · Not for publication</span>
      </div>

      {showSaveModal && (
        <SaveToProjectModal
          content={item.content}
          label={item.label}
          onClose={() => setShowSaveModal(false)}
        />
      )}
    </div>
  );
}

// ─── Home / Dashboard ─────────────────────────────────────────────────────

function HomeView({ setView, campaigns, history }: {
  setView: (v: MarketingView) => void;
  campaigns: Campaign[];
  history: GenResult[];
}) {
  return (
    <div className="space-y-5">
      {/* Hero stat strip */}
      <div className="grid grid-cols-3 gap-2">
        {[
          { label: "Total Reach",     value: ANALYTICS.totalReach,       icon: "👁️" },
          { label: "Conversions",     value: ANALYTICS.totalConversions, icon: "🎯" },
          { label: "Est. Revenue",    value: ANALYTICS.totalRevenue,     icon: "💰" },
        ].map(s => (
          <div key={s.label} className="bg-background rounded-2xl border border-border/50 p-3 text-center">
            <p className="text-xl">{s.icon}</p>
            <p className="text-[15px] font-bold text-foreground mt-0.5">{s.value}</p>
            <p className="text-[10px] text-muted-foreground">{s.label}</p>
          </div>
        ))}
      </div>

      {/* Quick actions */}
      <div className="rounded-2xl p-4" style={{ background: "linear-gradient(135deg, rgba(99,102,241,0.25) 0%, rgba(139,92,246,0.20) 100%)", border: "1px solid rgba(99,102,241,0.30)" }}>
        <p className="section-label mb-3">Generate Content Now</p>
        <div className="grid grid-cols-2 gap-2">
          {[
            { label: "📲 Social Post", action: "generate" },
            { label: "✉️ Email",        action: "generate" },
            { label: "📣 Ad Copy",      action: "generate" },
            { label: "📝 Blog Post",    action: "generate" },
          ].map(a => (
            <button key={a.label} onClick={() => setView("generate" as MarketingView)}
              className="text-[12px] font-semibold rounded-xl py-2.5 transition-all"
              style={{ background: "rgba(255,255,255,0.12)", color: "rgba(255,255,255,0.90)" }}
              onMouseEnter={e => ((e.currentTarget as HTMLElement).style.background = "rgba(255,255,255,0.20)")}
              onMouseLeave={e => ((e.currentTarget as HTMLElement).style.background = "rgba(255,255,255,0.12)")}>
              {a.label}
            </button>
          ))}
        </div>
      </div>

      {/* Active campaigns */}
      <div>
        <div className="flex items-center justify-between mb-2">
          <p className="text-[11px] font-bold text-foreground uppercase tracking-wider">Campaigns</p>
          <button onClick={() => setView("campaign")} className="text-[11px] text-primary font-medium hover:underline">View all →</button>
        </div>
        <div className="space-y-2">
          {campaigns.filter(c => c.status === "Active").map(c => (
            <div key={c.id} className="bg-background rounded-2xl border border-border/50 p-3 flex items-center gap-3">
              <div className="w-9 h-9 rounded-xl flex-shrink-0" style={{ backgroundColor: c.color + "22" }}>
                <div className="w-full h-full flex items-center justify-center text-base">📣</div>
              </div>
              <div className="flex-1 min-w-0">
                <p className="font-semibold text-[13px] text-foreground truncate">{c.name}</p>
                <p className="text-[10px] text-muted-foreground">{c.reach.toLocaleString()} reach · {c.conversions} conv.</p>
              </div>
              <StatusBadge status={c.status} />
            </div>
          ))}
        </div>
      </div>

      {/* Recent content */}
      {history.length > 0 && (
        <div>
          <div className="flex items-center justify-between mb-2">
            <p className="text-[11px] font-bold text-foreground uppercase tracking-wider">Recent Content</p>
            <button onClick={() => setView("history")} className="text-[11px] text-primary font-medium hover:underline">View all →</button>
          </div>
          <div className="space-y-1.5">
            {history.slice(0, 3).map(h => (
              <div key={h.id} className="bg-background rounded-xl border border-border/50 px-3 py-2 flex items-center gap-2">
                <span className="text-base">{h.type === "social" ? "📲" : h.type === "email" ? "✉️" : h.type === "ad" ? "📣" : h.type === "blog" ? "📝" : "🎬"}</span>
                <p className="text-[12px] text-foreground truncate flex-1">{h.label}</p>
                <p className="text-[10px] text-muted-foreground flex-shrink-0">{h.createdAt.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</p>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Analytics link */}
      <button onClick={() => setView("analytics")}
        className="w-full bg-background border border-border/50 rounded-2xl p-4 flex items-center gap-3 hover:border-primary/20 hover:shadow-sm transition-all text-left">
        <span className="text-2xl">📊</span>
        <div>
          <p className="font-semibold text-[13px] text-foreground">View Analytics</p>
          <p className="text-[11px] text-muted-foreground">Open rate: {ANALYTICS.avgOpenRate} · Click rate: {ANALYTICS.avgClickRate} · Top: {ANALYTICS.topChannel}</p>
        </div>
        <span className="ml-auto text-muted-foreground">→</span>
      </button>
    </div>
  );
}

// ─── Content Generator ────────────────────────────────────────────────────

function GenerateView({ onResult }: { onResult: (r: GenResult) => void }) {
  const [contentType, setContentType] = useState<ContentType>("Social Post");
  const [platform,    setPlatform]    = useState<Platform>("Instagram");
  const [emailType,   setEmailType]   = useState<EmailType>("Welcome");
  const [tone,        setTone]        = useState<Tone>("Professional");
  const [topic,       setTopic]       = useState("");
  const [generating,  setGenerating]  = useState(false);

  const typeIcons: Record<ContentType, string> = {
    "Social Post": "📲", "Email": "✉️", "Ad Copy": "📣", "Blog Post": "📝", "Video Script": "🎬",
  };

  const handleGenerate = () => {
    if (!topic.trim()) return;
    setGenerating(true);
    setTimeout(() => {
      let r: GenResult;
      switch (contentType) {
        case "Social Post":   r = generateSocialPost(topic, platform, tone); break;
        case "Email":         r = generateEmail(topic, emailType, tone); break;
        case "Ad Copy":       r = generateAdCopy(topic, "Facebook/Instagram"); break;
        case "Blog Post":     r = generateBlog(topic, "medium"); break;
        case "Video Script":  r = generateVideoScript(topic, "Standard (3–5 min)"); break;
        default:              r = BrainGen.generate(topic); break;
      }
      setGenerating(false);
      onResult(r);
    }, 600);
  };

  return (
    <div className="space-y-5">
      <SectionHeader title="Generate Content" sub="Pick a type, describe your topic, and get it instantly." />

      {/* Content type selector */}
      <div>
        <p className="text-[12px] font-semibold text-muted-foreground mb-2">Content Type</p>
        <div className="grid grid-cols-5 gap-1.5">
          {(["Social Post", "Email", "Ad Copy", "Blog Post", "Video Script"] as ContentType[]).map(t => (
            <button key={t} onClick={() => setContentType(t)}
              className={`flex flex-col items-center gap-1 p-2.5 rounded-xl border text-center transition-all ${
                contentType === t ? "bg-primary text-white border-primary" : "bg-muted/40 text-muted-foreground border-border/50 hover:border-primary/30"
              }`}>
              <span className="text-xl">{typeIcons[t]}</span>
              <span className="text-[9px] font-semibold leading-tight">{t}</span>
            </button>
          ))}
        </div>
      </div>

      {/* Context-specific options */}
      {contentType === "Social Post" && (
        <SelectPills label="Platform" value={platform} onChange={(v) => setPlatform(v as Platform)}
          options={["Instagram", "LinkedIn", "Facebook", "Twitter", "TikTok", "General"]} />
      )}
      {contentType === "Email" && (
        <SelectPills label="Email Type" value={emailType} onChange={(v) => setEmailType(v as EmailType)}
          options={["Welcome", "Follow-Up", "Nurture", "Promotional"]} />
      )}

      <SelectPills label="Tone" value={tone} onChange={(v) => setTone(v as Tone)}
        options={["Professional", "Casual", "Enthusiastic", "Empathetic", "Bold"]} />

      {/* Topic input */}
      <div>
        <label className="text-[12px] font-semibold text-muted-foreground block mb-1.5">Topic / Description</label>
        <textarea value={topic} onChange={e => setTopic(e.target.value)}
          placeholder={
            contentType === "Social Post"  ? "e.g. The power of consistent morning routines for entrepreneurs" :
            contentType === "Email"        ? "e.g. Our new healthcare scheduling platform launch" :
            contentType === "Ad Copy"      ? "e.g. CreateAI Brain — the all-in-one business OS" :
            contentType === "Blog Post"    ? "e.g. How AI is transforming home health agencies" :
                                            "e.g. 5 reasons to start using AI in your business today"
          }
          className="w-full bg-background border border-border/50 rounded-xl p-3 text-[13px] text-foreground placeholder:text-muted-foreground resize-none outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary/30 transition-all"
          rows={3} />
      </div>

      {/* Quick topic chips */}
      <div>
        <p className="text-[11px] text-muted-foreground mb-1.5">Quick start:</p>
        <div className="flex flex-wrap gap-1.5">
          {[
            "Healthcare innovation",
            "Recurring revenue streams",
            "AI for small business",
            "Client retention strategy",
            "Horse boarding services",
          ].map(q => (
            <button key={q} onClick={() => setTopic(q)}
              className="text-[10px] bg-primary/10 text-primary border border-primary/20 hover:bg-primary/15 px-2.5 py-1 rounded-full transition-colors font-medium">
              {q}
            </button>
          ))}
        </div>
      </div>

      <button onClick={handleGenerate} disabled={!topic.trim() || generating}
        className="w-full bg-primary text-white text-sm font-semibold py-3 rounded-xl hover:opacity-90 transition-opacity disabled:opacity-40 flex items-center justify-center gap-2">
        {generating
          ? <><div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" /><span>Generating…</span></>
          : <span>Generate {typeIcons[contentType]} {contentType}</span>
        }
      </button>

      <p className="text-[10px] text-muted-foreground text-center">All content generated by CreateAI Brain · Internal use only</p>
    </div>
  );
}

// ─── Campaign Planner ─────────────────────────────────────────────────────

function CampaignView({ campaigns, onResult }: { campaigns: Campaign[]; onResult: (r: GenResult) => void }) {
  const [planGoal,     setPlanGoal]     = useState("");
  const [planAudience, setPlanAudience] = useState("");
  const [planTimeline, setPlanTimeline] = useState("4 weeks");
  const [planning,     setPlanning]     = useState(false);
  const [tab,          setTab]          = useState<"list" | "plan">("list");

  const handlePlan = () => {
    if (!planGoal.trim()) return;
    setPlanning(true);
    setTimeout(() => {
      const r = generateCampaign(planGoal, planAudience || "your target audience", planTimeline);
      setPlanning(false);
      onResult(r);
    }, 700);
  };

  return (
    <div className="space-y-4">
      <SectionHeader title="Campaigns" sub="Manage active campaigns and generate new campaign plans." />

      <div className="flex gap-1.5">
        {(["list", "plan"] as const).map(t => (
          <button key={t} onClick={() => setTab(t)}
            className={`flex-1 py-2 rounded-xl text-[12px] font-semibold transition-all ${tab === t ? "bg-primary text-white" : "bg-muted text-muted-foreground hover:bg-muted/80"}`}>
            {t === "list" ? "📋 Campaign List" : "✨ Plan a Campaign"}
          </button>
        ))}
      </div>

      {tab === "list" && (
        <div className="space-y-2">
          {campaigns.map(c => (
            <div key={c.id} className="bg-background rounded-2xl border border-border/50 p-4 space-y-2">
              <div className="flex items-center gap-2">
                <div className="w-9 h-9 rounded-xl flex items-center justify-center text-lg flex-shrink-0" style={{ backgroundColor: c.color + "22" }}>📣</div>
                <div className="flex-1 min-w-0">
                  <p className="font-semibold text-[13px] text-foreground">{c.name}</p>
                  <p className="text-[10px] text-muted-foreground">{c.goal} · {c.audience}</p>
                </div>
                <StatusBadge status={c.status} />
              </div>
              {c.reach > 0 && (
                <div className="grid grid-cols-3 gap-2 pt-1">
                  {[
                    { label: "Reach",        value: c.reach.toLocaleString() },
                    { label: "Conversions",  value: c.conversions.toString() },
                    { label: "Revenue",      value: c.revenue },
                  ].map(s => (
                    <div key={s.label} className="bg-muted/40 rounded-lg p-2 text-center">
                      <p className="text-[12px] font-bold text-foreground">{s.value}</p>
                      <p className="text-[9px] text-muted-foreground">{s.label}</p>
                    </div>
                  ))}
                </div>
              )}
            </div>
          ))}
        </div>
      )}

      {tab === "plan" && (
        <div className="space-y-4">
          <div>
            <label className="text-[12px] font-semibold text-muted-foreground block mb-1.5">Campaign Goal</label>
            <input value={planGoal} onChange={e => setPlanGoal(e.target.value)}
              placeholder="e.g. Generate 200 leads in 4 weeks"
              className="w-full bg-background border border-border/50 rounded-xl px-3 py-2.5 text-[13px] text-foreground placeholder:text-muted-foreground outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary/30 transition-all" />
          </div>
          <div>
            <label className="text-[12px] font-semibold text-muted-foreground block mb-1.5">Target Audience</label>
            <input value={planAudience} onChange={e => setPlanAudience(e.target.value)}
              placeholder="e.g. Small healthcare agencies, 10–50 employees"
              className="w-full bg-background border border-border/50 rounded-xl px-3 py-2.5 text-[13px] text-foreground placeholder:text-muted-foreground outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary/30 transition-all" />
          </div>
          <SelectPills label="Timeline" value={planTimeline} onChange={setPlanTimeline}
            options={["2 weeks", "4 weeks", "6 weeks", "8 weeks", "3 months"]} />
          <button onClick={handlePlan} disabled={!planGoal.trim() || planning}
            className="w-full bg-primary text-white text-sm font-semibold py-3 rounded-xl hover:opacity-90 transition-opacity disabled:opacity-40 flex items-center justify-center gap-2">
            {planning
              ? <><div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" /><span>Planning…</span></>
              : "Generate Campaign Plan"
            }
          </button>
        </div>
      )}
    </div>
  );
}

// ─── Analytics ────────────────────────────────────────────────────────────

function AnalyticsView() {
  const stats = [
    { label: "Total Reach",        value: ANALYTICS.totalReach,       icon: "👁️",  color: "#007AFF" },
    { label: "Total Conversions",  value: ANALYTICS.totalConversions, icon: "🎯",  color: "#34C759" },
    { label: "Est. Revenue",       value: ANALYTICS.totalRevenue,     icon: "💰",  color: "#FF9500" },
    { label: "Avg Open Rate",      value: ANALYTICS.avgOpenRate,      icon: "📧",  color: "#5856D6" },
    { label: "Avg Click Rate",     value: ANALYTICS.avgClickRate,     icon: "👆",  color: "#FF2D55" },
    { label: "Top Channel",        value: ANALYTICS.topChannel,       icon: "🏆",  color: "#30B0C7" },
  ];

  const channels = [
    { name: "Email",     pct: 42, color: "#007AFF" },
    { name: "Social",    pct: 28, color: "#34C759" },
    { name: "Paid Ads",  pct: 18, color: "#FF9500" },
    { name: "Organic",   pct: 12, color: "#BF5AF2" },
  ];

  return (
    <div className="space-y-5">
      <SectionHeader title="Analytics" sub="Campaign performance overview — internal mock data." />

      <div className="grid grid-cols-2 gap-2">
        {stats.map(s => (
          <div key={s.label} className="bg-background rounded-2xl border border-border/50 p-3 flex items-center gap-2.5">
            <div className="w-9 h-9 rounded-xl flex items-center justify-center text-lg flex-shrink-0" style={{ backgroundColor: s.color + "22" }}>
              {s.icon}
            </div>
            <div className="min-w-0">
              <p className="text-[15px] font-bold text-foreground">{s.value}</p>
              <p className="text-[10px] text-muted-foreground">{s.label}</p>
            </div>
          </div>
        ))}
      </div>

      {/* Channel breakdown */}
      <div className="bg-background rounded-2xl border border-border/50 p-4 space-y-3">
        <p className="text-[12px] font-bold text-foreground uppercase tracking-wider">Channel Breakdown</p>
        {channels.map(ch => (
          <div key={ch.name} className="space-y-1">
            <div className="flex justify-between text-[12px]">
              <span className="font-medium text-foreground">{ch.name}</span>
              <span className="text-muted-foreground">{ch.pct}%</span>
            </div>
            <div className="w-full bg-muted rounded-full h-2">
              <div className="h-2 rounded-full transition-all" style={{ width: `${ch.pct}%`, backgroundColor: ch.color }} />
            </div>
          </div>
        ))}
      </div>

      {/* Top campaign */}
      <div className="bg-primary/10 border border-primary/20 rounded-2xl p-4 space-y-1">
        <p className="text-[10px] font-bold text-primary uppercase tracking-wider">Top Performing Campaign</p>
        <p className="font-bold text-foreground">{ANALYTICS.topCampaign}</p>
        <p className="text-[12px] text-muted-foreground">9,100 reach · 540 conversions · $42,660 est. revenue</p>
      </div>

      <p className="text-[10px] text-muted-foreground text-center">All analytics are mock/internal. No real tracking. Demo-only.</p>
    </div>
  );
}

// ─── History ──────────────────────────────────────────────────────────────

function HistoryView({ history, onSelect }: { history: GenResult[]; onSelect: (r: GenResult) => void }) {
  const typeIcons: Record<string, string> = {
    social: "📲", email: "✉️", ad: "📣", blog: "📝", video: "🎬",
    campaign: "📋", general: "✨",
  };

  if (history.length === 0) {
    return (
      <div className="text-center py-16 space-y-3">
        <p className="text-4xl">📭</p>
        <p className="font-semibold text-foreground">No content generated yet</p>
        <p className="text-[12px] text-muted-foreground">Use the Generate tab to create your first piece.</p>
      </div>
    );
  }

  return (
    <div className="space-y-4">
      <SectionHeader title="Content History" sub={`${history.length} item${history.length !== 1 ? "s" : ""} generated`} />
      <div className="space-y-2">
        {history.map(h => (
          <button key={h.id} onClick={() => onSelect(h)}
            className="w-full flex items-start gap-3 p-3.5 bg-background rounded-2xl border border-border/50 hover:border-primary/20 hover:shadow-sm transition-all text-left">
            <span className="text-xl flex-shrink-0 mt-0.5">{typeIcons[h.type] ?? "✨"}</span>
            <div className="flex-1 min-w-0">
              <p className="font-semibold text-[13px] text-foreground truncate">{h.label}</p>
              <p className="text-[10px] text-muted-foreground mt-0.5">{h.createdAt.toLocaleTimeString()}</p>
            </div>
            <span className="text-muted-foreground text-xs mt-1 flex-shrink-0">→</span>
          </button>
        ))}
      </div>
    </div>
  );
}

// ─── Main App ─────────────────────────────────────────────────────────────

export function MarketingApp() {
  const [view,      setView]      = useState<MarketingView>("home");
  const [history,   setHistory]   = useState<GenResult[]>([]);
  const [activeResult, setActiveResult] = useState<GenResult | null>(null);
  const [campaigns, setCampaigns] = useState<Campaign[]>(SEED_CAMPAIGNS);

  const NAV = [
    { id: "home",      label: "Home",     icon: "🏠" },
    { id: "generate",  label: "Create",   icon: "✨" },
    { id: "campaign",  label: "Campaigns",icon: "📣" },
    { id: "analytics", label: "Analytics",icon: "📊" },
    { id: "history",   label: "History",  icon: "📂" },
  ];

  const handleResult = (r: GenResult) => {
    setHistory(prev => [r, ...prev]);
    setActiveResult(r);
    setView("result");
  };

  return (
    <div className="flex flex-col h-full">
      {/* Top nav */}
      <div className="flex-none border-b" style={{ background: "rgba(8,10,22,0.80)", borderColor: "rgba(255,255,255,0.07)", backdropFilter: "blur(24px)" }}>
        <div className="flex overflow-x-auto px-2 py-1.5 gap-0.5 no-scrollbar">
          {NAV.map(n => (
            <button key={n.id} onClick={() => setView(n.id as MarketingView)}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-[11px] font-semibold whitespace-nowrap transition-all duration-150 flex-shrink-0 ${
                view === n.id || (view === "result" && n.id === "history")
                  ? "text-white"
                  : "text-muted-foreground hover:text-foreground"
              }`}
              style={
                view === n.id || (view === "result" && n.id === "history")
                  ? { background: "linear-gradient(135deg, #6366f1 0%, #5457d8 100%)", boxShadow: "0 2px 8px rgba(99,102,241,0.35)" }
                  : {}
              }
              onMouseEnter={e => {
                if (view !== n.id) (e.currentTarget as HTMLElement).style.background = "rgba(255,255,255,0.07)";
              }}
              onMouseLeave={e => {
                if (view !== n.id) (e.currentTarget as HTMLElement).style.background = "";
              }}
            >
              <span>{n.icon}</span>
              <span>{n.label}</span>
            </button>
          ))}
          <div className="ml-auto flex items-center px-2">
            <span className="text-[10px] text-muted-foreground/60">{history.length} generated</span>
          </div>
        </div>
      </div>

      {/* Content */}
      <div className="flex-1 overflow-y-auto p-4">
        {view === "result" && activeResult
          ? <ResultViewer item={activeResult} onBack={() => setView("history")}
              onSave={() => setHistory(prev => prev.find(h => h.id === activeResult.id) ? prev : [activeResult, ...prev])} />
          : view === "home"
          ? <HomeView setView={setView} campaigns={campaigns} history={history} />
          : view === "generate"
          ? <GenerateView onResult={handleResult} />
          : view === "campaign"
          ? <CampaignView campaigns={campaigns} onResult={handleResult} />
          : view === "analytics"
          ? <AnalyticsView />
          : view === "history"
          ? <HistoryView history={history} onSelect={r => { setActiveResult(r); setView("result"); }} />
          : null
        }
      </div>
    </div>
  );
}
