import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import openaiRouter from "./openai";
import projectsRouter from "./projects";
import brainstormRouter from "./brainstorm";
import projectChatRouter from "./projectChat";
import userRouter from "./user";
import activityRouter from "./activity";
import conversationsRouter from "./conversations";
import integrationsRouter from "./integrations";
import peopleRouter from "./people";
import notificationsRouter from "./notifications";
import documentsRouter from "./documents";
import tasksRouter from "./tasks";
import membersRouter from "./project_members";
import tractionRouter from "./traction";
import metricsRouter from "./metrics";
import opportunitiesRouter from "./opportunities";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use("/openai", openaiRouter);
router.use("/projects", projectsRouter);
router.use("/projects", tasksRouter);
router.use("/projects", membersRouter);
router.use("/brainstorm", brainstormRouter);
router.use("/project-chat", projectChatRouter);
router.use("/user", userRouter);
router.use("/activity", activityRouter);
router.use("/conversations", conversationsRouter);
router.use("/integrations", integrationsRouter);
router.use("/people", peopleRouter);
router.use("/notifications", notificationsRouter);
router.use("/documents", documentsRouter);
router.use("/traction", tractionRouter);
router.use("/metrics",  metricsRouter);
router.use("/opportunities", opportunitiesRouter);

export default router;
