import React from "react";

const SAGE = "#7a9068";

interface PrintableOutputProps {
  title:     string;
  content:   string;
  appLabel?: string;
  createdAt?: number;
}

export function PrintableOutput({ title, content, appLabel, createdAt }: PrintableOutputProps) {
  const dateStr = createdAt
    ? new Date(createdAt).toLocaleString("en-US", {
        month: "long", day: "numeric", year: "numeric",
        hour: "numeric", minute: "2-digit",
      })
    : new Date().toLocaleString("en-US", {
        month: "long", day: "numeric", year: "numeric",
        hour: "numeric", minute: "2-digit",
      });

  return (
    <div
      id="printable-output"
      style={{
        fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
        maxWidth: 740,
        margin: "0 auto",
        padding: "48px 40px",
        background: "#ffffff",
        color: "#1a1916",
      }}
    >
      {/* Header */}
      <div style={{ borderBottom: `3px solid ${SAGE}`, paddingBottom: 24, marginBottom: 32 }}>
        <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 12 }}>
          <div
            style={{
              background: SAGE,
              color: "white",
              borderRadius: 10,
              padding: "6px 14px",
              fontSize: 11,
              fontWeight: 700,
              letterSpacing: "0.08em",
              textTransform: "uppercase",
            }}
          >
            CreateAI Brain
          </div>
          {appLabel && (
            <span style={{ fontSize: 12, color: "#6b6660", fontWeight: 600 }}>
              {appLabel}
            </span>
          )}
        </div>
        <h1 style={{ margin: 0, fontSize: 26, fontWeight: 800, color: "#1a1916", lineHeight: 1.3 }}>
          {title}
        </h1>
        <p style={{ margin: "8px 0 0", fontSize: 13, color: "#6b6660" }}>{dateStr}</p>
      </div>

      {/* Body */}
      <div
        style={{
          fontSize: 15,
          lineHeight: 1.75,
          color: "#1a1916",
          whiteSpace: "pre-wrap",
          wordBreak: "break-word",
        }}
      >
        {content}
      </div>

      {/* Footer */}
      <div
        style={{
          marginTop: 48,
          paddingTop: 20,
          borderTop: "1px solid #e5e7eb",
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
        }}
      >
        <span style={{ fontSize: 11, color: "#9ca3af" }}>
          Generated by CreateAI Brain · Lakeside Trinity LLC
        </span>
        <span style={{ fontSize: 11, color: "#9ca3af" }}>createai.digital</span>
      </div>
    </div>
  );
}
