import { streamEngine } from "@/controller";
export interface CharacterForgeEngineDefinition { id: string; name: string; icon: string; color: string; tagline: string; description: string; placeholder: string; example: string; series?: string; }
export interface CharacterForgeSeriesDefinition { id: string; name: string; symbol: string; icon: string; gradient: string; description: string; engines: string[]; estimatedMinutes: number; }

export const CHARACTERFORGE_ENGINES: CharacterForgeEngineDefinition[] = [
  { id: "BackstoryEngine",      name: "Backstory Engine",       icon: "📖", color: "#6366f1", tagline: "Origin Architect",        description: "Designs the lived history of a character — the specific events that made them who they are, in full sensory detail.",              placeholder: "What backstory should this character have?",           example: "e.g. A character who was the sole survivor of something that wasn't actually as terrible as they've made it in their mind",          series: "wound"     },
  { id: "WoundEngine",          name: "Wound Engine",           icon: "💔", color: "#dc2626", tagline: "Core Wound Architect",    description: "Designs the character's core wound — the formative damage that shapes every choice they make, often without their knowing it.",    placeholder: "What is this character's core wound?",                 example: "e.g. A character whose wound is being believed when they were lying and doubted when they were telling the truth — permanently",      series: "wound"     },
  { id: "WantVsNeedEngine",     name: "Want vs Need Engine",    icon: "⚖️", color: "#d97706", tagline: "Desire Architect",        description: "Defines what a character thinks they want versus what they actually need — and the arc of learning the difference.",             placeholder: "What does this character want vs what do they need?",  example: "e.g. A character who wants to be left alone but needs to learn that their isolation is a choice disguised as fate",                  series: "arc"       },
  { id: "MoralCodeEngine",      name: "Moral Code Engine",      icon: "⚖️", color: "#0891b2", tagline: "Ethics Architect",        description: "Designs the character's moral framework — what they will and won't do, where those lines come from, and how the story tests them.",  placeholder: "What is this character's moral code?",                 example: "e.g. A character with a rigid honor code that protects them from having to make real moral choices — and what breaks it",            series: "mask"      },
  { id: "VoiceEngine",          name: "Voice Engine",           icon: "🗣️", color: "#7c3aed", tagline: "Voice Architect",         description: "Designs how a character speaks — their vocabulary, cadence, what they never say directly, and what their language reveals.",        placeholder: "How does this character speak and express themselves?", example: "e.g. A character who communicates everything through questions — they never make a direct statement and you have to decode them",     series: "voice"     },
  { id: "FlawEngine",           name: "Flaw Engine",            icon: "🪨", color: "#be185d", tagline: "Flaw Architect",          description: "Designs genuine, story-relevant character flaws — not quirks, but actual failures that cost the character and those around them.", placeholder: "What is this character's central flaw?",               example: "e.g. A character whose flaw is solving every problem with action — they cannot sit with uncertainty for even one moment",            series: "wound"     },
  { id: "SecretEngine",         name: "Secret Engine",          icon: "🔒", color: "#374151", tagline: "Hidden Truth Architect",  description: "Designs what a character is hiding — from others, from themselves — and what it would cost them for it to be known.",              placeholder: "What secret does this character carry?",               example: "e.g. A character who is hiding the fact that they're happy with how things turned out — and the shame that brings them",             series: "mask"      },
  { id: "RelationshipWebEngine",name: "Relationship Web Engine",icon: "🕸️", color: "#15803d", tagline: "Connection Architect",    description: "Maps who this character loves, fears, owes, and resents — and how those relationships are the real plot of their story.",          placeholder: "Who are the key relationships in this character's life?",example: "e.g. A character whose three most important relationships are all with people who don't know the others exist",                    series: "arc"       },
  { id: "ChangeArcEngine",      name: "Change Arc Engine",      icon: "🦋", color: "#ca8a04", tagline: "Arc Architect",           description: "Designs the character's transformation arc — positive change, negative change, or flat arc — and what causes each beat of change.", placeholder: "What is this character's transformation arc?",          example: "e.g. A character who appears to change completely but returns at the end to exactly who they were — and this is tragic, not triumphant", series: "arc"   },
  { id: "MaskEngine",           name: "Mask Engine",            icon: "🎭", color: "#78350f", tagline: "Persona Architect",       description: "Designs the face a character shows the world versus who they actually are — and the gap between them.",                           placeholder: "What mask does this character wear and why?",          example: "e.g. A character whose public persona is so convincing they've forgotten who they were before they put it on",                       series: "mask"      },
  { id: "ObsessionEngine",      name: "Obsession Engine",       icon: "🌀", color: "#0f766e", tagline: "Obsession Architect",     description: "Designs what a character is obsessed with — the thing that distorts their perception and makes them unreliable in specific ways.", placeholder: "What is this character obsessed with and why?",         example: "e.g. A character obsessed with fairness who unconsciously rigs every situation to create the fairness they're looking for",         series: "wound"     },
  { id: "DecisionEngine",       name: "Decision Engine",        icon: "🎯", color: "#6b7280", tagline: "Choice Architect",        description: "Designs the key decisions that define a character — the moments where their nature is revealed in what they choose when it's hard.", placeholder: "What are the defining decisions in this character's life?",example: "e.g. Design 5 pivotal decisions this character made and 5 they almost made — and how each path would have changed them",        series: "arc"       },
  { id: "DeathEngine",          name: "Death Engine",           icon: "💀", color: "#4b5563", tagline: "End Architect",           description: "Designs how a character dies — the right death for who they are, what it means, and what survives them in the world and in others.", placeholder: "How should this character die and what does it mean?",  example: "e.g. A character who dies performing an act that contradicts everything they stood for — and the reader understands why they did it", series: "arc"    },
];

export const CHARACTERFORGE_SERIES: CharacterForgeSeriesDefinition[] = [
  { id: "wound",  name: "WOUND-Series",      symbol: "WO", icon: "💔", gradient: "linear-gradient(135deg,#dc2626,#6366f1,#0f766e)", description: "Core Damage — Backstory, Wound, Flaw, and Obsession — the formative damage that drives a character.",        engines: ["BackstoryEngine","WoundEngine","FlawEngine","ObsessionEngine"],              estimatedMinutes: 4 },
  { id: "mask",   name: "MASK-Series",       symbol: "MA", icon: "🎭", gradient: "linear-gradient(135deg,#78350f,#374151,#be185d)", description: "Hidden Self — Mask, Secret, and Moral Code — the gap between who a character is and who they appear to be.",   engines: ["MaskEngine","SecretEngine","MoralCodeEngine"],                               estimatedMinutes: 3 },
  { id: "arc",    name: "ARC-Series",        symbol: "AR", icon: "🦋", gradient: "linear-gradient(135deg,#ca8a04,#d97706,#15803d)", description: "Transformation — Want vs Need, Change Arc, Relationships, and Decisions — the story of a person changing.",    engines: ["WantVsNeedEngine","ChangeArcEngine","RelationshipWebEngine","DecisionEngine"],estimatedMinutes: 4 },
  { id: "voice",  name: "VOICE-Series",      symbol: "VO", icon: "🗣️", gradient: "linear-gradient(135deg,#7c3aed,#0891b2,#6b7280)", description: "Expression — Voice, Mask, and Secret — how a character speaks, performs, and what they never say directly.",    engines: ["VoiceEngine","MaskEngine","SecretEngine"],                                   estimatedMinutes: 3 },
  { id: "shadow", name: "SHADOW-SELF-Series",symbol: "SS", icon: "🌀", gradient: "linear-gradient(135deg,#374151,#4b5563,#78350f)", description: "Full Character — Wound, Obsession, Death, and Arc — the complete psychological portrait of a character.",      engines: ["WoundEngine","ObsessionEngine","DeathEngine","ChangeArcEngine"],             estimatedMinutes: 4 },
];

export async function runCharacterForgeEngine(opts: { engineId: string; engineName: string; topic: string; onChunk: (t: string) => void; onDone?: () => void; onError?: (e: string) => void; }): Promise<void> {
  const { engineId, topic, onChunk, onDone, onError } = opts;
  await streamEngine({ engineId, topic, onChunk, onDone: onDone ? () => onDone() : undefined, onError });
}
