import { streamEngine, streamSeries } from "@/controller";
// ═══════════════════════════════════════════════════════════════════════════
// CIVILIZATION ENGINE — CivilizationForge Frontend Intelligence Layer
// 13 society-building engines + 5 series. Fictional, safe, family-friendly.
// ═══════════════════════════════════════════════════════════════════════════

export interface CivilizationEngineDefinition {
  id: string; name: string; icon: string; color: string; gradient: string;
  tagline: string; description: string; placeholder: string; example: string; series?: string;
}

export const CIVILIZATION_ENGINES: CivilizationEngineDefinition[] = [
  { id: "EconomyEngine", name: "Economy Engine", icon: "💰", color: "#d97706", gradient: "linear-gradient(135deg, #d97706, #b45309)", tagline: "Economy Architect", description: "Designs fictional economic systems — currency, production, distribution, inequality, and the stories economics generates.", placeholder: "What economy should I design?", example: "e.g. An economy where memory can be bottled and sold, creating a class of people who sell their childhood to survive", series: "society" },
  { id: "PoliticalSystemEngine", name: "Political System Engine", icon: "🏛️", color: "#1d4ed8", gradient: "linear-gradient(135deg, #1d4ed8, #1e40af)", tagline: "Politics Architect", description: "Designs fictional political systems — governance structures, power sources, legitimacy, and how power changes hands.", placeholder: "What political system should I design?", example: "e.g. A republic where only people who have lost a child may vote, believing grief grants wisdom", series: "power" },
  { id: "SocialStrataEngine", name: "Social Strata Engine", icon: "⬆️", color: "#7c3aed", gradient: "linear-gradient(135deg, #7c3aed, #6d28d9)", tagline: "Strata Architect", description: "Designs fictional class systems — how social mobility works, what determines status, and the stories between the strata.", placeholder: "What social class system should I design?", example: "e.g. A society stratified by what kind of work your hands have done — those who have never worked with their hands are the lowest class", series: "society" },
  { id: "CulturalTraditionEngine", name: "Cultural Tradition Engine", icon: "🎎", color: "#be185d", gradient: "linear-gradient(135deg, #be185d, #db2777)", tagline: "Tradition Architect", description: "Creates fictional customs, ceremonies, taboos, coming-of-age rituals, and the traditions that hold a culture together.", placeholder: "What cultural tradition should I create?", example: "e.g. A culture where every major life decision is announced publicly in song, because keeping silent intentions is considered dishonest", series: "culture" },
  { id: "ArchitectureStyleEngine", name: "Architecture Engine", icon: "🏗️", color: "#0f766e", gradient: "linear-gradient(135deg, #0f766e, #0d9488)", tagline: "Architecture Architect", description: "Designs fictional architectural styles — the values a civilization builds into its structures, spaces, and cities.", placeholder: "What architectural style should I design?", example: "e.g. A culture that builds every structure to eventually collapse, believing permanence is a form of hubris against nature", series: "culture" },
  { id: "LawSystemEngine", name: "Law System Engine", icon: "⚖️", color: "#1e40af", gradient: "linear-gradient(135deg, #1e40af, #1d4ed8)", tagline: "Law Architect", description: "Designs fictional legal systems — how justice is defined, who enforces it, who escapes it, and the stories it creates.", placeholder: "What legal system should I design?", example: "e.g. A society where punishment is determined not by the crime but by what the criminal most values and fears to lose", series: "power" },
  { id: "TradeRouteEngine", name: "Trade Route Engine", icon: "🗺️", color: "#78350f", gradient: "linear-gradient(135deg, #78350f, #92400e)", tagline: "Trade Architect", description: "Designs fictional trade routes — what moves along them, who controls them, and the civilizations they connect or divide.", placeholder: "What trade route should I design?", example: "e.g. A trade route that can only be navigated by people born under a specific moon, creating a hereditary merchant caste", series: "economy" },
  { id: "WarfareDoctrineEngine", name: "Warfare Doctrine Engine", icon: "⚔️", color: "#dc2626", gradient: "linear-gradient(135deg, #dc2626, #991b1b)", tagline: "Warfare Architect", description: "Designs fictional military philosophy — how a culture fights, what it considers honorable in war, and what victory means.", placeholder: "What warfare doctrine should I design?", example: "e.g. A culture that considers killing in battle a failure — the highest military achievement is capturing an enemy's surrender without a single death", series: "power" },
  { id: "CelebrationEngine", name: "Celebration Engine", icon: "🎉", color: "#d946ef", gradient: "linear-gradient(135deg, #d946ef, #c026d3)", tagline: "Celebration Architect", description: "Creates fictional festivals, feasts, anniversaries, and commemorations — how a culture marks what it values most.", placeholder: "What celebration should I create?", example: "e.g. A week-long festival where every person in the city is required to perform an act of service for a stranger", series: "culture" },
  { id: "FoodCultureEngine", name: "Food Culture Engine", icon: "🍲", color: "#16a34a", gradient: "linear-gradient(135deg, #16a34a, #15803d)", tagline: "Food Architect", description: "Designs fictional culinary traditions — what a people eat, how they prepare it, what it means, and how food marks identity.", placeholder: "What food culture should I design?", example: "e.g. A culture where the meal you cook for someone on their deathbed is considered your most important act of love", series: "culture" },
  { id: "FashionEraEngine", name: "Fashion Era Engine", icon: "👗", color: "#ec4899", gradient: "linear-gradient(135deg, #ec4899, #db2777)", tagline: "Fashion Architect", description: "Designs fictional fashion eras — what a civilization wears, what clothing communicates, and how style encodes power.", placeholder: "What fashion era should I design?", example: "e.g. An era where the wealthiest wear undyed plain cloth, because color has become the mark of the working class", series: "economy" },
  { id: "SportsCultureEngine", name: "Sports Culture Engine", icon: "🏆", color: "#ca8a04", gradient: "linear-gradient(135deg, #ca8a04, #a16207)", tagline: "Sports Architect", description: "Invents fictional sports, competitions, and games — how they are played, what they mean, and who is allowed to compete.", placeholder: "What sport or competition should I design?", example: "e.g. A sport where teams compete to build the most beautiful structure in 48 hours, judged by the losing team's children", series: "economy" },
  { id: "InstitutionEngine", name: "Institution Engine", icon: "🏫", color: "#6b7280", gradient: "linear-gradient(135deg, #6b7280, #4b5563)", tagline: "Institution Architect", description: "Designs fictional institutions — schools, courts, hospitals, guilds — their purpose, their dysfunction, and their hidden power.", placeholder: "What institution should I design?", example: "e.g. A hospital where healers are forbidden from charging for services but may accept gratitude as legally binding contracts", series: "society" },
];

export interface CivilizationSeriesDefinition {
  id: string; name: string; symbol: string; icon: string; gradient: string; description: string; engines: string[]; estimatedMinutes: number;
}

export const CIVILIZATION_SERIES: CivilizationSeriesDefinition[] = [
  { id: "society", name: "SOCIETY-Series", symbol: "SO", icon: "🏛️", gradient: "linear-gradient(135deg, #d97706, #7c3aed, #6b7280)", description: "Social Trifecta — Economy, Social Strata, and Institution — the bones of how a civilization organizes itself.", engines: ["EconomyEngine", "SocialStrataEngine", "InstitutionEngine"], estimatedMinutes: 3 },
  { id: "power", name: "POWER-Series", symbol: "PW", icon: "⚖️", gradient: "linear-gradient(135deg, #1d4ed8, #dc2626, #1e40af)", description: "Power Trifecta — Political System, Law System, and Warfare Doctrine — how a civilization takes and keeps control.", engines: ["PoliticalSystemEngine", "LawSystemEngine", "WarfareDoctrineEngine"], estimatedMinutes: 3 },
  { id: "culture", name: "CULTURE-Series", symbol: "CU", icon: "🎎", gradient: "linear-gradient(135deg, #be185d, #0f766e, #d946ef)", description: "Culture Trifecta — Tradition, Architecture, and Celebration — how a civilization expresses what it believes.", engines: ["CulturalTraditionEngine", "ArchitectureStyleEngine", "CelebrationEngine"], estimatedMinutes: 3 },
  { id: "economy", name: "ECONOMY-Series", symbol: "EC", icon: "💰", gradient: "linear-gradient(135deg, #78350f, #ec4899, #ca8a04)", description: "Commerce Trifecta — Trade Route, Fashion Era, and Sports Culture — how a civilization moves wealth and status.", engines: ["TradeRouteEngine", "FashionEraEngine", "SportsCultureEngine"], estimatedMinutes: 3 },
  { id: "lifeways", name: "LIFEWAYS-Series", symbol: "LW", icon: "🍲", gradient: "linear-gradient(135deg, #16a34a, #be185d, #d97706)", description: "Daily Life Trifecta — Food Culture, Tradition, and Institution — how ordinary people live inside a civilization.", engines: ["FoodCultureEngine", "CulturalTraditionEngine", "InstitutionEngine"], estimatedMinutes: 3 },
];

export function getCivilizationEngineById(id: string): CivilizationEngineDefinition | undefined { return CIVILIZATION_ENGINES.find(e => e.id === id); }
export function getCivilizationEngineColor(id: string): string { return getCivilizationEngineById(id)?.color ?? "#d97706"; }
export function getCivilizationEngineIcon(id: string): string { return getCivilizationEngineById(id)?.icon ?? "🏛️"; }

export async function runCivilizationEngine(opts: { engineId: string; engineName: string; topic: string; context?: string; onChunk: (t: string) => void; onDone?: () => void; onError?: (e: string) => void; }): Promise<void> {
  const { engineId, topic, context, onChunk, onDone, onError } = opts;
  await streamEngine({ engineId, topic, context, onChunk, onDone: onDone ? () => onDone() : undefined, onError });
}

export async function runCivilizationSeries(opts: { seriesId: string; topic: string; context?: string; onSectionStart: (id: string, i: number) => void; onChunk: (t: string) => void; onSectionEnd: (id: string) => void; onDone?: () => void; onError?: (e: string) => void; }): Promise<void> {
  await streamSeries({ seriesId: opts.seriesId, topic: opts.topic, context: opts.context, onSectionStart: opts.onSectionStart, onChunk: opts.onChunk, onSectionEnd: opts.onSectionEnd, onDone: opts.onDone, onError: opts.onError });
}
