import { streamEngine } from "@/controller";
export interface CosmologyForgeEngineDefinition { id: string; name: string; icon: string; color: string; tagline: string; description: string; placeholder: string; example: string; series?: string; }
export interface CosmologyForgeSeriesDefinition { id: string; name: string; symbol: string; icon: string; gradient: string; description: string; engines: string[]; estimatedMinutes: number; }

export const COSMOLOGYFORGE_ENGINES: CosmologyForgeEngineDefinition[] = [
  { id: "UniversePhysicsEngine",   name: "Universe Physics Engine",   icon: "⚛️", color: "#6366f1", tagline: "Cosmos Architect",         description: "Designs the fundamental physics of a fictional universe — what laws govern it, what constants differ from ours, and what that changes.", placeholder: "What physics govern this universe?",                  example: "e.g. A universe where entropy runs backward in pockets — zones of time reversal that the laws of physics refuse to explain",        series: "creation" },
  { id: "PlaneOfExistenceEngine",  name: "Plane of Existence Engine", icon: "🌐", color: "#7c3aed", tagline: "Planes Architect",          description: "Designs the planes and dimensions of a fictional cosmos — what exists beyond the mortal world, how to travel there, and what rules change.", placeholder: "What planes of existence should I design?",          example: "e.g. A plane of pure intention where nothing has happened yet — and what it's like to visit a place where everything is still potential", series: "planes"   },
  { id: "CreationMythEngine",      name: "Creation Myth Engine",      icon: "🌌", color: "#be185d", tagline: "Origin Architect",          description: "Designs the creation myth of a fictional universe — what existed before, what event started everything, and what it means.",           placeholder: "How was this universe created?",                     example: "e.g. A universe created by a god who immediately died of the effort — and the cosmos is the aftermath of divine death",              series: "creation" },
  { id: "DeityHierarchyEngine",    name: "Deity Hierarchy Engine",    icon: "👑", color: "#d97706", tagline: "Divine Order Architect",    description: "Designs the structure of divine power — how gods relate to each other, what they fight over, and whether they answer to anything.", placeholder: "What is the hierarchy of gods in this cosmos?",       example: "e.g. A cosmos where all gods are equal but one holds the deciding vote in any dispute — and has never used it",                     series: "divinwar" },
  { id: "DeathMechanicsEngine",    name: "Death Mechanics Engine",    icon: "💀", color: "#374151", tagline: "Death System Architect",    description: "Designs how death works as a cosmic mechanic — where souls go, who processes them, and what happens when the system breaks.",       placeholder: "How does death work mechanically in this cosmos?",   example: "e.g. A cosmos where death is administered by a bureaucracy that has a 300-year backlog — the recently dead must wait",              series: "void"     },
  { id: "SoulSystemEngine",        name: "Soul System Engine",        icon: "✨", color: "#ca8a04", tagline: "Soul Architect",            description: "Designs how souls work in a fictional cosmos — what they are, who has one, what can be done to them, and whether they can be destroyed.", placeholder: "How do souls work in this cosmos?",                 example: "e.g. A cosmos where souls are the universe's memory — every soul is a record of every choice ever made by every living being",      series: "void"     },
  { id: "CosmicConflictEngine",    name: "Cosmic Conflict Engine",    icon: "⚔️", color: "#dc2626", tagline: "Divine War Architect",      description: "Designs the great conflicts of a fictional cosmos — wars between gods, between planes, between fundamental forces.",               placeholder: "What cosmic conflict defines this universe?",         example: "e.g. A war between the god of cause and the god of effect that has been going on so long no one can remember who started it",       series: "divinwar" },
  { id: "VoidEngine",              name: "Void Engine",               icon: "🌑", color: "#1d4ed8", tagline: "Nothing Architect",         description: "Designs the void or chaos that exists outside or beneath the ordered cosmos — and what happens when it leaks in.",               placeholder: "What is the void or chaos in this cosmos?",          example: "e.g. A void that isn't emptiness but a kind of anti-meaning — everything it touches stops making sense rather than ceasing to exist", series: "void"   },
  { id: "LiminalPlaneEngine",      name: "Liminal Plane Engine",      icon: "🚪", color: "#0891b2", tagline: "In-Between Architect",      description: "Designs the in-between spaces of a cosmos — purgatory, threshold planes, bardo states, and what lives in the cracks between worlds.",  placeholder: "What liminal planes exist between the main planes?",  example: "e.g. A plane that exists only during transitions — you can only enter it while changing your mind about something",                  series: "planes"   },
  { id: "AscensionEngine",         name: "Ascension Engine",          icon: "⬆️", color: "#15803d", tagline: "Godhood Architect",         description: "Designs how mortals can become divine — the paths to ascension, what it costs, and what you lose when you stop being mortal.",       placeholder: "How can mortals ascend to divinity in this cosmos?",  example: "e.g. Ascension requires a mortal to be genuinely forgotten by every being who ever knew them — gods are the truly alone",            series: "divinwar" },
  { id: "ProphecyMechanicsEngine", name: "Prophecy Mechanics Engine", icon: "🔮", color: "#0f766e", tagline: "Fate Mechanics Architect",  description: "Designs how prophecy actually works as a cosmic system — who issues it, how it propagates, and whether it can ever be wrong.",      placeholder: "How does prophecy work mechanically in this cosmos?", example: "e.g. Prophecies are spoken by the universe itself in moments of instability — they predict whatever would restore balance fastest",  series: "creation" },
  { id: "UniverseCollapseEngine",  name: "Universe Collapse Engine",  icon: "💥", color: "#78350f", tagline: "End Times Architect",       description: "Designs the end of a fictional universe — the eschatological event, the stages of collapse, and what (if anything) comes after.",   placeholder: "How does this universe end?",                        example: "e.g. The universe ends not with a bang but with every being simultaneously losing the will to continue — a cosmic exhaustion",        series: "endofall" },
  { id: "MultiverseEngine",        name: "Multiverse Engine",         icon: "∞",  color: "#6b7280", tagline: "Many Worlds Architect",     description: "Designs the multiverse structure of a fictional cosmos — how many universes exist, how they differ, and whether they interact.",   placeholder: "What multiverse structure does this cosmos have?",    example: "e.g. An infinite multiverse where every universe is aware of one other universe — and they have been in conversation for eons",      series: "planes"   },
];

export const COSMOLOGYFORGE_SERIES: CosmologyForgeSeriesDefinition[] = [
  { id: "creation", name: "CREATION-Series",  symbol: "CR", icon: "🌌", gradient: "linear-gradient(135deg,#6366f1,#be185d,#0f766e)", description: "Origins — Universe Physics, Creation Myth, and Prophecy Mechanics — how and why the universe began.", engines: ["UniversePhysicsEngine","CreationMythEngine","ProphecyMechanicsEngine"],     estimatedMinutes: 3 },
  { id: "planes",   name: "PLANES-Series",    symbol: "PL", icon: "🌐", gradient: "linear-gradient(135deg,#7c3aed,#0891b2,#6b7280)", description: "Cosmological Map — Planes of Existence, Liminal Plane, and Multiverse — the structure of reality.",    engines: ["PlaneOfExistenceEngine","LiminalPlaneEngine","MultiverseEngine"],           estimatedMinutes: 3 },
  { id: "divinwar", name: "DIVINE-WAR-Series",symbol: "DW", icon: "⚔️", gradient: "linear-gradient(135deg,#d97706,#dc2626,#15803d)", description: "Divine Conflict — Deity Hierarchy, Cosmic Conflict, and Ascension — the wars and politics of gods.",    engines: ["DeityHierarchyEngine","CosmicConflictEngine","AscensionEngine"],            estimatedMinutes: 3 },
  { id: "void",     name: "VOID-Series",      symbol: "VO", icon: "🌑", gradient: "linear-gradient(135deg,#374151,#1d4ed8,#ca8a04)", description: "The Nothing — Void, Death Mechanics, and Soul System — what lies beyond existence and what it wants.", engines: ["VoidEngine","DeathMechanicsEngine","SoulSystemEngine"],                     estimatedMinutes: 3 },
  { id: "endofall", name: "END-OF-ALL-Series",symbol: "EA", icon: "💥", gradient: "linear-gradient(135deg,#78350f,#6366f1,#374151)", description: "Apocalypse — Universe Collapse and Void — the complete cosmological end and what precedes it.",        engines: ["UniverseCollapseEngine","VoidEngine"],                                      estimatedMinutes: 2 },
];

export async function runCosmologyForgeEngine(opts: { engineId: string; engineName: string; topic: string; onChunk: (t: string) => void; onDone?: () => void; onError?: (e: string) => void; }): Promise<void> {
  const { engineId, topic, onChunk, onDone, onError } = opts;
  await streamEngine({ engineId, topic, onChunk, onDone: onDone ? () => onDone() : undefined, onError });
}
