// ─── Export Engine — Safe Local Export Stubs ─────────────────────────────────
// All exports produce local files only. No network, no real publishing.
// JSON: structured data; Markdown: human-readable; Text: raw plain text.
// "MOCK" suffix on all filenames makes the demo-only nature clear.

import { Creation, CreationSection } from "@/standalone/creation/CreationStore";

// ─── Shared header for all exports ───────────────────────────────────────────
function buildHeader(creation: Creation): string {
  return [
    `Title: ${creation.name}`,
    `Type: ${creation.type}`,
    `Domain: ${creation.domain}`,
    `Genre: ${creation.genre} | Style: ${creation.style} | Tone: ${creation.tone}`,
    `Created: ${new Date(creation.createdAt).toLocaleString()}`,
    `Sections: ${creation.sections.length}`,
    `Status: ${creation.status ?? "draft"}`,
    creation.tags?.length ? `Tags: ${creation.tags.join(", ")}` : "",
    ``,
    `DISCLAIMER: All content is mock/simulated. Generated by CreateAI Brain for demonstration only.`,
    `Not for real production use without qualified expert review.`,
    `─`.repeat(60),
  ].filter(l => l !== undefined).join("\n");
}

// ─── Export as JSON ───────────────────────────────────────────────────────────
export function exportAsJSON(creation: Creation): void {
  const payload = {
    meta: {
      exportedAt: new Date().toISOString(),
      exportedBy: "CreateAI Brain",
      disclaimer: "All content is mock/simulated. Not for real use without expert review.",
      version: "1.0",
    },
    creation: {
      id: creation.id,
      name: creation.name,
      type: creation.type,
      domain: creation.domain,
      genre: creation.genre,
      style: creation.style,
      tone: creation.tone,
      createdAt: creation.createdAt,
      status: creation.status ?? "draft",
      tags: creation.tags ?? [],
      collectionId: creation.collectionId ?? null,
      themeColor: creation.themeColor ?? null,
      modules: creation.modules,
      patterns: creation.patterns,
      description: creation.description,
      sectionsCount: creation.sections.length,
      sections: creation.sections.map(s => ({ title: s.title, content: s.content })),
    },
  };
  const blob = new Blob([JSON.stringify(payload, null, 2)], { type: "application/json" });
  triggerDownload(blob, `${safeName(creation.name)}_MOCK.json`);
}

// ─── Export as Markdown ───────────────────────────────────────────────────────
export function exportAsMarkdown(creation: Creation): void {
  const lines: string[] = [
    `# ${creation.name}`,
    ``,
    `> **Type:** ${creation.type} | **Domain:** ${creation.domain} | **Status:** ${creation.status ?? "draft"}`,
    `> **Created:** ${new Date(creation.createdAt).toLocaleString()}`,
    `> **Tags:** ${(creation.tags ?? []).join(", ") || "none"}`,
    ``,
    `> ⚠️ **DISCLAIMER:** All content is mock/simulated. Generated by CreateAI Brain for demonstration only. Not for real production use without expert review.`,
    ``,
    `---`,
    ``,
  ];

  for (const section of creation.sections) {
    lines.push(`## ${section.title}`, ``, section.content, ``, `---`, ``);
  }

  const blob = new Blob([lines.join("\n")], { type: "text/markdown" });
  triggerDownload(blob, `${safeName(creation.name)}_MOCK.md`);
}

// ─── Export as Plain Text ─────────────────────────────────────────────────────
export function exportAsText(creation: Creation, sectionTitle?: string): void {
  let content: string;
  let filename: string;

  if (sectionTitle) {
    const sec = creation.sections.find(s => s.title === sectionTitle);
    content = buildHeader(creation) + `\n\n== ${sectionTitle} ==\n\n${sec?.content ?? "(Section not found)"}`;
    filename = `${safeName(creation.name)}_${safeName(sectionTitle)}_MOCK.txt`;
  } else {
    const allSections = creation.sections.map(s => `== ${s.title} ==\n\n${s.content}`).join("\n\n" + "─".repeat(40) + "\n\n");
    content = buildHeader(creation) + "\n\n" + allSections;
    filename = `${safeName(creation.name)}_MOCK.txt`;
  }

  const blob = new Blob([content], { type: "text/plain" });
  triggerDownload(blob, filename);
}

// ─── Copy to Clipboard ────────────────────────────────────────────────────────
export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    try {
      const ta = document.createElement("textarea");
      ta.value = text; ta.style.position = "fixed"; ta.style.top = "-9999px";
      document.body.appendChild(ta); ta.select();
      document.execCommand("copy");
      document.body.removeChild(ta);
      return true;
    } catch {
      return false;
    }
  }
}

// ─── Build Markdown Summary ───────────────────────────────────────────────────
export function buildMarkdownSummary(creation: Creation): string {
  return [
    `# ${creation.name}`,
    ``,
    `**Type:** ${creation.type} | **Domain:** ${creation.domain}`,
    `**Created:** ${new Date(creation.createdAt).toLocaleString()}`,
    ``,
    `## Sections (${creation.sections.length})`,
    ...creation.sections.map(s => `- **${s.title}** — ${s.content.split("\n")[0].slice(0, 80)}…`),
    ``,
    `> Mock content only — CreateAI Brain`,
  ].join("\n");
}

// ─── Helpers ──────────────────────────────────────────────────────────────────
function safeName(name: string): string {
  return name.replace(/[^a-z0-9]/gi, "_").toLowerCase().replace(/__+/g, "_").slice(0, 50);
}

function triggerDownload(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url; a.download = filename;
  document.body.appendChild(a); a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

// ─── Export Format Options ────────────────────────────────────────────────────
export interface ExportOption {
  id: string;
  label: string;
  icon: string;
  desc: string;
  format: "json" | "markdown" | "text" | "clipboard";
}

export const EXPORT_OPTIONS: ExportOption[] = [
  { id: "json",      label: "Export as JSON",     icon: "📦", desc: "Structured data with all sections and metadata", format: "json" },
  { id: "markdown",  label: "Export as Markdown",  icon: "📝", desc: "Human-readable .md file with all sections",       format: "markdown" },
  { id: "text",      label: "Export as Text",      icon: "📄", desc: "Plain text file — all sections concatenated",     format: "text" },
  { id: "clipboard", label: "Copy Summary",        icon: "📋", desc: "Copy a Markdown summary to your clipboard",       format: "clipboard" },
];
