export interface GameWorldEngineDefinition { id: string; name: string; icon: string; color: string; tagline: string; description: string; placeholder: string; example: string; series?: string; }
export interface GameWorldSeriesDefinition { id: string; name: string; symbol: string; icon: string; gradient: string; description: string; engines: string[]; estimatedMinutes: number; }

export const GAMEWORLD_ENGINES: GameWorldEngineDefinition[] = [
  { id: "BoardGameEngine",         name: "Board Game Engine",         icon: "♟️", color: "#6366f1", tagline: "Game Architect",            description: "Designs fictional board games — their rules, pieces, how they spread across a culture, and what they teach players about society.", placeholder: "What board game should I design for this world?",     example: "e.g. A board game that simulates the politics of your civilization so accurately that the ruling class has banned it 3 times",     series: "sport"      },
  { id: "SportDesignEngine",       name: "Sport Design Engine",       icon: "⚽", color: "#dc2626", tagline: "Sport Architect",           description: "Designs fictional sports — their rules, equipment, the culture around them, and what they reveal about a civilization's values.",  placeholder: "What sport should I design for this world?",         example: "e.g. A sport played only in rain — the game's difficulty scales with weather, so championships are held in monsoon season",         series: "sport"      },
  { id: "GamblingSystemEngine",    name: "Gambling System Engine",    icon: "🎲", color: "#d97706", tagline: "Chance Architect",          description: "Designs the gambling traditions of a fictional world — games, odds, the culture of risk, and who profits from others' luck.",      placeholder: "What gambling culture exists in this world?",         example: "e.g. A gambling culture where you can bet your name — the winner takes your legal identity for a period of time",                  series: "underground"},
  { id: "ChildrensGameEngine",     name: "Children's Game Engine",    icon: "🧸", color: "#15803d", tagline: "Play Architect",            description: "Designs the games children play — their rules, what they teach, and what a culture's children games reveal about adult values.",  placeholder: "What games do children play in this culture?",        example: "e.g. A children's game that teaches social hierarchy so effectively that adults have forgotten it's a game",                       series: "sport"      },
  { id: "DeadlyGameEngine",        name: "Deadly Game Engine",        icon: "☠️", color: "#374151", tagline: "Mortal Game Architect",     description: "Designs games where losing has deadly consequences — their justifications, their audience, and their relationship to justice.",    placeholder: "What deadly game exists in this world?",             example: "e.g. A game where criminals can play for their sentence reduction — the game is fair but the house always ends up ahead",           series: "arena"      },
  { id: "GladiatorEngine",         name: "Gladiator Engine",          icon: "⚔️", color: "#be185d", tagline: "Arena Combat Architect",    description: "Designs gladiatorial traditions — who fights, why, what the crowds want, and how the institution justifies itself morally.",       placeholder: "What gladiatorial culture exists in this world?",     example: "e.g. A gladiatorial tradition where combatants fight with deliberately mismatched weapons — the asymmetry is considered artful",    series: "arena"      },
  { id: "TradingCardEquivEngine",  name: "Trading Card Equiv Engine", icon: "🃏", color: "#ca8a04", tagline: "Collectible Architect",     description: "Designs trading card equivalents in a fictional world — what's collected, traded, hoarded, and what rare items are worth lives.", placeholder: "What are the trading collectibles of this world?",    example: "e.g. A culture that collects pressed flowers from famous battles — the rarer the battle, the more valuable the flower",            series: "underground"},
  { id: "GameRulesEngine",         name: "Game Rules Engine",         icon: "📋", color: "#0891b2", tagline: "Rules Architect",           description: "Designs the actual ruleset of a specific fictional game — turn structure, win conditions, and the loopholes everyone exploits.", placeholder: "What are the rules of this fictional game?",          example: "e.g. Design the complete ruleset of a game that's been played for 400 years and has 12 competing regional rule interpretations",  series: "sport"      },
  { id: "StadiumCultureEngine",    name: "Stadium Culture Engine",    icon: "🏟️", color: "#78350f", tagline: "Crowd Culture Architect",   description: "Designs the culture around spectator sports — the rituals, the songs, the fandom violence, the stadium foods and traditions.",    placeholder: "What is the culture around spectating sports here?",  example: "e.g. A culture where the stadium crowd is considered a 13th player — their collective noise can legally affect the game outcome",  series: "championship"},
  { id: "ChampionshipEngine",      name: "Championship Engine",       icon: "🏆", color: "#0f766e", tagline: "Tournament Architect",      description: "Designs tournament and championship systems — how seasons work, what glory means, and how championships become political events.", placeholder: "What championship system should I design?",          example: "e.g. A championship where the loser is required to compose a public song praising the winner — some losers are better singers",    series: "championship"},
  { id: "FixingEngine",            name: "Fixing Engine",             icon: "🎭", color: "#6b7280", tagline: "Corruption Architect",      description: "Designs match-fixing culture — who fixes games, who knows, who pretends not to know, and what happens when it becomes public.",  placeholder: "What game-fixing culture exists in this world?",      example: "e.g. A world where match-fixing is so common that honest games are considered surprising — integrity is the conspiracy theory",    series: "underground"},
  { id: "GameBanEngine",           name: "Game Ban Engine",           icon: "🚫", color: "#4b5563", tagline: "Forbidden Play Architect",  description: "Designs games that have been banned — why they were banned, what they taught, and whether people still play them in secret.",    placeholder: "What games are banned in this culture and why?",      example: "e.g. A children's game banned for teaching cooperation too effectively — the ruling class found cooperative children alarming",     series: "underground"},
  { id: "WagerCultureEngine",      name: "Wager Culture Engine",      icon: "🤝", color: "#1d4ed8", tagline: "Bet Culture Architect",     description: "Designs the broader culture of wagering — what people bet beyond money, what sacred bets exist, and what can never be wagered.", placeholder: "What is the wager culture of this civilization?",     example: "e.g. A culture where the highest stake is a secret — wagering personal secrets creates a web of mutual blackmail as social glue",  series: "championship"},
];

export const GAMEWORLD_SERIES: GameWorldSeriesDefinition[] = [
  { id: "sport",        name: "SPORT-Series",        symbol: "SP", icon: "⚽", gradient: "linear-gradient(135deg,#6366f1,#dc2626,#15803d)", description: "Sport Culture — Sport Design, Board Games, Children's Games, and Rules — the games a civilization plays.", engines: ["SportDesignEngine","BoardGameEngine","ChildrensGameEngine","GameRulesEngine"],  estimatedMinutes: 4 },
  { id: "arena",        name: "ARENA-Series",        symbol: "AR", icon: "⚔️", gradient: "linear-gradient(135deg,#be185d,#374151,#78350f)", description: "Combat Sport — Gladiator and Deadly Games — when games are life-and-death and the crowd loves it.",         engines: ["GladiatorEngine","DeadlyGameEngine"],                                          estimatedMinutes: 2 },
  { id: "underground",  name: "UNDERGROUND-Series",  symbol: "UG", icon: "🎲", gradient: "linear-gradient(135deg,#d97706,#6b7280,#4b5563)", description: "Shadow Games — Gambling, Trading Cards, Game Bans, and Fixing — what happens to games in the dark.",       engines: ["GamblingSystemEngine","TradingCardEquivEngine","FixingEngine","GameBanEngine"],  estimatedMinutes: 4 },
  { id: "championship", name: "CHAMPIONSHIP-Series", symbol: "CH", icon: "🏆", gradient: "linear-gradient(135deg,#0f766e,#0891b2,#1d4ed8)", description: "Competition — Championship, Stadium Culture, and Wager Culture — how competition becomes spectacle.",       engines: ["ChampionshipEngine","StadiumCultureEngine","WagerCultureEngine"],               estimatedMinutes: 3 },
  { id: "ban",          name: "BAN-Series",          symbol: "BN", icon: "🚫", gradient: "linear-gradient(135deg,#4b5563,#374151,#6b7280)", description: "Forbidden Games — Game Ban, Deadly Games, and Fixing — games that power prohibits or corrupts.",            engines: ["GameBanEngine","DeadlyGameEngine","FixingEngine"],                               estimatedMinutes: 3 },
];

export async function runGameWorldEngine(opts: { engineId: string; engineName: string; topic: string; onChunk: (t: string) => void; onDone?: () => void; onError?: (e: string) => void; }): Promise<void> {
  const { engineId, engineName, topic, onChunk, onDone, onError } = opts;
  try {
    const resp = await fetch("/api/openai/engine-run", { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ engineId, engineName, topic }) });
    if (!resp.ok || !resp.body) { onError?.(`Engine returned ${resp.status}`); return; }
    const reader = resp.body.getReader(); const decoder = new TextDecoder();
    while (true) {
      const { done, value } = await reader.read(); if (done) break;
      for (const line of decoder.decode(value).split("\n")) {
        if (!line.startsWith("data:")) continue;
        try { const p = JSON.parse(line.slice(5).trim()) as { content?: string; done?: boolean }; if (p.content) onChunk(p.content); if (p.done) onDone?.(); } catch { /* skip */ }
      }
    }
  } catch (err) { onError?.(String(err)); }
}
