// ─── Demo-Only Mock Integration Engine ───────────────────────────────────────
// ALL packets are FICTIONAL, SIMULATED, and DEMO-ONLY.
// No real connections. No real data. No real-world actions.
// All statuses are mock. "Submit" is non-functional by design.

const STORE_KEY = "createai_integration_packets_v1";

export type PacketStatus = "ready" | "pending" | "submitted" | "connected-demo";

export interface DemoPacket {
  id: string;
  name: string;
  vendor: string;
  category: string;
  icon: string;
  color: string;
  description: string;
  features: string[];
  dataFlows: string[];
  scope: string[];
  endpoint: string;
  status: PacketStatus;
  submittedAt?: string;
  connectedAt?: string;
  safetyNote: string;
  isAutoGenerated?: boolean;
}

// ─── Master Demo Packet Library ───────────────────────────────────────────────
export const DEMO_PACKET_LIBRARY: Omit<DemoPacket, "status" | "submittedAt" | "connectedAt">[] = [

  // ── Healthcare ────────────────────────────────────────────────────────────
  { id: "ehr-epic",         name: "Epic EHR",             vendor: "Epic Systems",       category: "Healthcare",    icon: "🏥", color: "#34C759",
    description: "Connect patient records, clinical workflows, and scheduling from Epic's EHR system.",
    features: ["Patient record sync", "Appointment scheduling", "Clinical notes", "Order management"],
    dataFlows: ["Patient → Platform", "Orders → EHR", "Notes → Archive"],
    scope: ["patient.read", "appointment.write", "clinical.read"],
    endpoint: "https://demo.epic-ehr.example.com/api/FHIR/R4",
    safetyNote: "DEMO ONLY. No real patient data. No HIPAA-covered data. All records are fictional." },

  { id: "ehr-cerner",       name: "Cerner / Oracle Health", vendor: "Oracle Health",    category: "Healthcare",    icon: "🩺", color: "#30B0C7",
    description: "Integrate clinical data, care plans, and lab results from Cerner's cloud health platform.",
    features: ["Care plan sync", "Lab results", "Medication management", "Provider directory"],
    dataFlows: ["Labs → Dashboard", "Care Plans → AI Engine", "Providers → Directory"],
    scope: ["patient.read", "labs.read", "medications.read"],
    endpoint: "https://demo.cerner-health.example.com/fhir/r4",
    safetyNote: "DEMO ONLY. Fictional data. No real clinical decisions supported." },

  { id: "telehealth",       name: "Telehealth Platform",  vendor: "Teladoc (Mock)",     category: "Healthcare",    icon: "📱", color: "#5856D6",
    description: "Enable virtual visits, remote monitoring, and asynchronous care coordination.",
    features: ["Video visits", "Remote monitoring", "Async messaging", "Care coordination"],
    dataFlows: ["Visit notes → EHR", "Vitals → Dashboard", "Alerts → Care Team"],
    scope: ["visit.create", "monitor.read", "message.send"],
    endpoint: "https://demo.telehealth.example.com/api/v2",
    safetyNote: "DEMO ONLY. No real medical consultations. Fictional platform." },

  { id: "pharmacy",         name: "Pharmacy Network",     vendor: "Walgreens (Mock)",   category: "Healthcare",    icon: "💊", color: "#FF9500",
    description: "Connect prescription routing, refill reminders, and medication adherence tracking.",
    features: ["Prescription routing", "Refill reminders", "Adherence tracking", "Drug interactions"],
    dataFlows: ["Prescriptions → Pharmacy", "Refills → Patient", "Interactions → Alert Engine"],
    scope: ["prescription.write", "refill.read", "interaction.check"],
    endpoint: "https://demo.pharmacy-net.example.com/api",
    safetyNote: "DEMO ONLY. No real prescriptions. No real medications. Fictional." },

  // ── Finance ───────────────────────────────────────────────────────────────
  { id: "stripe",           name: "Stripe Payments",      vendor: "Stripe",             category: "Finance",       icon: "💳", color: "#007AFF",
    description: "Enable billing, subscriptions, invoices, and revenue analytics.",
    features: ["Subscription billing", "Invoice generation", "Revenue analytics", "Refund management"],
    dataFlows: ["Charges → Revenue Engine", "Invoices → Docs Engine", "Webhooks → Workflow Engine"],
    scope: ["payment.create", "invoice.write", "customer.read"],
    endpoint: "https://api.stripe.example-demo.com/v1",
    safetyNote: "DEMO ONLY. No real charges. Fictional Stripe environment. No financial transactions." },

  { id: "plaid",            name: "Plaid Banking",        vendor: "Plaid",              category: "Finance",       icon: "🏦", color: "#BF5AF2",
    description: "Connect bank accounts, verify income, and read transaction data for financial workflows.",
    features: ["Account linking", "Income verification", "Transaction sync", "Balance checks"],
    dataFlows: ["Accounts → Dashboard", "Transactions → Analytics", "Income → Profile"],
    scope: ["accounts.read", "transactions.read", "identity.read"],
    endpoint: "https://demo.plaid.example.com/api",
    safetyNote: "DEMO ONLY. No real bank data. Fictional accounts. No financial advice provided." },

  { id: "quickbooks",       name: "QuickBooks Accounting", vendor: "Intuit",            category: "Finance",       icon: "📊", color: "#34C759",
    description: "Sync invoices, expenses, payroll data, and financial reports.",
    features: ["Invoice sync", "Expense tracking", "Payroll data", "P&L reports"],
    dataFlows: ["Invoices → QB", "Expenses → QB", "Reports → Dashboard"],
    scope: ["invoice.read", "expense.write", "report.read"],
    endpoint: "https://demo.quickbooks.example.com/v3",
    safetyNote: "DEMO ONLY. No real accounting records. Fictional financial data." },

  // ── CRM & Sales ───────────────────────────────────────────────────────────
  { id: "hubspot",          name: "HubSpot CRM",          vendor: "HubSpot",            category: "CRM & Sales",   icon: "🎯", color: "#FF9500",
    description: "Sync contacts, deals, pipelines, and marketing automation.",
    features: ["Contact sync", "Deal pipeline", "Email sequences", "Activity tracking"],
    dataFlows: ["Contacts → CRM", "Deals → Pipeline Engine", "Emails → Marketing Engine"],
    scope: ["contacts.write", "deals.read", "emails.send"],
    endpoint: "https://api.hubspot-demo.example.com/crm/v3",
    safetyNote: "DEMO ONLY. No real contact data. No real emails sent. Fictional CRM environment." },

  { id: "salesforce",       name: "Salesforce",           vendor: "Salesforce",         category: "CRM & Sales",   icon: "☁️", color: "#1679C5",
    description: "Connect leads, opportunities, accounts, and Salesforce workflows.",
    features: ["Lead management", "Opportunity tracking", "Account sync", "Flow automation"],
    dataFlows: ["Leads → Salesforce", "Opportunities → Analytics", "Accounts → People Engine"],
    scope: ["lead.create", "opportunity.read", "account.write"],
    endpoint: "https://demo.salesforce.example.com/api/v58",
    safetyNote: "DEMO ONLY. No real Salesforce org connected. Fictional demo environment." },

  { id: "pipedrive",        name: "Pipedrive",            vendor: "Pipedrive",          category: "CRM & Sales",   icon: "📈", color: "#FF2D55",
    description: "Manage sales pipeline stages, activities, and deal tracking.",
    features: ["Pipeline stages", "Activity logging", "Deal tracking", "Forecasting"],
    dataFlows: ["Deals → Pipeline", "Activities → Log Engine", "Forecast → Dashboard"],
    scope: ["deals.write", "activities.read", "pipeline.read"],
    endpoint: "https://demo.pipedrive.example.com/api/v1",
    safetyNote: "DEMO ONLY. No real sales data. Fictional demo pipeline." },

  // ── Marketing & Communication ─────────────────────────────────────────────
  { id: "mailchimp",        name: "Mailchimp Email",      vendor: "Mailchimp (Intuit)", category: "Marketing",     icon: "📧", color: "#FFD700",
    description: "Automate email campaigns, audience segmentation, and send analytics.",
    features: ["Campaign automation", "Audience segments", "A/B testing", "Send analytics"],
    dataFlows: ["Campaigns → Email Engine", "Analytics → Dashboard", "Segments → CRM"],
    scope: ["campaigns.send", "audiences.read", "reports.read"],
    endpoint: "https://demo.mailchimp.example.com/3.0",
    safetyNote: "DEMO ONLY. No real emails sent. Fictional audience and campaign data." },

  { id: "sendgrid",         name: "SendGrid Transactional", vendor: "Twilio SendGrid",  category: "Marketing",     icon: "✉️", color: "#1A82E2",
    description: "Send transactional emails, receipts, and notifications at scale.",
    features: ["Transactional emails", "Template engine", "Delivery analytics", "Unsubscribe handling"],
    dataFlows: ["Triggers → Email Engine", "Templates → Send", "Analytics → Dashboard"],
    scope: ["mail.send", "templates.read", "stats.read"],
    endpoint: "https://demo.sendgrid.example.com/v3",
    safetyNote: "DEMO ONLY. No real emails sent. Fictional delivery data." },

  { id: "twilio",           name: "Twilio SMS",           vendor: "Twilio",             category: "Messaging",     icon: "💬", color: "#F22F46",
    description: "Send SMS notifications, reminders, and two-way messaging.",
    features: ["SMS notifications", "Two-way messaging", "OTP delivery", "Opt-out management"],
    dataFlows: ["Triggers → SMS Engine", "Replies → Inbox", "Opt-outs → CRM"],
    scope: ["messages.create", "messages.read", "numbers.read"],
    endpoint: "https://demo.twilio.example.com/2010-04-01",
    safetyNote: "DEMO ONLY. No real SMS sent. Fictional phone numbers. No real communication." },

  { id: "slack",            name: "Slack Notifications",  vendor: "Slack (Salesforce)", category: "Messaging",     icon: "💼", color: "#4A154B",
    description: "Post alerts, approvals, and workflow notifications to Slack channels.",
    features: ["Channel alerts", "Approval workflows", "Slash commands", "Scheduled digests"],
    dataFlows: ["Alerts → Slack", "Approvals → Workflow Engine", "Digests → Channel"],
    scope: ["chat.write", "channels.read", "commands.read"],
    endpoint: "https://demo.slack.example.com/api",
    safetyNote: "DEMO ONLY. No real Slack workspace. Fictional channels and messages." },

  // ── Productivity & Storage ────────────────────────────────────────────────
  { id: "google-drive",     name: "Google Drive",         vendor: "Google",             category: "Storage",       icon: "📁", color: "#34A853",
    description: "Store, organize, and share documents, forms, and media files.",
    features: ["File storage", "Folder structure", "Sharing permissions", "Version history"],
    dataFlows: ["Files → Drive", "Docs → Document Engine", "Shared → People Engine"],
    scope: ["drive.file", "drive.read", "drive.share"],
    endpoint: "https://demo.googleapis.example.com/drive/v3",
    safetyNote: "DEMO ONLY. No real Google account connected. Fictional file storage." },

  { id: "notion",           name: "Notion Workspace",     vendor: "Notion Labs",        category: "Productivity",  icon: "📝", color: "#000000",
    description: "Sync pages, databases, and wikis for team knowledge management.",
    features: ["Page sync", "Database integration", "Wiki structure", "Comment threads"],
    dataFlows: ["Pages → Knowledge Base", "Databases → Analytics", "Tasks → Project Engine"],
    scope: ["pages.read", "databases.write", "users.read"],
    endpoint: "https://demo.notion.example.com/v1",
    safetyNote: "DEMO ONLY. No real Notion workspace. Fictional workspace data." },

  { id: "zapier",           name: "Zapier Automation",    vendor: "Zapier",             category: "Automation",    icon: "⚡", color: "#FF4A00",
    description: "Connect 5,000+ apps and automate cross-platform workflows.",
    features: ["Multi-step Zaps", "Trigger/action flows", "Filter logic", "Delay steps"],
    dataFlows: ["Triggers → Zap Engine", "Actions → Target Apps", "Filters → Workflow Engine"],
    scope: ["zaps.create", "zaps.run", "zaps.read"],
    endpoint: "https://demo.zapier.example.com/api/v1",
    safetyNote: "DEMO ONLY. No real Zapier account. Fictional automation flows." },

  { id: "jira",             name: "Jira Project Tracking", vendor: "Atlassian",         category: "Operations",    icon: "🔧", color: "#0052CC",
    description: "Sync project tickets, sprints, and engineering workflows.",
    features: ["Ticket sync", "Sprint management", "Backlog prioritization", "Release tracking"],
    dataFlows: ["Tickets → Project Engine", "Sprints → Dashboard", "Releases → Roadmap Engine"],
    scope: ["issues.write", "sprints.read", "projects.read"],
    endpoint: "https://demo.jira.example.com/rest/api/3",
    safetyNote: "DEMO ONLY. No real Jira project. Fictional sprint and ticket data." },

  // ── AI ────────────────────────────────────────────────────────────────────
  { id: "openai",           name: "OpenAI GPT API",       vendor: "OpenAI",             category: "AI",            icon: "🤖", color: "#10A37F",
    description: "Power generation, summarization, classification, and chat with GPT models.",
    features: ["Text generation", "Summarization", "Classification", "Chat completions"],
    dataFlows: ["Prompts → GPT", "Responses → Content Engine", "Tokens → Usage Tracker"],
    scope: ["completions.create", "chat.completions", "models.list"],
    endpoint: "https://demo.openai.example.com/v1",
    safetyNote: "DEMO ONLY. Uses CreateAI Brain's internal AI proxy. No direct OpenAI billing." },

  { id: "anthropic",        name: "Anthropic Claude",     vendor: "Anthropic",          category: "AI",            icon: "🧠", color: "#D97757",
    description: "Deploy safe, helpful AI reasoning for document analysis and long-context tasks.",
    features: ["Long-context analysis", "Document reasoning", "Safe AI responses", "Structured output"],
    dataFlows: ["Documents → Claude", "Analysis → Report Engine", "Responses → Output Engine"],
    scope: ["messages.create", "models.read"],
    endpoint: "https://demo.anthropic.example.com/v1",
    safetyNote: "DEMO ONLY. Fictional Anthropic connection. No real API calls from this packet." },

  { id: "analytics",        name: "Analytics Engine",     vendor: "Google Analytics",   category: "Analytics",     icon: "📊", color: "#F9AB00",
    description: "Track user behavior, conversion events, and performance metrics.",
    features: ["Event tracking", "Conversion funnels", "Audience segments", "Real-time dashboard"],
    dataFlows: ["Events → Analytics", "Funnels → Dashboard", "Segments → Marketing Engine"],
    scope: ["analytics.read", "events.write", "reports.read"],
    endpoint: "https://demo.analytics.example.com/v4",
    safetyNote: "DEMO ONLY. No real user data tracked. Fictional analytics environment." },

  { id: "zoom",             name: "Zoom Meetings",        vendor: "Zoom Communications", category: "Communication", icon: "📹", color: "#2D8CFF",
    description: "Schedule, launch, and record video meetings and webinars.",
    features: ["Meeting scheduling", "Webinar hosting", "Recording storage", "Attendance tracking"],
    dataFlows: ["Meetings → Calendar", "Recordings → Storage Engine", "Attendance → CRM"],
    scope: ["meetings.create", "webinars.read", "recordings.read"],
    endpoint: "https://demo.zoom.example.com/v2",
    safetyNote: "DEMO ONLY. No real Zoom account. Fictional meetings and recordings." },

  { id: "document-ai",      name: "Document AI",          vendor: "Google Cloud",       category: "AI",            icon: "🔍", color: "#4285F4",
    description: "Extract structured data from documents, forms, and PDFs using machine learning.",
    features: ["OCR extraction", "Form parsing", "Table detection", "Entity recognition"],
    dataFlows: ["Documents → AI Engine", "Extracted Data → Platform", "Structured Data → Analytics"],
    scope: ["documents.process", "documents.read", "models.read"],
    endpoint: "https://demo.documentai.example.com/v1",
    safetyNote: "DEMO ONLY. No real document processing. Fictional extraction results." },
];

// ─── Activation Phrases ───────────────────────────────────────────────────────
export const ACTIVATION_PHRASES = [
  "prepare everything", "load all connections", "set up the demo",
  "activate all", "connect everything", "submit all", "ready to demo",
  "go live", "launch demo", "activate integrations", "load integrations",
  "prepare the demo", "initialize all", "start demo mode",
];

export function detectActivationPhrase(text: string): boolean {
  const lower = text.toLowerCase().trim();
  return ACTIVATION_PHRASES.some(phrase => lower.includes(phrase));
}

// ─── Packet Store (localStorage) ─────────────────────────────────────────────
function loadPackets(): DemoPacket[] {
  try { return JSON.parse(localStorage.getItem(STORE_KEY) ?? "[]"); } catch { return []; }
}

function savePackets(packets: DemoPacket[]): void {
  try { localStorage.setItem(STORE_KEY, JSON.stringify(packets)); } catch {}
}

export const IntegrationEngine = {
  // Get all packets (from library + any user-added)
  getAllPackets(): DemoPacket[] {
    const stored = loadPackets();
    const storedIds = new Set(stored.map(p => p.id));
    // Merge: stored takes priority (has status), fill in uninitialized library packets as "ready"
    const fresh: DemoPacket[] = DEMO_PACKET_LIBRARY
      .filter(p => !storedIds.has(p.id))
      .map(p => ({ ...p, status: "ready" as PacketStatus }));
    return [...stored, ...fresh];
  },

  // Save a packet's updated state
  updatePacket(id: string, updates: Partial<DemoPacket>): void {
    const all = this.getAllPackets();
    const idx = all.findIndex(p => p.id === id);
    if (idx >= 0) {
      all[idx] = { ...all[idx], ...updates };
    } else {
      const base = DEMO_PACKET_LIBRARY.find(p => p.id === id);
      if (base) all.push({ ...base, status: "ready", ...updates });
    }
    savePackets(all.filter(p => !DEMO_PACKET_LIBRARY.find(x => x.id === p.id && JSON.stringify({ ...x, status: "ready" }) === JSON.stringify(p)) ));
    // Only store packets that differ from default
    const changed = all.filter(p => p.status !== "ready" || p.submittedAt || p.connectedAt);
    savePackets(changed);
  },

  // Simulate submitting a single packet
  submitPacket(id: string): void {
    this.updatePacket(id, { status: "submitted", submittedAt: new Date().toISOString() });
  },

  // Simulate connecting a single packet (after submitted)
  connectPacket(id: string): void {
    this.updatePacket(id, { status: "connected-demo", connectedAt: new Date().toISOString() });
  },

  // Reset a packet to "ready"
  resetPacket(id: string): void {
    this.updatePacket(id, { status: "ready", submittedAt: undefined, connectedAt: undefined });
  },

  // "Prepare Everything" — stage all packets as pending
  prepareAll(): void {
    const changed = this.getAllPackets().map(p =>
      p.status === "ready" ? { ...p, status: "pending" as PacketStatus } : p
    );
    const toStore = changed.filter(p => p.status !== "ready" || p.submittedAt || p.connectedAt);
    savePackets(toStore);
  },

  // "Submit All" — submit all pending/ready packets
  submitAll(): void {
    const ts = new Date().toISOString();
    const changed = this.getAllPackets().map(p =>
      (p.status === "ready" || p.status === "pending") ? { ...p, status: "submitted" as PacketStatus, submittedAt: ts } : p
    );
    const toStore = changed.filter(p => p.status !== "ready" || p.submittedAt || p.connectedAt);
    savePackets(toStore);
  },

  // "Connect All" — mark all submitted packets as connected-demo
  connectAll(): void {
    const ts = new Date().toISOString();
    const changed = this.getAllPackets().map(p =>
      p.status === "submitted" ? { ...p, status: "connected-demo" as PacketStatus, connectedAt: ts } : p
    );
    const toStore = changed.filter(p => p.status !== "ready" || p.submittedAt || p.connectedAt);
    savePackets(toStore);
  },

  // Reset everything
  resetAll(): void {
    savePackets([]);
  },

  // Auto-build a packet from a keyword
  autoGenerate(name: string): DemoPacket {
    const id = name.toLowerCase().replace(/[^a-z0-9]/g, "-");
    return {
      id: `auto-${id}`, name, vendor: "Custom (Auto-Generated)", category: "Custom",
      icon: "✨", color: "#BF5AF2",
      description: `Auto-generated demo integration packet for ${name}. All data is fictional and for demonstration only.`,
      features: [`${name} data sync`, `${name} notifications`, `${name} reporting`, `${name} automation`],
      dataFlows: [`${name} → Platform`, `Platform → ${name}`, "Bidirectional sync (mock)"],
      scope: ["read", "write", "notify"],
      endpoint: `https://demo.${id}.example.com/api/v1`,
      status: "ready",
      isAutoGenerated: true,
      safetyNote: `DEMO ONLY. Auto-generated packet. No real ${name} integration. All data fictional.`,
    };
  },

  getStats(packets: DemoPacket[]) {
    return {
      total:         packets.length,
      ready:         packets.filter(p => p.status === "ready").length,
      pending:       packets.filter(p => p.status === "pending").length,
      submitted:     packets.filter(p => p.status === "submitted").length,
      connectedDemo: packets.filter(p => p.status === "connected-demo").length,
    };
  },
};
