// ─── Universal Integration Engine ────────────────────────────────────────────
// INTERNAL INTEGRATION CAPACITY — UNIVERSAL, SAFE, SELF-CONTAINED
//
// This engine operates under 3 strict tiers:
//   1. READY — AWAITING API KEYS   (internal packet prepared, no real keys yet)
//   2. SIMULATION MODE — TEST PACKETS ONLY   (simulation running; packets in memory only, never stored as real)
//   3. REAL — ACTIVE   (real API keys provided by user; real backend connection established)
//
// Rules:
//   - Internal capacity may be prepared and stored (tier 1).
//   - Simulation test packets exist ONLY in memory during a simulation run.
//   - Real connections require real API keys provided by the user.
//   - Never generate, guess, or fabricate real API keys.
//   - Never contact external systems.
//   - Never mix simulation packets with real platform data.

const STORE_KEY = "createai_integration_packets_v2";

export type PacketStatus = "ready-awaiting" | "simulation" | "real-active";

// Spec-canonical display labels
export const SPEC_LABELS: Record<PacketStatus, string> = {
  "ready-awaiting": "READY — AWAITING API KEYS",
  "simulation":     "SIMULATION MODE — TEST PACKETS ONLY",
  "real-active":    "REAL — ACTIVE",
};

export interface DemoPacket {
  id: string;
  name: string;
  vendor: string;
  category: string;
  icon: string;
  color: string;
  description: string;
  features: string[];
  dataFlows: string[];
  scope: string[];
  endpoint: string;
  status: PacketStatus;
  simulatedAt?: string;
  activatedAt?: string;
  realApiKey?: string;          // Only set when real keys are provided — never guessed
  safetyNote: string;
  isAutoGenerated?: boolean;
}

// ─── 12-Engine Architecture ───────────────────────────────────────────────────
export const TWELVE_ENGINES = [
  { id: 1,  name: "Integration Engine",          icon: "🔌", desc: "Prepares, simulates, and validates all integrations internally. Auto-expands to any system." },
  { id: 2,  name: "Identity & Access Engine",    icon: "🔐", desc: "Manages user identity, roles, permissions, SSO, and OAuth flows." },
  { id: 3,  name: "Data Model Engine",           icon: "🗄️",  desc: "Defines, validates, and evolves all data schemas and field structures." },
  { id: 4,  name: "Workflow Engine",             icon: "⚙️",  desc: "Orchestrates multi-step workflows, triggers, conditions, and automation." },
  { id: 5,  name: "Communication Engine",        icon: "💬", desc: "Handles email, SMS, push notifications, and in-app messaging." },
  { id: 6,  name: "Document & Content Engine",   icon: "📄", desc: "Generates, stores, and manages all documents, reports, and content." },
  { id: 7,  name: "User Experience Engine",      icon: "🎨", desc: "Renders adaptive UI, accessibility, theming, and component systems." },
  { id: 8,  name: "Simulation Engine",           icon: "🧪", desc: "Runs safe synthetic data simulations. Packets exist in memory only — never stored." },
  { id: 9,  name: "Security & Compliance Engine",icon: "🛡️",  desc: "Enforces encryption, audit logs, compliance rules, and security policies." },
  { id: 10, name: "Scalability Engine",          icon: "📈", desc: "Auto-scales architecture, load balancing, and performance optimization." },
  { id: 11, name: "Monetization Engine",         icon: "💳", desc: "Manages pricing, billing, subscriptions, and revenue analytics." },
  { id: 12, name: "AI Reasoning & Guidance Engine", icon: "🧠", desc: "Powers all AI reasoning, recommendations, and intelligent automation across the platform." },
];

// ─── Master Demo Packet Library ───────────────────────────────────────────────
export const DEMO_PACKET_LIBRARY: Omit<DemoPacket, "status" | "submittedAt" | "connectedAt">[] = [

  // ── Healthcare ────────────────────────────────────────────────────────────
  { id: "ehr-epic",         name: "Epic EHR",             vendor: "Epic Systems",       category: "Healthcare",    icon: "🏥", color: "#34C759",
    description: "Connect patient records, clinical workflows, and scheduling from Epic's EHR system.",
    features: ["Patient record sync", "Appointment scheduling", "Clinical notes", "Order management"],
    dataFlows: ["Patient → Platform", "Orders → EHR", "Notes → Archive"],
    scope: ["patient.read", "appointment.write", "clinical.read"],
    endpoint: "https://demo.epic-ehr.example.com/api/FHIR/R4",
    safetyNote: "DEMO ONLY. No real patient data. No HIPAA-covered data. All records are fictional." },

  { id: "ehr-cerner",       name: "Cerner / Oracle Health", vendor: "Oracle Health",    category: "Healthcare",    icon: "🩺", color: "#30B0C7",
    description: "Integrate clinical data, care plans, and lab results from Cerner's cloud health platform.",
    features: ["Care plan sync", "Lab results", "Medication management", "Provider directory"],
    dataFlows: ["Labs → Dashboard", "Care Plans → AI Engine", "Providers → Directory"],
    scope: ["patient.read", "labs.read", "medications.read"],
    endpoint: "https://demo.cerner-health.example.com/fhir/r4",
    safetyNote: "DEMO ONLY. Fictional data. No real clinical decisions supported." },

  { id: "telehealth",       name: "Telehealth Platform",  vendor: "Teladoc (Mock)",     category: "Healthcare",    icon: "📱", color: "#5856D6",
    description: "Enable virtual visits, remote monitoring, and asynchronous care coordination.",
    features: ["Video visits", "Remote monitoring", "Async messaging", "Care coordination"],
    dataFlows: ["Visit notes → EHR", "Vitals → Dashboard", "Alerts → Care Team"],
    scope: ["visit.create", "monitor.read", "message.send"],
    endpoint: "https://demo.telehealth.example.com/api/v2",
    safetyNote: "DEMO ONLY. No real medical consultations. Fictional platform." },

  { id: "pharmacy",         name: "Pharmacy Network",     vendor: "Walgreens (Mock)",   category: "Healthcare",    icon: "💊", color: "#FF9500",
    description: "Connect prescription routing, refill reminders, and medication adherence tracking.",
    features: ["Prescription routing", "Refill reminders", "Adherence tracking", "Drug interactions"],
    dataFlows: ["Prescriptions → Pharmacy", "Refills → Patient", "Interactions → Alert Engine"],
    scope: ["prescription.write", "refill.read", "interaction.check"],
    endpoint: "https://demo.pharmacy-net.example.com/api",
    safetyNote: "DEMO ONLY. No real prescriptions. No real medications. Fictional." },

  // ── Finance ───────────────────────────────────────────────────────────────
  { id: "stripe",           name: "Stripe Payments",      vendor: "Stripe",             category: "Finance",       icon: "💳", color: "#007AFF",
    description: "Enable billing, subscriptions, invoices, and revenue analytics.",
    features: ["Subscription billing", "Invoice generation", "Revenue analytics", "Refund management"],
    dataFlows: ["Charges → Revenue Engine", "Invoices → Docs Engine", "Webhooks → Workflow Engine"],
    scope: ["payment.create", "invoice.write", "customer.read"],
    endpoint: "https://api.stripe.example-demo.com/v1",
    safetyNote: "DEMO ONLY. No real charges. Fictional Stripe environment. No financial transactions." },

  { id: "plaid",            name: "Plaid Banking",        vendor: "Plaid",              category: "Finance",       icon: "🏦", color: "#BF5AF2",
    description: "Connect bank accounts, verify income, and read transaction data for financial workflows.",
    features: ["Account linking", "Income verification", "Transaction sync", "Balance checks"],
    dataFlows: ["Accounts → Dashboard", "Transactions → Analytics", "Income → Profile"],
    scope: ["accounts.read", "transactions.read", "identity.read"],
    endpoint: "https://demo.plaid.example.com/api",
    safetyNote: "DEMO ONLY. No real bank data. Fictional accounts. No financial advice provided." },

  { id: "quickbooks",       name: "QuickBooks Accounting", vendor: "Intuit",            category: "Finance",       icon: "📊", color: "#34C759",
    description: "Sync invoices, expenses, payroll data, and financial reports.",
    features: ["Invoice sync", "Expense tracking", "Payroll data", "P&L reports"],
    dataFlows: ["Invoices → QB", "Expenses → QB", "Reports → Dashboard"],
    scope: ["invoice.read", "expense.write", "report.read"],
    endpoint: "https://demo.quickbooks.example.com/v3",
    safetyNote: "DEMO ONLY. No real accounting records. Fictional financial data." },

  // ── CRM & Sales ───────────────────────────────────────────────────────────
  { id: "hubspot",          name: "HubSpot CRM",          vendor: "HubSpot",            category: "CRM & Sales",   icon: "🎯", color: "#FF9500",
    description: "Sync contacts, deals, pipelines, and marketing automation.",
    features: ["Contact sync", "Deal pipeline", "Email sequences", "Activity tracking"],
    dataFlows: ["Contacts → CRM", "Deals → Pipeline Engine", "Emails → Marketing Engine"],
    scope: ["contacts.write", "deals.read", "emails.send"],
    endpoint: "https://api.hubspot-demo.example.com/crm/v3",
    safetyNote: "DEMO ONLY. No real contact data. No real emails sent. Fictional CRM environment." },

  { id: "salesforce",       name: "Salesforce",           vendor: "Salesforce",         category: "CRM & Sales",   icon: "☁️", color: "#1679C5",
    description: "Connect leads, opportunities, accounts, and Salesforce workflows.",
    features: ["Lead management", "Opportunity tracking", "Account sync", "Flow automation"],
    dataFlows: ["Leads → Salesforce", "Opportunities → Analytics", "Accounts → People Engine"],
    scope: ["lead.create", "opportunity.read", "account.write"],
    endpoint: "https://demo.salesforce.example.com/api/v58",
    safetyNote: "DEMO ONLY. No real Salesforce org connected. Fictional demo environment." },

  { id: "pipedrive",        name: "Pipedrive",            vendor: "Pipedrive",          category: "CRM & Sales",   icon: "📈", color: "#FF2D55",
    description: "Manage sales pipeline stages, activities, and deal tracking.",
    features: ["Pipeline stages", "Activity logging", "Deal tracking", "Forecasting"],
    dataFlows: ["Deals → Pipeline", "Activities → Log Engine", "Forecast → Dashboard"],
    scope: ["deals.write", "activities.read", "pipeline.read"],
    endpoint: "https://demo.pipedrive.example.com/api/v1",
    safetyNote: "DEMO ONLY. No real sales data. Fictional demo pipeline." },

  // ── Marketing & Communication ─────────────────────────────────────────────
  { id: "mailchimp",        name: "Mailchimp Email",      vendor: "Mailchimp (Intuit)", category: "Marketing",     icon: "📧", color: "#FFD700",
    description: "Automate email campaigns, audience segmentation, and send analytics.",
    features: ["Campaign automation", "Audience segments", "A/B testing", "Send analytics"],
    dataFlows: ["Campaigns → Email Engine", "Analytics → Dashboard", "Segments → CRM"],
    scope: ["campaigns.send", "audiences.read", "reports.read"],
    endpoint: "https://demo.mailchimp.example.com/3.0",
    safetyNote: "DEMO ONLY. No real emails sent. Fictional audience and campaign data." },

  { id: "sendgrid",         name: "SendGrid Transactional", vendor: "Twilio SendGrid",  category: "Marketing",     icon: "✉️", color: "#1A82E2",
    description: "Send transactional emails, receipts, and notifications at scale.",
    features: ["Transactional emails", "Template engine", "Delivery analytics", "Unsubscribe handling"],
    dataFlows: ["Triggers → Email Engine", "Templates → Send", "Analytics → Dashboard"],
    scope: ["mail.send", "templates.read", "stats.read"],
    endpoint: "https://demo.sendgrid.example.com/v3",
    safetyNote: "DEMO ONLY. No real emails sent. Fictional delivery data." },

  { id: "twilio",           name: "Twilio SMS",           vendor: "Twilio",             category: "Messaging",     icon: "💬", color: "#F22F46",
    description: "Send SMS notifications, reminders, and two-way messaging.",
    features: ["SMS notifications", "Two-way messaging", "OTP delivery", "Opt-out management"],
    dataFlows: ["Triggers → SMS Engine", "Replies → Inbox", "Opt-outs → CRM"],
    scope: ["messages.create", "messages.read", "numbers.read"],
    endpoint: "https://demo.twilio.example.com/2010-04-01",
    safetyNote: "DEMO ONLY. No real SMS sent. Fictional phone numbers. No real communication." },

  { id: "slack",            name: "Slack Notifications",  vendor: "Slack (Salesforce)", category: "Messaging",     icon: "💼", color: "#4A154B",
    description: "Post alerts, approvals, and workflow notifications to Slack channels.",
    features: ["Channel alerts", "Approval workflows", "Slash commands", "Scheduled digests"],
    dataFlows: ["Alerts → Slack", "Approvals → Workflow Engine", "Digests → Channel"],
    scope: ["chat.write", "channels.read", "commands.read"],
    endpoint: "https://demo.slack.example.com/api",
    safetyNote: "DEMO ONLY. No real Slack workspace. Fictional channels and messages." },

  // ── Productivity & Storage ────────────────────────────────────────────────
  { id: "google-drive",     name: "Google Drive",         vendor: "Google",             category: "Storage",       icon: "📁", color: "#34A853",
    description: "Store, organize, and share documents, forms, and media files.",
    features: ["File storage", "Folder structure", "Sharing permissions", "Version history"],
    dataFlows: ["Files → Drive", "Docs → Document Engine", "Shared → People Engine"],
    scope: ["drive.file", "drive.read", "drive.share"],
    endpoint: "https://demo.googleapis.example.com/drive/v3",
    safetyNote: "DEMO ONLY. No real Google account connected. Fictional file storage." },

  { id: "notion",           name: "Notion Workspace",     vendor: "Notion Labs",        category: "Productivity",  icon: "📝", color: "#000000",
    description: "Sync pages, databases, and wikis for team knowledge management.",
    features: ["Page sync", "Database integration", "Wiki structure", "Comment threads"],
    dataFlows: ["Pages → Knowledge Base", "Databases → Analytics", "Tasks → Project Engine"],
    scope: ["pages.read", "databases.write", "users.read"],
    endpoint: "https://demo.notion.example.com/v1",
    safetyNote: "DEMO ONLY. No real Notion workspace. Fictional workspace data." },

  { id: "zapier",           name: "Zapier Automation",    vendor: "Zapier",             category: "Automation",    icon: "⚡", color: "#FF4A00",
    description: "Connect 5,000+ apps and automate cross-platform workflows.",
    features: ["Multi-step Zaps", "Trigger/action flows", "Filter logic", "Delay steps"],
    dataFlows: ["Triggers → Zap Engine", "Actions → Target Apps", "Filters → Workflow Engine"],
    scope: ["zaps.create", "zaps.run", "zaps.read"],
    endpoint: "https://demo.zapier.example.com/api/v1",
    safetyNote: "DEMO ONLY. No real Zapier account. Fictional automation flows." },

  { id: "jira",             name: "Jira Project Tracking", vendor: "Atlassian",         category: "Operations",    icon: "🔧", color: "#0052CC",
    description: "Sync project tickets, sprints, and engineering workflows.",
    features: ["Ticket sync", "Sprint management", "Backlog prioritization", "Release tracking"],
    dataFlows: ["Tickets → Project Engine", "Sprints → Dashboard", "Releases → Roadmap Engine"],
    scope: ["issues.write", "sprints.read", "projects.read"],
    endpoint: "https://demo.jira.example.com/rest/api/3",
    safetyNote: "DEMO ONLY. No real Jira project. Fictional sprint and ticket data." },

  // ── AI ────────────────────────────────────────────────────────────────────
  { id: "openai",           name: "OpenAI GPT API",       vendor: "OpenAI",             category: "AI",            icon: "🤖", color: "#10A37F",
    description: "Power generation, summarization, classification, and chat with GPT models.",
    features: ["Text generation", "Summarization", "Classification", "Chat completions"],
    dataFlows: ["Prompts → GPT", "Responses → Content Engine", "Tokens → Usage Tracker"],
    scope: ["completions.create", "chat.completions", "models.list"],
    endpoint: "https://demo.openai.example.com/v1",
    safetyNote: "DEMO ONLY. Uses CreateAI Brain's internal AI proxy. No direct OpenAI billing." },

  { id: "anthropic",        name: "Anthropic Claude",     vendor: "Anthropic",          category: "AI",            icon: "🧠", color: "#D97757",
    description: "Deploy safe, helpful AI reasoning for document analysis and long-context tasks.",
    features: ["Long-context analysis", "Document reasoning", "Safe AI responses", "Structured output"],
    dataFlows: ["Documents → Claude", "Analysis → Report Engine", "Responses → Output Engine"],
    scope: ["messages.create", "models.read"],
    endpoint: "https://demo.anthropic.example.com/v1",
    safetyNote: "DEMO ONLY. Fictional Anthropic connection. No real API calls from this packet." },

  { id: "analytics",        name: "Analytics Engine",     vendor: "Google Analytics",   category: "Analytics",     icon: "📊", color: "#F9AB00",
    description: "Track user behavior, conversion events, and performance metrics.",
    features: ["Event tracking", "Conversion funnels", "Audience segments", "Real-time dashboard"],
    dataFlows: ["Events → Analytics", "Funnels → Dashboard", "Segments → Marketing Engine"],
    scope: ["analytics.read", "events.write", "reports.read"],
    endpoint: "https://demo.analytics.example.com/v4",
    safetyNote: "DEMO ONLY. No real user data tracked. Fictional analytics environment." },

  { id: "zoom",             name: "Zoom Meetings",        vendor: "Zoom Communications", category: "Communication", icon: "📹", color: "#2D8CFF",
    description: "Schedule, launch, and record video meetings and webinars.",
    features: ["Meeting scheduling", "Webinar hosting", "Recording storage", "Attendance tracking"],
    dataFlows: ["Meetings → Calendar", "Recordings → Storage Engine", "Attendance → CRM"],
    scope: ["meetings.create", "webinars.read", "recordings.read"],
    endpoint: "https://demo.zoom.example.com/v2",
    safetyNote: "DEMO ONLY. No real Zoom account. Fictional meetings and recordings." },

  { id: "document-ai",      name: "Document AI",          vendor: "Google Cloud",       category: "AI",            icon: "🔍", color: "#4285F4",
    description: "Extract structured data from documents, forms, and PDFs using machine learning.",
    features: ["OCR extraction", "Form parsing", "Table detection", "Entity recognition"],
    dataFlows: ["Documents → AI Engine", "Extracted Data → Platform", "Structured Data → Analytics"],
    scope: ["documents.process", "documents.read", "models.read"],
    endpoint: "https://demo.documentai.example.com/v1",
    safetyNote: "DEMO ONLY. No real document processing. Fictional extraction results." },
];

// ─── Activation Phrases ───────────────────────────────────────────────────────
export const ACTIVATION_PHRASES = [
  "prepare everything", "load all connections", "set up the demo",
  "activate all", "connect everything", "ready to demo",
  "go live", "launch demo", "activate integrations", "load integrations",
  "prepare the demo", "initialize all", "start simulation",
];

export function detectActivationPhrase(text: string): boolean {
  const lower = text.toLowerCase().trim();
  return ACTIVATION_PHRASES.some(phrase => lower.includes(phrase));
}

// ─── Packet Store (localStorage) ─────────────────────────────────────────────
// Only READY — AWAITING API KEYS packets are stored.
// SIMULATION MODE packets are NEVER stored — memory only.
// REAL — ACTIVE packets are stored (with real key reference, never the key value).

function loadPackets(): DemoPacket[] {
  try { return JSON.parse(localStorage.getItem(STORE_KEY) ?? "[]"); } catch { return []; }
}

function savePackets(packets: DemoPacket[]): void {
  // NEVER store simulation packets — they must be memory-only
  const safe = packets
    .filter(p => p.status !== "simulation")
    .map(p => ({ ...p, realApiKey: p.realApiKey ? "[stored-ref]" : undefined }));
  try { localStorage.setItem(STORE_KEY, JSON.stringify(safe)); } catch {}
}

export const IntegrationEngine = {

  // Get all packets (from library + any user-customized)
  getAllPackets(): DemoPacket[] {
    const stored   = loadPackets();
    const storedIds = new Set(stored.map(p => p.id));
    const fresh: DemoPacket[] = DEMO_PACKET_LIBRARY
      .filter(p => !storedIds.has(p.id))
      .map(p => ({ ...p, status: "ready-awaiting" as PacketStatus }));
    return [...stored, ...fresh];
  },

  // Update a packet's state (only persists non-simulation packets)
  updatePacket(id: string, updates: Partial<DemoPacket>): void {
    const all = this.getAllPackets();
    const idx = all.findIndex(p => p.id === id);
    if (idx >= 0) {
      all[idx] = { ...all[idx], ...updates };
    } else {
      const base = DEMO_PACKET_LIBRARY.find(p => p.id === id);
      if (base) all.push({ ...base, status: "ready-awaiting", ...updates });
    }
    const toStore = all.filter(p =>
      p.status !== "ready-awaiting" || p.activatedAt || p.simulatedAt
    );
    savePackets(toStore);
  },

  // Run a simulation on a single packet (memory-only — does NOT persist)
  simulatePacket(id: string): DemoPacket | null {
    const all  = this.getAllPackets();
    const base = all.find(p => p.id === id);
    if (!base) return null;
    // Return an in-memory simulation copy — never stored
    return { ...base, status: "simulation", simulatedAt: new Date().toISOString() };
  },

  // Activate with real API key (persists the activation, key reference only)
  activateWithKey(id: string, _realApiKey: string): void {
    // Store that a real key was provided — never store the key value itself
    this.updatePacket(id, {
      status:      "real-active",
      activatedAt: new Date().toISOString(),
      realApiKey:  "[user-provided]",
    });
  },

  // Reset a packet to READY — AWAITING API KEYS
  resetPacket(id: string): void {
    this.updatePacket(id, {
      status:      "ready-awaiting",
      simulatedAt: undefined,
      activatedAt: undefined,
      realApiKey:  undefined,
    });
  },

  // Run simulation on ALL packets (returns in-memory array — NEVER stored)
  simulateAll(): DemoPacket[] {
    const ts = new Date().toISOString();
    return this.getAllPackets()
      .filter(p => p.status !== "real-active")
      .map(p => ({ ...p, status: "simulation" as PacketStatus, simulatedAt: ts }));
  },

  // Reset all back to READY — AWAITING API KEYS
  resetAll(): void {
    try { localStorage.removeItem(STORE_KEY); } catch {}
  },

  // Auto-build an integration packet from a keyword (returned as READY — AWAITING API KEYS)
  autoGenerate(name: string): DemoPacket {
    const id = name.toLowerCase().replace(/[^a-z0-9]/g, "-");
    return {
      id:   `auto-${id}`,
      name,
      vendor:      `${name} (Auto-Prepared)`,
      category:    "Custom",
      icon:        "✨",
      color:       "#BF5AF2",
      description: `Auto-prepared integration packet for ${name}. Internal capacity ready. Awaiting real API keys from ${name} to go live.`,
      features:    [`${name} data sync`, `${name} notifications`, `${name} reporting`, `${name} automation`],
      dataFlows:   [`${name} → Platform`, `Platform → ${name}`, "Bidirectional sync"],
      scope:       ["read", "write", "notify"],
      endpoint:    `https://demo.${id}.example.com/api/v1`,
      status:      "ready-awaiting",
      isAutoGenerated: true,
      safetyNote:  `READY — AWAITING API KEYS. Auto-prepared for ${name}. Internal mapping is complete. Provide real API keys to activate.`,
    };
  },

  // ── Auto-expand: prepare + simulate any named system in one call ──────────
  // Returns the prepared packet AND a memory-only simulation copy.
  // The simulation copy is NEVER stored — caller is responsible for discarding it.
  prepareAndSimulate(name: string): { packet: DemoPacket; simulation: DemoPacket } {
    // Check if already in library
    const all     = this.getAllPackets();
    const existing = all.find(p =>
      p.name.toLowerCase() === name.toLowerCase() ||
      p.id === `auto-${name.toLowerCase().replace(/[^a-z0-9]/g, "-")}`
    );
    const packet = existing ?? this.autoGenerate(name);

    // Persist the READY — AWAITING API KEYS packet
    if (!existing) this.updatePacket(packet.id, packet);

    // Return in-memory simulation — never stored
    const simulation: DemoPacket = {
      ...packet,
      status:      "simulation",
      simulatedAt: new Date().toISOString(),
    };
    return { packet, simulation };
  },

  // ── Auto-simulate ALL non-real packets in one pass ─────────────────────────
  // Returns memory-only simulation copies. NEVER stored.
  runAutoSimulation(): DemoPacket[] {
    const ts = new Date().toISOString();
    return this.getAllPackets()
      .filter(p => p.status !== "real-active")
      .map(p => ({ ...p, status: "simulation" as PacketStatus, simulatedAt: ts }));
  },

  // ── Auto-generate formal partner integration request document ─────────────
  // This is an INTERNAL document only. It is never sent automatically.
  // The user must review and send it to the partner through their own channels.
  generatePartnerRequest(packet: DemoPacket): string {
    const date = new Date().toLocaleDateString("en-US", {
      year: "numeric", month: "long", day: "numeric",
    });
    return [
      `PARTNER INTEGRATION REQUEST`,
      `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`,
      `Date:        ${date}`,
      `Platform:    CreateAI Brain`,
      `Integration: ${packet.name}`,
      `Vendor:      ${packet.vendor}`,
      `Category:    ${packet.category}`,
      `Status:      READY — AWAITING API KEYS`,
      ``,
      `REQUEST SUMMARY`,
      `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`,
      `We are formally requesting API access to ${packet.name} to enable`,
      `the following integration within our platform, CreateAI Brain.`,
      ``,
      `${packet.description}`,
      ``,
      `REQUESTED API SCOPES`,
      `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`,
      ...packet.scope.map(s => `  • ${s}`),
      ``,
      `DATA FLOWS`,
      `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`,
      ...packet.dataFlows.map(f => `  • ${f}`),
      ``,
      `CAPABILITIES REQUESTED`,
      `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`,
      ...packet.features.map(f => `  • ${f}`),
      ``,
      `TECHNICAL DETAILS`,
      `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`,
      `Auth method:     OAuth 2.0 / API Key (as specified by ${packet.vendor})`,
      `Data protocol:   REST / JSON`,
      `Internal endpoint prepared: ${packet.endpoint}`,
      ``,
      `LEGAL & COMPLIANCE CHECKLIST`,
      `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`,
      `□  We agree to ${packet.vendor}'s API Terms of Service`,
      `□  We will use the API solely for the described use case`,
      `□  We will not store sensitive data beyond operational requirements`,
      `□  We will implement rate limiting, error handling, and retry logic`,
      `□  We will maintain appropriate encryption and security standards`,
      `□  We will notify ${packet.vendor} of any security incidents promptly`,
      ``,
      `ACTIVATION PROCESS`,
      `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`,
      `Once partner approves this request:`,
      `  1. Partner provides real API keys via developer portal`,
      `  2. We enter the keys — integration switches to REAL — ACTIVE immediately`,
      `  3. Integration is added to the Integration Hub for all platform users`,
      `  4. Full end-to-end flow verified with real data`,
      ``,
      `CONTACT`,
      `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`,
      `Platform:    CreateAI Brain`,
      `Auto-prepared by: Integration Engine — Universal Preparation Layer`,
      ``,
      `[ADD YOUR NAME, COMPANY, EMAIL, AND PHONE BEFORE SENDING]`,
    ].join("\n");
  },

  getStats(packets: DemoPacket[]) {
    return {
      total:      packets.length,
      ready:      packets.filter(p => p.status === "ready-awaiting").length,
      simulation: packets.filter(p => p.status === "simulation").length,
      real:       packets.filter(p => p.status === "real-active").length,
    };
  },
};
