import { streamEngine } from "@/controller";
export interface LanguageForgeEngineDefinition { id: string; name: string; icon: string; color: string; tagline: string; description: string; placeholder: string; example: string; series?: string; }
export interface LanguageForgeSeriesDefinition { id: string; name: string; symbol: string; icon: string; gradient: string; description: string; engines: string[]; estimatedMinutes: number; }

export const LANGUAGEFORGE_ENGINES: LanguageForgeEngineDefinition[] = [
  { id: "PhonologyEngine",          name: "Phonology Engine",           icon: "🔊", color: "#6366f1", tagline: "Sound Architect",         description: "Designs the sound system of a fictional language — vowels, consonants, stress patterns, and the feeling of speaking it aloud.",               placeholder: "What phonology should this language have?",             example: "e.g. A language with no plosives — every word flows like water, making it impossible to sound angry even when you are",          series: "tongue"   },
  { id: "GrammarEngine",            name: "Grammar Engine",             icon: "📐", color: "#7c3aed", tagline: "Structure Architect",      description: "Designs the grammatical rules of a fictional language — word order, tense, case, agreement, and how sentences think.",               placeholder: "What grammar system should this language use?",          example: "e.g. A language where tense is marked by proximity to death — the closer you are to dying the more past-focused your grammar", series: "tongue"   },
  { id: "WritingSystemEngine",      name: "Writing System Engine",      icon: "✍️", color: "#be185d", tagline: "Script Architect",         description: "Invents fictional writing systems — alphabets, syllabaries, logographic systems, and how the script itself carries meaning.",           placeholder: "What writing system should this language have?",         example: "e.g. A writing system where letters physically lean in the direction of the story's moral weight",                               series: "script"   },
  { id: "VocabularyEngine",         name: "Vocabulary Engine",          icon: "📖", color: "#0891b2", tagline: "Lexicon Architect",         description: "Creates core vocabulary — the first 200 words, what they reveal about a culture, and what concepts have no direct translation.",      placeholder: "What vocabulary should this language prioritize?",       example: "e.g. A language with 47 words for different kinds of silence and no word for 'hurry'",                                           series: "tongue"   },
  { id: "DialectEngine",            name: "Dialect Engine",             icon: "🗣️", color: "#d97706", tagline: "Dialect Architect",         description: "Designs regional dialects and social dialects — how class, geography, and history fracture a language into variations.",            placeholder: "What dialects should this language have?",               example: "e.g. A dialect spoken only by those who survived a specific disaster — marked by borrowed words from their rescuers' language", series: "dialect"  },
  { id: "SlangEngine",              name: "Slang Engine",               icon: "💬", color: "#15803d", tagline: "Street Language Architect",  description: "Creates slang, idiom, and informal registers — the living edge of a language where new meanings are born and old ones die.",            placeholder: "What slang and idioms should exist in this culture?",    example: "e.g. A slang system based entirely on the names of famous cowards — 'pulling a Keth' means to flee without warning",            series: "dialect"  },
  { id: "ProfanitySystemEngine",    name: "Profanity System Engine",    icon: "🤬", color: "#dc2626", tagline: "Taboo Language Architect",  description: "Designs what a culture considers profane — taboo words, their power, their origin, and what using them says about the speaker.",        placeholder: "What is considered profane in this language/culture?",   example: "e.g. A culture where the only true profanity is speaking the names of the living dead — considered so obscene it's illegal",    series: "dialect"  },
  { id: "PoetryFormEngine",         name: "Poetry Form Engine",         icon: "🎭", color: "#78350f", tagline: "Verse Architect",           description: "Invents fictional poetry forms — the meters, structures, rhyme schemes, and what each form is used for ritually or emotionally.",     placeholder: "What poetry forms exist in this culture?",               example: "e.g. A 9-line form where the 5th line must contradict the 4th, used only for apologies between enemies",                         series: "sacred"   },
  { id: "ProverbEngine",            name: "Proverb Engine",             icon: "💡", color: "#ca8a04", tagline: "Wisdom Language Architect",  description: "Creates proverbs, sayings, and idiomatic wisdom — the compressed philosophy of a culture passed down through language.",              placeholder: "What proverbs shape this culture's thinking?",           example: "e.g. Proverbs from a maritime culture where all wisdom is expressed in terms of water, tide, and the behavior of fish",           series: "tongue"   },
  { id: "NamingSystemEngine",       name: "Naming System Engine",       icon: "🏷️", color: "#4b5563", tagline: "Name Architect",             description: "Designs how people, places, and things are named — naming conventions, what names mean, and how names change over a lifetime.",      placeholder: "How does this culture name its people and places?",      example: "e.g. A culture where children are named after the first stranger who holds them — names are therefore mostly foreign words",      series: "sacred"   },
  { id: "LinguisticEvolutionEngine",name: "Linguistic Evolution Engine",icon: "🧬", color: "#0f766e", tagline: "Language Change Architect",  description: "Maps how a language evolves over centuries — sound shifts, borrowed words, lost meanings, and the archaeology of language change.",    placeholder: "How has this language changed over 500 years?",          example: "e.g. A language that absorbed so many words from conquered cultures that scholars argue about which root is truly original",      series: "dead"     },
  { id: "SacredLanguageEngine",     name: "Sacred Language Engine",     icon: "🕊️", color: "#1d4ed8", tagline: "Holy Tongue Architect",      description: "Designs languages used only in religious or ceremonial contexts — the preserved dead languages of ritual and prayer.",                placeholder: "What is the sacred or ceremonial language?",             example: "e.g. A sacred language no one speaks natively anymore — priests must learn it from crumbling manuscripts and they disagree on pronunciation", series: "sacred" },
  { id: "SignLanguageEngine",       name: "Sign Language Engine",       icon: "🤟", color: "#6b7280", tagline: "Visual Language Architect",  description: "Invents fictional sign languages — handshapes, movement, facial grammar, and the communities who use them and why.",                  placeholder: "What sign language exists in this world?",               example: "e.g. A sign language developed by soldiers to communicate silently behind enemy lines, now used by an entire underground culture",  series: "dialect"  },
];

export const LANGUAGEFORGE_SERIES: LanguageForgeSeriesDefinition[] = [
  { id: "tongue",  name: "TONGUE-Series",  symbol: "TG", icon: "🔊", gradient: "linear-gradient(135deg,#6366f1,#0891b2,#ca8a04)", description: "Core Tongue — Phonology, Grammar, Vocabulary, and Proverbs — the living heart of a spoken language.", engines: ["PhonologyEngine","GrammarEngine","VocabularyEngine","ProverbEngine"], estimatedMinutes: 4 },
  { id: "script",  name: "SCRIPT-Series",  symbol: "SC", icon: "✍️", gradient: "linear-gradient(135deg,#be185d,#7c3aed,#1d4ed8)",  description: "Written Form — Writing System, Naming System, and Poetry Form — the visible face of a language.",      engines: ["WritingSystemEngine","NamingSystemEngine","PoetryFormEngine"],       estimatedMinutes: 3 },
  { id: "dialect", name: "DIALECT-Series", symbol: "DL", icon: "🗣️", gradient: "linear-gradient(135deg,#d97706,#15803d,#dc2626)",  description: "Living Edge — Dialect, Slang, Profanity, and Sign Language — the language as it is actually used.",   engines: ["DialectEngine","SlangEngine","ProfanitySystemEngine"],               estimatedMinutes: 3 },
  { id: "sacred",  name: "SACRED-Series",  symbol: "SA", icon: "🕊️", gradient: "linear-gradient(135deg,#1d4ed8,#4b5563,#78350f)",  description: "Holy Tongue — Sacred Language, Naming System, and Poetry Form — the ceremonial architecture of speech.", engines: ["SacredLanguageEngine","NamingSystemEngine","PoetryFormEngine"],      estimatedMinutes: 3 },
  { id: "dead",    name: "DEAD-TONGUE-Series", symbol: "DT", icon: "🧬", gradient: "linear-gradient(135deg,#0f766e,#6b7280,#6366f1)", description: "Language Evolution — Evolution, Sacred Language, and Dialect — how a language dies and what survives.", engines: ["LinguisticEvolutionEngine","SacredLanguageEngine","DialectEngine"],  estimatedMinutes: 3 },
];

export async function runLanguageForgeEngine(opts: { engineId: string; engineName: string; topic: string; onChunk: (t: string) => void; onDone?: () => void; onError?: (e: string) => void; }): Promise<void> {
  const { engineId, topic, onChunk, onDone, onError } = opts;
  await streamEngine({ engineId, topic, onChunk, onDone: onDone ? () => onDone() : undefined, onError });
}
