import { streamEngine } from "@/controller";
export interface MagicSystemEngineDefinition { id: string; name: string; icon: string; color: string; tagline: string; description: string; placeholder: string; example: string; series?: string; }
export interface MagicSystemSeriesDefinition { id: string; name: string; symbol: string; icon: string; gradient: string; description: string; engines: string[]; estimatedMinutes: number; }

export const MAGICSYSTEM_ENGINES: MagicSystemEngineDefinition[] = [
  { id: "MagicRuleEngine",       name: "Magic Rule Engine",       icon: "📜", color: "#6366f1", tagline: "Law of Magic Architect",     description: "Defines the fundamental rules of magic — what it can do, what it cannot do, and who decided those limits.",             placeholder: "What are the core rules of this magic system?",         example: "e.g. Magic works by borrowing time from your future self — every spell costs years of your life, paid in advance",            series: "hardmagic" },
  { id: "MagicCostEngine",       name: "Magic Cost Engine",       icon: "⚖️", color: "#dc2626", tagline: "Price of Power Architect",   description: "Designs what magic costs the user — physical, emotional, moral, social — and how those costs accumulate over time.",       placeholder: "What does magic cost in this world?",                   example: "e.g. Magic is free but leaves a visible mark — after enough spells you become transparent, then invisible, then gone",         series: "hardmagic" },
  { id: "SpellDesignEngine",     name: "Spell Design Engine",     icon: "✨", color: "#7c3aed", tagline: "Spell Architect",            description: "Creates specific spells — what they do, how they're cast, what they look like, and what they feel like from the inside.", placeholder: "What spells exist in this magic system?",               example: "e.g. A spell that reverses a single decision someone else made — but the caster feels all the consequences of both choices",  series: "hardmagic" },
  { id: "SchoolOfMagicEngine",   name: "School of Magic Engine",  icon: "🏛️", color: "#d97706", tagline: "Tradition Architect",        description: "Designs schools and traditions of magic — each with their philosophy, methods, forbidden practices, and rivalries.",      placeholder: "What schools of magic exist in this world?",            example: "e.g. A school of magic based entirely on grief — only those who have lost something irreplaceable can study here",            series: "school"   },
  { id: "MagicCorruptionEngine", name: "Magic Corruption Engine", icon: "🌑", color: "#374151", tagline: "Corruption Architect",       description: "Designs what happens when magic goes wrong or is overused — the transformations, the madness, the things you become.",      placeholder: "What does magic corruption look like in this world?",   example: "e.g. Using too much magic causes memories to become visible to others — your secrets literally bleed into the air around you", series: "corruption"},
  { id: "ArtifactEngine",        name: "Artifact Engine",         icon: "💎", color: "#ca8a04", tagline: "Object of Power Architect",  description: "Creates magical artifacts — their history, their powers, their personality, and why they always end up in the wrong hands.", placeholder: "What magical artifacts exist in this world?",           example: "e.g. A mirror that shows you your worst day yet to come — wizards fight wars over it because knowing the worst lets you choose differently", series: "artifact" },
  { id: "PractitionerEngine",    name: "Practitioner Engine",     icon: "🧙", color: "#0891b2", tagline: "Mage Architect",             description: "Designs who can use magic — how they're born, trained, organized, and how magical ability shapes a person's social life.", placeholder: "Who uses magic and how do they fit into society?",       example: "e.g. Magic users are chosen by objects that choose them at puberty — the object judges character and can revoke its choice",   series: "school"   },
  { id: "ForbiddenMagicEngine",  name: "Forbidden Magic Engine",  icon: "🚫", color: "#be185d", tagline: "Taboo Magic Architect",      description: "Designs what is forbidden, why it's forbidden, and who enforces those limits — and whether the prohibition is justified.",   placeholder: "What magic is forbidden and why?",                     example: "e.g. Magic that affects memory is forbidden — not because it doesn't work but because it works too well and is being hoarded",  series: "corruption"},
  { id: "MagicCounterEngine",    name: "Magic Counter Engine",    icon: "🛡️", color: "#15803d", tagline: "Anti-Magic Architect",       description: "Designs how magic is countered, blocked, or negated — and who has access to those defenses and who doesn't.",              placeholder: "How is magic countered or defended against?",           example: "e.g. The only thing that blocks a spell is genuine belief that it won't work — but manufactured doubt doesn't count",          series: "hardmagic" },
  { id: "MagicEcologyEngine",    name: "Magic Ecology Engine",    icon: "🌿", color: "#0f766e", tagline: "World Magic Architect",       description: "Designs how magic interacts with the natural world — what creatures are magical, what places amplify or suppress it.",      placeholder: "How does magic interact with nature in this world?",    example: "e.g. Trees near ley lines grow in mathematically perfect spirals — loggers who ignore this go mad within a season",            series: "school"   },
  { id: "MagicPoliticsEngine",   name: "Magic Politics Engine",   icon: "👑", color: "#78350f", tagline: "Power Politics Architect",   description: "Designs how magic shapes political systems — who controls access, how it creates inequality, and who it excludes.",         placeholder: "How does magic affect political power in this world?",  example: "e.g. The ruling family doesn't use magic themselves — they control who has access to the only teacher left alive",             series: "corruption"},
  { id: "MagicEvolutionEngine",  name: "Magic Evolution Engine",  icon: "🧬", color: "#6b7280", tagline: "Magic Change Architect",     description: "Designs how magic changes over time — new forms emerging, old abilities dying out, and why the magic of today differs from legend.", placeholder: "How has magic changed over centuries in this world?", example: "e.g. The grandest spells are simpler than before — something is eating the complexity out of magic and no one knows what",     series: "artifact" },
  { id: "SentientMagicEngine",   name: "Sentient Magic Engine",   icon: "🌀", color: "#4f46e5", tagline: "Living Magic Architect",     description: "Designs magic that has its own will, agenda, and preferences — and what it means to live in a world where magic chooses you.",  placeholder: "Is magic sentient in this world and what does it want?",example: "e.g. Magic in this world remembers every spell it has ever cast and has preferences based on its accumulated experience",        series: "artifact" },
];

export const MAGICSYSTEM_SERIES: MagicSystemSeriesDefinition[] = [
  { id: "hardmagic",  name: "HARDMAGIC-Series",  symbol: "HM", icon: "📜", gradient: "linear-gradient(135deg,#6366f1,#dc2626,#15803d)", description: "System Core — Rules, Cost, Spell Design, and Counter — the mechanical spine of a magic system.", engines: ["MagicRuleEngine","MagicCostEngine","SpellDesignEngine","MagicCounterEngine"], estimatedMinutes: 4 },
  { id: "school",     name: "SCHOOL-Series",     symbol: "SC", icon: "🏛️", gradient: "linear-gradient(135deg,#d97706,#0891b2,#0f766e)", description: "Tradition — Schools, Practitioners, and Ecology — who uses magic and how it lives in the world.",  engines: ["SchoolOfMagicEngine","PractitionerEngine","MagicEcologyEngine"],              estimatedMinutes: 3 },
  { id: "corruption", name: "CORRUPTION-Series", symbol: "CO", icon: "🌑", gradient: "linear-gradient(135deg,#374151,#be185d,#78350f)", description: "Dark Side — Corruption, Forbidden Magic, and Politics — what magic does to those who misuse it.", engines: ["MagicCorruptionEngine","ForbiddenMagicEngine","MagicPoliticsEngine"],          estimatedMinutes: 3 },
  { id: "artifact",   name: "ARTIFACT-Series",   symbol: "AR", icon: "💎", gradient: "linear-gradient(135deg,#ca8a04,#6b7280,#4f46e5)", description: "Objects of Power — Artifacts, Evolution, and Sentient Magic — magic that outlives its makers.",   engines: ["ArtifactEngine","MagicEvolutionEngine","SentientMagicEngine"],                  estimatedMinutes: 3 },
  { id: "softmagic",  name: "SOFTMAGIC-Series",  symbol: "SM", icon: "✨", gradient: "linear-gradient(135deg,#7c3aed,#ca8a04,#0891b2)", description: "Full System — Spell Design, Practitioners, and Ecology — a complete but flexible magic design.", engines: ["SpellDesignEngine","PractitionerEngine","MagicEcologyEngine"],                  estimatedMinutes: 3 },
];

export async function runMagicSystemEngine(opts: { engineId: string; engineName: string; topic: string; onChunk: (t: string) => void; onDone?: () => void; onError?: (e: string) => void; }): Promise<void> {
  const { engineId, topic, onChunk, onDone, onError } = opts;
  await streamEngine({ engineId, topic, onChunk, onDone: onDone ? () => onDone() : undefined, onError });
}
