import { streamEngine } from "@/controller";
export interface MythweaveEngineDefinition {
  id: string; name: string; icon: string; color: string; gradient: string;
  tagline: string; description: string; placeholder: string; example: string; series?: string;
}

export const MYTHWEAVE_ENGINES: MythweaveEngineDefinition[] = [
  { id: "ArchetypeEngine",       name: "Archetype Engine",        icon: "🏛️", color: "#7c3aed", gradient: "linear-gradient(135deg,#7c3aed,#6d28d9)", tagline: "Archetype Architect",     description: "Maps universal archetypes into fictional worlds — the hero, shadow, trickster, sage, and every variation between.",    placeholder: "What archetype should I map for this world?",          example: "e.g. The Trickster archetype in a world where trickery is considered the highest spiritual practice",                      series: "archetype" },
  { id: "SymbolSystemEngine",    name: "Symbol System Engine",    icon: "🔯", color: "#1d4ed8", gradient: "linear-gradient(135deg,#1d4ed8,#1e40af)", tagline: "Symbol Architect",        description: "Designs fictional symbol systems — their meaning, how they change across cultures, and what they reveal about a world.", placeholder: "What symbol system should I design?",                  example: "e.g. A civilization where the triangle means different things to different castes — each believing their version is original", series: "folklore" },
  { id: "MotifEngine",           name: "Motif Engine",            icon: "🌀", color: "#0f766e", gradient: "linear-gradient(135deg,#0f766e,#0d9488)", tagline: "Motif Architect",         description: "Identifies and designs recurring story motifs — the patterns that repeat across myths, folklore, and narrative across cultures.", placeholder: "What story motif should I design?",                  example: "e.g. The motif of the river that must be crossed to enter adulthood — and how five different cultures interpret that river", series: "folklore" },
  { id: "FolkloreEngine",        name: "Folklore Engine",         icon: "📖", color: "#d97706", gradient: "linear-gradient(135deg,#d97706,#b45309)", tagline: "Folklore Architect",      description: "Creates folk tales, urban legends, oral traditions, and the living mythology of everyday people in fictional worlds.",   placeholder: "What folklore should I create?",                       example: "e.g. The folk tales that mothers tell in a kingdom that officially denies magic — and what they protect children from",      series: "folklore" },
  { id: "RitualDesignEngine",    name: "Ritual Design Engine",    icon: "🕯️", color: "#be185d", gradient: "linear-gradient(135deg,#be185d,#db2777)", tagline: "Ritual Architect",        description: "Designs ritual structures — the steps, symbols, participants, and what each ritual seals, breaks, or calls forth.",    placeholder: "What ritual should I design?",                         example: "e.g. A coming-of-age ritual where the initiate must spend 3 days as an elder and 3 days as a child before they can be themselves", series: "archetype" },
  { id: "TricksterEngine",       name: "Trickster Engine",        icon: "🃏", color: "#ca8a04", gradient: "linear-gradient(135deg,#ca8a04,#a16207)", tagline: "Chaos Architect",         description: "Designs trickster figures and chaos agents — the forces that unmake order so that better order can form.",            placeholder: "What trickster figure should I design?",               example: "e.g. A trickster god who only deceives people into the lives they actually wanted but were too afraid to choose",            series: "archetype" },
  { id: "HeroJourneyEngine",     name: "Hero Journey Engine",     icon: "⚔️", color: "#dc2626", gradient: "linear-gradient(135deg,#dc2626,#991b1b)", tagline: "Journey Architect",       description: "Designs Campbell's monomyth adapted for fictional worlds — call, crossing, ordeal, transformation, and return.",     placeholder: "What hero journey should I design?",                   example: "e.g. A hero journey where the return home is the most dangerous and painful stage — not the quest itself",                  series: "journey"  },
  { id: "ShadowNarrativeEngine", name: "Shadow Narrative Engine", icon: "🌑", color: "#374151", gradient: "linear-gradient(135deg,#374151,#1f2937)", tagline: "Shadow Architect",        description: "Designs the story beneath the official story — the suppressed, the denied, and what the dominant narrative erases.",   placeholder: "What shadow narrative should I design?",               example: "e.g. The shadow narrative of a kingdom that calls itself a democracy — told from the perspective of those who have no vote", series: "journey"  },
  { id: "TransformationEngine",  name: "Transformation Engine",   icon: "🦋", color: "#15803d", gradient: "linear-gradient(135deg,#15803d,#16a34a)", tagline: "Change Architect",        description: "Designs metamorphosis narratives — characters who change so completely that who they were is almost a different person.", placeholder: "What transformation arc should I design?",             example: "e.g. A character who transforms so many times they can no longer remember who they started as — and what they do with that", series: "journey"  },
  { id: "ThresholdEngine",       name: "Threshold Engine",        icon: "🚪", color: "#6b7280", gradient: "linear-gradient(135deg,#6b7280,#4b5563)", tagline: "Liminal Architect",       description: "Designs liminal spaces and threshold moments — the in-between states where transformation happens and identity is suspended.", placeholder: "What threshold or liminal space should I design?",    example: "e.g. A mountain pass that takes 3 days to cross where travelers forget their names — and what emerges on the other side",  series: "journey"  },
  { id: "MentorArchetypeEngine", name: "Mentor Archetype Engine", icon: "🧙", color: "#0891b2", gradient: "linear-gradient(135deg,#0891b2,#0e7490)", tagline: "Guide Architect",         description: "Designs wise guide figures — their knowledge, their limitations, what they cannot say, and why they always leave.",     placeholder: "What mentor archetype should I design?",               example: "e.g. A mentor whose greatest wisdom is knowing when to withhold the answer so the student must find it themselves",         series: "archetype" },
  { id: "OracleArchetypeEngine", name: "Oracle Archetype Engine", icon: "👁️", color: "#78350f", gradient: "linear-gradient(135deg,#78350f,#92400e)", tagline: "Oracle Architect",        description: "Designs truth-tellers and seers — their gift, their burden, who believes them, and the price of knowing too much.",   placeholder: "What oracle archetype should I design?",               example: "e.g. An oracle who can only speak truth through riddles because direct speech drives those who hear it permanently silent", series: "folklore" },
  { id: "DestinyEngine",         name: "Destiny Engine",          icon: "⭐", color: "#4f46e5", gradient: "linear-gradient(135deg,#4f46e5,#4338ca)", tagline: "Fate Architect",          description: "Designs the mechanics of fate and free will in a fictional world — how destiny works, who controls it, and who escapes.", placeholder: "What destiny system should I design?",                example: "e.g. A world where destiny is a river with banks — you can swim upstream, but the current always wins, eventually",        series: "journey"  },
];

export interface MythweaveSeriesDefinition { id: string; name: string; symbol: string; icon: string; gradient: string; description: string; engines: string[]; estimatedMinutes: number; }

export const MYTHWEAVE_SERIES: MythweaveSeriesDefinition[] = [
  { id: "archetype", name: "ARCHETYPE-Series", symbol: "AR", icon: "🏛️", gradient: "linear-gradient(135deg,#7c3aed,#be185d,#ca8a04)", description: "Power Trifecta — Archetype, Trickster, and Mentor Archetype — the universal figures who shape every story.",       engines: ["ArchetypeEngine","TricksterEngine","MentorArchetypeEngine"],              estimatedMinutes: 3 },
  { id: "folklore",  name: "FOLKLORE-Series",  symbol: "FL", icon: "📖", gradient: "linear-gradient(135deg,#d97706,#0f766e,#1d4ed8)", description: "Living Myth Trifecta — Folklore, Symbol System, and Oracle Archetype — the stories people tell when no one is watching.", engines: ["FolkloreEngine","SymbolSystemEngine","OracleArchetypeEngine"],            estimatedMinutes: 3 },
  { id: "journey",   name: "JOURNEY-Series",   symbol: "JO", icon: "⚔️", gradient: "linear-gradient(135deg,#dc2626,#374151,#15803d)", description: "Quest Trifecta — Hero Journey, Shadow Narrative, and Destiny — the complete arc of transformation and return.",         engines: ["HeroJourneyEngine","ShadowNarrativeEngine","DestinyEngine"],              estimatedMinutes: 3 },
  { id: "change",    name: "CHANGE-Series",    symbol: "CH", icon: "🦋", gradient: "linear-gradient(135deg,#15803d,#6b7280,#0891b2)", description: "Transformation Trifecta — Transformation, Threshold, and Ritual Design — the mechanics of how a person changes.",       engines: ["TransformationEngine","ThresholdEngine","RitualDesignEngine"],            estimatedMinutes: 3 },
  { id: "meaning",   name: "MEANING-Series",   symbol: "MN", icon: "🌀", gradient: "linear-gradient(135deg,#0f766e,#4f46e5,#d97706)", description: "Pattern Trifecta — Motif, Archetype, and Destiny — the recurring patterns that give a fictional world its meaning.",   engines: ["MotifEngine","ArchetypeEngine","DestinyEngine"],                          estimatedMinutes: 3 },
];

export function getMythweaveEngineById(id: string): MythweaveEngineDefinition | undefined { return MYTHWEAVE_ENGINES.find(e => e.id === id); }

export async function runMythweaveEngine(opts: { engineId: string; engineName: string; topic: string; context?: string; onChunk: (t: string) => void; onDone?: () => void; onError?: (e: string) => void; }): Promise<void> {
  const { engineId, topic, context, onChunk, onDone, onError } = opts;
  await streamEngine({ engineId, topic, context, onChunk, onDone: onDone ? () => onDone() : undefined, onError });
}
