export interface ReligionForgeEngineDefinition { id: string; name: string; icon: string; color: string; tagline: string; description: string; placeholder: string; example: string; series?: string; }
export interface ReligionForgeSeriesDefinition { id: string; name: string; symbol: string; icon: string; gradient: string; description: string; engines: string[]; estimatedMinutes: number; }

export const RELIGIONFORGE_ENGINES: ReligionForgeEngineDefinition[] = [
  { id: "TheologyEngine",       name: "Theology Engine",        icon: "📜", color: "#4f46e5", tagline: "Doctrine Architect",      description: "Designs the core theological claims of a fictional religion — what it says about creation, purpose, morality, and the divine.",   placeholder: "What theology should this religion have?",            example: "e.g. A theology that holds all gods are real but only your patron god is good — a universe of real competing divinities",             series: "pantheon"    },
  { id: "DeityDesignEngine",    name: "Deity Design Engine",    icon: "⚡", color: "#7c3aed", tagline: "God Architect",           description: "Creates individual deities — their domains, personalities, relationships with each other, and what they actually want from mortals.", placeholder: "What deity should I design?",                        example: "e.g. A god of contracts whose domain is both marriage and war — because in this theology both are agreements made under duress",    series: "pantheon"    },
  { id: "SacredTextEngine",     name: "Sacred Text Engine",     icon: "📖", color: "#d97706", tagline: "Scripture Architect",     description: "Designs the sacred texts of a religion — their authorship disputes, their contradictions, their interpretive traditions.",        placeholder: "What sacred texts should this religion have?",        example: "e.g. A religion whose core text was written by 12 different prophets who never agreed — and all 12 versions are considered equally canonical", series: "sacredtext" },
  { id: "ClergyCasteEngine",    name: "Clergy Caste Engine",    icon: "🧙", color: "#be185d", tagline: "Priesthood Architect",    description: "Designs the priestly hierarchy — roles, ranks, celibacy rules, how clergy are selected, and what power they actually hold.",        placeholder: "What priestly system should this religion have?",    example: "e.g. A religion where clergy are selected by lottery from the general population — everyone dreads being chosen",                  series: "clergy"      },
  { id: "RitualEngine",         name: "Ritual Engine",          icon: "🕯️", color: "#dc2626", tagline: "Ceremony Architect",      description: "Creates the ritual life of a religion — daily practices, seasonal ceremonies, rites of passage, and what happens when rituals fail.", placeholder: "What rituals does this religion practice?",           example: "e.g. A religion with 3 contradictory theories about what makes a ritual valid — factions fight over which version is acceptable",  series: "clergy"      },
  { id: "SchismEngine",         name: "Schism Engine",          icon: "💥", color: "#ca8a04", tagline: "Division Architect",      description: "Designs the great schisms of a religion — what theological disagreement divided the faithful and what each side claims is original.", placeholder: "What caused the great schism in this religion?",      example: "e.g. A schism over whether the god speaks directly or through intermediaries — 800 years of violence over this question",          series: "heresy"      },
  { id: "HeresyEngine",         name: "Heresy Engine",          icon: "🔥", color: "#374151", tagline: "Heresy Architect",        description: "Designs heresies and forbidden beliefs — what the church condemns, why, and what the heretics actually believe and practice.",     placeholder: "What heresies exist in this religion?",              example: "e.g. A heresy that holds suffering itself is divine — the most devout believers seek out pain as communion with the divine",        series: "heresy"      },
  { id: "SaintsEngine",         name: "Saints Engine",          icon: "✨", color: "#0891b2", tagline: "Saint Architect",         description: "Creates the saints and holy figures of a religion — their stories, their miracles, the cults that form around them, and the politics of canonization.", placeholder: "What saints or holy figures exist in this religion?", example: "e.g. A saint who performed one miracle and then publicly renounced the faith — and remains venerated by both sides",        series: "sacredtext"  },
  { id: "AfterlifeEngine",      name: "Afterlife Engine",        icon: "🌌", color: "#15803d", tagline: "Death Belief Architect",  description: "Designs what a religion believes happens after death — and how those beliefs shape how the living treat the dying and the dead.",   placeholder: "What afterlife does this religion teach?",            example: "e.g. A religion that holds the afterlife is simply a replay of your life, and you are living your afterlife right now",              series: "afterlife"   },
  { id: "PrayerSystemEngine",   name: "Prayer System Engine",   icon: "🙏", color: "#78350f", tagline: "Prayer Architect",        description: "Designs how prayer works in a religion — postures, timing, formulas, what prayers are answered, and what the silence means.",     placeholder: "How does prayer work in this religion?",             example: "e.g. A religion where prayers must be whispered to be valid — shouting is considered aggression toward the divine",                 series: "clergy"      },
  { id: "MiracleEngine",        name: "Miracle Engine",         icon: "⭐", color: "#0f766e", tagline: "Miracle Architect",       description: "Designs how miracles work in a fictional religion — what counts, who verifies them, and what a religion does with unexplained events.", placeholder: "How do miracles work in this religion?",             example: "e.g. A religion where miracles require 3 independent witnesses but witnesses must be of opposing faiths to prevent bias",           series: "pantheon"    },
  { id: "ReligiousWarEngine",   name: "Religious War Engine",   icon: "⚔️", color: "#6b7280", tagline: "Holy War Architect",      description: "Designs holy wars — the theology that justified them, what atrocities were committed in the name of faith, and what remains after.", placeholder: "What holy war should I design?",                     example: "e.g. A holy war fought over a relic that was later discovered to be fraudulent — and what both sides do with that knowledge",      series: "heresy"      },
  { id: "AtheismResponseEngine",name: "Atheism Response Engine", icon: "❓", color: "#4b5563", tagline: "Doubt Architect",         description: "Designs how a religious culture responds to atheism — whether it's heresy, mental illness, criminal, or just shameful.",           placeholder: "How does this religious culture respond to atheism?", example: "e.g. A theocratic state that classifies atheism as a mental disorder — atheists are 'treated' rather than punished",                 series: "heresy"      },
];

export const RELIGIONFORGE_SERIES: ReligionForgeSeriesDefinition[] = [
  { id: "pantheon",   name: "PANTHEON-Series",    symbol: "PA", icon: "⚡", gradient: "linear-gradient(135deg,#4f46e5,#7c3aed,#0891b2)", description: "Divine Design — Theology, Deity Design, and Miracles — the core metaphysical claims of a religion.",         engines: ["TheologyEngine","DeityDesignEngine","MiracleEngine"],                              estimatedMinutes: 3 },
  { id: "sacredtext", name: "SACRED-TEXT-Series", symbol: "ST", icon: "📖", gradient: "linear-gradient(135deg,#d97706,#be185d,#0f766e)", description: "Holy Words — Sacred Text and Saints — the written tradition and the people who embodied it.",                  engines: ["SacredTextEngine","SaintsEngine"],                                                 estimatedMinutes: 2 },
  { id: "clergy",     name: "CLERGY-Series",      symbol: "CL", icon: "🧙", gradient: "linear-gradient(135deg,#be185d,#dc2626,#78350f)", description: "Sacred Institution — Clergy, Ritual, and Prayer — how the religion organizes its practice and worship.",        engines: ["ClergyCasteEngine","RitualEngine","PrayerSystemEngine"],                           estimatedMinutes: 3 },
  { id: "heresy",     name: "HERESY-Series",      symbol: "HE", icon: "🔥", gradient: "linear-gradient(135deg,#374151,#ca8a04,#6b7280)", description: "Division — Schism, Heresy, Religious War, and Atheism Response — the violence of theological disagreement.",   engines: ["SchismEngine","HeresyEngine","ReligiousWarEngine","AtheismResponseEngine"],         estimatedMinutes: 4 },
  { id: "afterlife",  name: "AFTERLIFE-Series",   symbol: "AL", icon: "🌌", gradient: "linear-gradient(135deg,#15803d,#4f46e5,#374151)", description: "Death and Beyond — Afterlife, Ritual, and Theology — what a religion says about death and why it matters.",    engines: ["AfterlifeEngine","RitualEngine","TheologyEngine"],                                  estimatedMinutes: 3 },
];

export async function runReligionForgeEngine(opts: { engineId: string; engineName: string; topic: string; onChunk: (t: string) => void; onDone?: () => void; onError?: (e: string) => void; }): Promise<void> {
  const { engineId, engineName, topic, onChunk, onDone, onError } = opts;
  try {
    const resp = await fetch("/api/openai/engine-run", { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ engineId, engineName, topic }) });
    if (!resp.ok || !resp.body) { onError?.(`Engine returned ${resp.status}`); return; }
    const reader = resp.body.getReader(); const decoder = new TextDecoder();
    while (true) {
      const { done, value } = await reader.read(); if (done) break;
      for (const line of decoder.decode(value).split("\n")) {
        if (!line.startsWith("data:")) continue;
        try { const p = JSON.parse(line.slice(5).trim()) as { content?: string; done?: boolean }; if (p.content) onChunk(p.content); if (p.done) onDone?.(); } catch { /* skip */ }
      }
    }
  } catch (err) { onError?.(String(err)); }
}
