import { streamEngine } from "@/controller";
export interface SoundscapeEngineDefinition {
  id: string; name: string; icon: string; color: string; gradient: string;
  tagline: string; description: string; placeholder: string; example: string; series?: string;
}

export const SOUNDSCAPE_ENGINES: SoundscapeEngineDefinition[] = [
  { id: "FictionalMusicEngine",     name: "Fictional Music Engine",     icon: "🎼", color: "#7c3aed", gradient: "linear-gradient(135deg,#7c3aed,#6d28d9)", tagline: "Music Theory Architect",    description: "Invents complete fictional music theory systems — scales, notation, intervals, and the cultural meanings they carry.",   placeholder: "What music theory system should I design?",             example: "e.g. A culture with only 5-tone scales where the gaps between notes carry as much meaning as the notes themselves",            series: "music"    },
  { id: "InstrumentForgeEngine",    name: "Instrument Forge Engine",    icon: "🎻", color: "#be185d", gradient: "linear-gradient(135deg,#be185d,#db2777)", tagline: "Instrument Architect",      description: "Designs fictional musical instruments — construction, material, playing method, range, and cultural role.",              placeholder: "What fictional instrument should I design?",            example: "e.g. An instrument carved from the bones of extinct creatures that only plays in mourning ceremonies",                       series: "music"    },
  { id: "AcousticEnvironmentEngine",name: "Acoustic Environment Engine",icon: "🏔️", color: "#0369a1", gradient: "linear-gradient(135deg,#0369a1,#0284c7)", tagline: "Soundscape Architect",      description: "Designs the complete sonic landscape of fictional places — what you hear there and what those sounds mean.",              placeholder: "What acoustic environment should I design?",            example: "e.g. A underground city where sound travels through water-filled tubes and all conversations are overheard by all",           series: "ambient"  },
  { id: "CeremonialMusicEngine",    name: "Ceremonial Music Engine",    icon: "🎺", color: "#d97706", gradient: "linear-gradient(135deg,#d97706,#b45309)", tagline: "Ceremony Architect",        description: "Creates the music of rituals, weddings, funerals, coronations, and sacred ceremonies in fictional cultures.",           placeholder: "What ceremonial music should I design?",               example: "e.g. A funeral tradition where mourners hum the deceased person's personal melody — the one they composed at birth",         series: "ceremony" },
  { id: "WarMusicEngine",           name: "War Music Engine",           icon: "🥁", color: "#dc2626", gradient: "linear-gradient(135deg,#dc2626,#991b1b)", tagline: "Battle Sound Architect",    description: "Designs the sonic language of war — war drums, battle horns, marching rhythms, and the music soldiers die hearing.",    placeholder: "What war music system should I design?",               example: "e.g. An army whose battle music is designed to terrify enemies by mimicking the sound of their worst childhood nightmares", series: "ceremony" },
  { id: "LullabyEngine",            name: "Lullaby Engine",             icon: "🌙", color: "#1d4ed8", gradient: "linear-gradient(135deg,#1d4ed8,#1e40af)", tagline: "Sleep Song Architect",      description: "Creates lullabies, sleep songs, and comfort music — and the cultures that use them and what they secretly mean.",       placeholder: "What lullaby tradition should I design?",              example: "e.g. A culture where lullabies contain encoded warnings about dangers the child will face when they grow up",                series: "ambient"  },
  { id: "EpicBalladEngine",         name: "Epic Ballad Engine",         icon: "🎤", color: "#15803d", gradient: "linear-gradient(135deg,#15803d,#16a34a)", tagline: "Ballad Architect",          description: "Writes epic ballads and bardic traditions — the songs that carry a culture's memory across generations.",               placeholder: "What epic ballad should I design?",                    example: "e.g. A civilization whose only historical records are ballads — and historians who argue over whether any of it is true",   series: "music"    },
  { id: "SilenceEngine",            name: "Silence Engine",             icon: "🤫", color: "#4b5563", gradient: "linear-gradient(135deg,#4b5563,#374151)", tagline: "Silence Architect",         description: "Designs the meaning and use of silence in fictional worlds — the rests in music, the pauses in speech, the sacred quiet.", placeholder: "What role should silence play in this culture?",       example: "e.g. A culture where 3 seconds of silence after a statement means you agree — and one moment of silence is a declaration of war", series: "ambient" },
  { id: "NatureSoundEngine",        name: "Nature Sound Engine",        icon: "🌊", color: "#0f766e", gradient: "linear-gradient(135deg,#0f766e,#0d9488)", tagline: "Nature Sound Architect",    description: "Designs the natural soundscape of fictional worlds — bird calls, insect songs, wind through alien vegetation.",         placeholder: "What natural soundscape should I design?",             example: "e.g. A world where the dominant predator hunts by mimicking the sound of rain, so the rain itself is feared",               series: "ambient"  },
  { id: "CrowdSoundEngine",         name: "Crowd Sound Engine",         icon: "👥", color: "#78350f", gradient: "linear-gradient(135deg,#78350f,#92400e)", tagline: "Crowd Sound Architect",     description: "Designs the sound of gatherings, markets, riots, festivals, and masses — the collective voice of fiction.",             placeholder: "What crowd sound environment should I design?",         example: "e.g. A culture's festival where 10,000 people hum a single drone note that shifts in pitch based on collective emotion",   series: "ceremony" },
  { id: "SonicWeaponEngine",        name: "Sonic Weapon Engine",        icon: "⚡", color: "#ca8a04", gradient: "linear-gradient(135deg,#ca8a04,#a16207)", tagline: "Sonic Weapon Architect",    description: "Designs fictional instruments and sounds used as weapons, tools, or means of control in fictional worlds.",              placeholder: "What sonic weapon or tool should I design?",           example: "e.g. A horn whose resonance frequency matches the structural weakness of stone — used to bring down walls from two miles", series: "music"    },
  { id: "MusicMemoryEngine",        name: "Music Memory Engine",        icon: "🧠", color: "#6b7280", gradient: "linear-gradient(135deg,#6b7280,#4b5563)", tagline: "Memory Architect",          description: "Designs how fictional cultures use music to preserve cultural memory, transmit history, and encode secrets.",           placeholder: "What musical memory tradition should I design?",        example: "e.g. A civilization where every law is stored as a distinct rhythm that lawyers must perform from memory in court",          series: "ceremony" },
  { id: "HarmonySystemEngine",      name: "Harmony System Engine",      icon: "🎵", color: "#0891b2", gradient: "linear-gradient(135deg,#0891b2,#0e7490)", tagline: "Harmony Architect",         description: "Invents fictional harmonic systems — consonance, dissonance, and the emotional and spiritual meanings of sound combinations.", placeholder: "What harmony system should I design?",               example: "e.g. A world where dissonance is considered sacred and consonance is associated with moral compromise and weakness",         series: "music"    },
];

export interface SoundscapeSeriesDefinition { id: string; name: string; symbol: string; icon: string; gradient: string; description: string; engines: string[]; estimatedMinutes: number; }

export const SOUNDSCAPE_SERIES: SoundscapeSeriesDefinition[] = [
  { id: "music",    name: "MUSIC-Series",    symbol: "MU", icon: "🎼", gradient: "linear-gradient(135deg,#7c3aed,#be185d,#15803d)", description: "Music Trifecta — Fictional Music, Instrument Forge, and Epic Ballad — the theory, instrument, and tradition of a culture's sound.", engines: ["FictionalMusicEngine","InstrumentForgeEngine","EpicBalladEngine"],          estimatedMinutes: 3 },
  { id: "ceremony", name: "CEREMONY-Series", symbol: "CE", icon: "🎺", gradient: "linear-gradient(135deg,#d97706,#dc2626,#ca8a04)", description: "Ceremony Trifecta — War Music, Ceremonial Music, and Crowd Sound — the collective sonic experience of a civilization.", engines: ["WarMusicEngine","CeremonialMusicEngine","CrowdSoundEngine"],                estimatedMinutes: 3 },
  { id: "ambient",  name: "AMBIENT-Series",  symbol: "AM", icon: "🌊", gradient: "linear-gradient(135deg,#0369a1,#1d4ed8,#0f766e)", description: "Soundscape Trifecta — Acoustic Environment, Lullaby, and Nature Sound — the sonic landscape of a world at rest.",       engines: ["AcousticEnvironmentEngine","LullabyEngine","NatureSoundEngine"],            estimatedMinutes: 3 },
  { id: "memory",   name: "MEMORY-Series",   symbol: "ME", icon: "🧠", gradient: "linear-gradient(135deg,#6b7280,#0891b2,#4b5563)", description: "Memory Trifecta — Music Memory, Harmony System, and Epic Ballad — how sound carries a civilization across time.",      engines: ["MusicMemoryEngine","HarmonySystemEngine","EpicBalladEngine"],               estimatedMinutes: 3 },
  { id: "power",    name: "POWER-Series",    symbol: "PO", icon: "⚡", gradient: "linear-gradient(135deg,#ca8a04,#dc2626,#7c3aed)", description: "Power Trifecta — Sonic Weapon, War Music, and Silence — the weaponization of sound and its absence.",                  engines: ["SonicWeaponEngine","WarMusicEngine","SilenceEngine"],                       estimatedMinutes: 3 },
];

export function getSoundscapeEngineById(id: string): SoundscapeEngineDefinition | undefined { return SOUNDSCAPE_ENGINES.find(e => e.id === id); }

export async function runSoundscapeEngine(opts: { engineId: string; engineName: string; topic: string; context?: string; onChunk: (t: string) => void; onDone?: () => void; onError?: (e: string) => void; }): Promise<void> {
  const { engineId, topic, context, onChunk, onDone, onError } = opts;
  await streamEngine({ engineId, topic, context, onChunk, onDone: onDone ? () => onDone() : undefined, onError });
}
