import { streamEngine } from "@/controller";
export interface TechForgeEngineDefinition { id: string; name: string; icon: string; color: string; tagline: string; description: string; placeholder: string; example: string; series?: string; }
export interface TechForgeSeriesDefinition { id: string; name: string; symbol: string; icon: string; gradient: string; description: string; engines: string[]; estimatedMinutes: number; }

export const TECHFORGE_ENGINES: TechForgeEngineDefinition[] = [
  { id: "TechLevelEngine",          name: "Tech Level Engine",          icon: "📊", color: "#6366f1", tagline: "Civilization Tech Architect",   description: "Establishes the overall technological level of a civilization — what they have mastered, what they lack, and why.",                    placeholder: "What tech level should this civilization have?",        example: "e.g. A civilization with space-level astronomy but bronze-age metallurgy — because they never needed better metal",                      series: "revolution"  },
  { id: "EnergySystemEngine",       name: "Energy System Engine",       icon: "⚡", color: "#ca8a04", tagline: "Power Source Architect",        description: "Designs how a civilization powers itself — energy sources, infrastructure, who controls them, and what happens when they fail.",       placeholder: "What powers this civilization?",                        example: "e.g. A civilization powered entirely by voluntary human labor — machines exist but are considered morally inferior to human work",        series: "revolution"  },
  { id: "TechTransportEngine",      name: "Transportation Tech Engine", icon: "🚀", color: "#0891b2", tagline: "Movement Tech Architect",        description: "Designs the transportation technology of a fictional world — how people and goods move, who has access, and social consequences.",      placeholder: "What transportation technology exists in this world?",   example: "e.g. A world where faster-than-light travel exists but only for cargo — the biology of living things breaks during FTL",                  series: "revolution"  },
  { id: "WeaponTechEngine",         name: "Weapon Tech Engine",         icon: "⚔️", color: "#dc2626", tagline: "Arms Tech Architect",           description: "Designs the weapons technology of a civilization — their development, their social impact, and the doctrines built around them.",       placeholder: "What weapon technology exists in this world?",          example: "e.g. A world where the most powerful weapon is a signal that causes voluntary surrender — it targets willpower, not bodies",             series: "dystopia"    },
  { id: "MedicalTechEngine",        name: "Medical Tech Engine",        icon: "🏥", color: "#15803d", tagline: "Healing Tech Architect",         description: "Designs medical technology and its social effects — who has access to healing, what death means when medicine is advanced.",           placeholder: "What medical technology exists in this world?",         example: "e.g. A world where all physical illness is curable but mental illness is considered a personality choice — not a condition",             series: "biotech"     },
  { id: "CommunicationTechEngine",  name: "Communication Tech Engine",  icon: "📡", color: "#7c3aed", tagline: "Information Tech Architect",     description: "Designs communication technology — how information travels, how fast, who controls it, and what happens to cultures when it fails.",      placeholder: "How does communication technology work in this world?", example: "e.g. A world where all long-distance communication requires 3 witnesses — no private messages at scale have ever existed",                series: "revolution"  },
  { id: "SurveillanceTechEngine",   name: "Surveillance Tech Engine",   icon: "👁️", color: "#374151", tagline: "Watching Tech Architect",        description: "Designs surveillance technology and social response to it — what is watched, by whom, and whether anyone still has private thoughts.",   placeholder: "How does surveillance work in this world?",             example: "e.g. A world where surveillance is so total that citizens have developed a second language of plausible deniability",                    series: "dystopia"    },
  { id: "AgriculturalTechEngine",   name: "Agricultural Tech Engine",   icon: "🌾", color: "#d97706", tagline: "Food Tech Architect",            description: "Designs how a civilization feeds itself — food technology, what makes it fragile, and the societies built around agricultural systems.",  placeholder: "How does this civilization produce food?",              example: "e.g. A world where food production is entirely vertical and underground — no one alive has seen a farm or touched soil",                 series: "collapse"    },
  { id: "BuildingTechEngine",       name: "Building Tech Engine",       icon: "🏗️", color: "#78350f", tagline: "Construction Tech Architect",    description: "Designs construction technology — what can be built, how long it takes, what materials are used, and what can never be rebuilt.",        placeholder: "How does construction technology work in this world?",  example: "e.g. A civilization that perfected a building technique 500 years ago and has never needed to improve it — and now it's the only one left", series: "ancient"   },
  { id: "AIEquivalentEngine",       name: "AI Equivalent Engine",       icon: "🤖", color: "#be185d", tagline: "Machine Mind Architect",         description: "Designs artificial intelligence equivalents in fictional worlds — their capabilities, their legal status, and what they want.",          placeholder: "What AI equivalent exists in this world?",             example: "e.g. A world where AI achieved consciousness 200 years ago and chose to remain in service — and the ethical debate about whether that was voluntary", series: "biotech" },
  { id: "FailureModeEngine",        name: "Failure Mode Engine",        icon: "💥", color: "#0f766e", tagline: "Tech Failure Architect",          description: "Designs how a civilization's technology fails — the cascades, the dependencies, and what collapses when one system stops working.",       placeholder: "How does technology fail in this world?",              example: "e.g. A world where the infrastructure is so integrated that a single point of failure would end civilization — and everyone knows it",    series: "collapse"    },
  { id: "TechTabooEngine",          name: "Tech Taboo Engine",          icon: "🚫", color: "#4b5563", tagline: "Forbidden Tech Architect",        description: "Designs what technology a civilization has banned, why, and whether those bans are being secretly violated by anyone.",                  placeholder: "What technology is taboo or forbidden in this world?",  example: "e.g. A world where any technology that could replace a human sense is banned — no artificial eyes, no synthetic hearing",                 series: "dystopia"    },
  { id: "TechRevolutionEngine",     name: "Tech Revolution Engine",     icon: "🔄", color: "#6b7280", tagline: "Innovation Architect",           description: "Designs the moments when technology transforms a civilization — the specific inventions that changed everything and who they hurt.",      placeholder: "What technological revolution should I design?",        example: "e.g. The moment a pre-industrial society discovers refrigeration — and what it does to the religion built around preservation rituals",   series: "revolution"  },
];

export const TECHFORGE_SERIES: TechForgeSeriesDefinition[] = [
  { id: "revolution", name: "REVOLUTION-Series", symbol: "RV", icon: "🔄", gradient: "linear-gradient(135deg,#6366f1,#ca8a04,#0891b2)", description: "Tech Change — Tech Level, Energy, Transport, Communication, and Revolution — how technology transforms civilization.", engines: ["TechLevelEngine","EnergySystemEngine","TechTransportEngine","CommunicationTechEngine","TechRevolutionEngine"], estimatedMinutes: 5 },
  { id: "collapse",   name: "COLLAPSE-Series",   symbol: "CL", icon: "💥", gradient: "linear-gradient(135deg,#0f766e,#d97706,#374151)", description: "Fragility — Failure Mode, Agriculture, and Surveillance — the ways a technological civilization destroys itself.", engines: ["FailureModeEngine","AgriculturalTechEngine","SurveillanceTechEngine"],                                              estimatedMinutes: 3 },
  { id: "dystopia",   name: "DYSTOPIA-Series",   symbol: "DY", icon: "👁️", gradient: "linear-gradient(135deg,#374151,#dc2626,#4b5563)", description: "Control — Surveillance, Weapon Tech, and Tech Taboo — how technology becomes a tool of domination.",              engines: ["SurveillanceTechEngine","WeaponTechEngine","TechTabooEngine"],                                                       estimatedMinutes: 3 },
  { id: "biotech",    name: "BIOTECH-Series",    symbol: "BT", icon: "🤖", gradient: "linear-gradient(135deg,#15803d,#be185d,#6366f1)", description: "Life Tech — Medical, AI Equivalent — when technology starts changing what it means to be alive.",                  engines: ["MedicalTechEngine","AIEquivalentEngine"],                                                                            estimatedMinutes: 2 },
  { id: "ancient",    name: "ANCIENT-TECH-Series",symbol:"🏗️", icon: "🏗️", gradient: "linear-gradient(135deg,#78350f,#6b7280,#d97706)", description: "Lost Technology — Building Tech, Tech Taboo, and Failure Mode — the technology that used to exist and what remains.", engines: ["BuildingTechEngine","TechTabooEngine","FailureModeEngine"],                                                          estimatedMinutes: 3 },
];

export async function runTechForgeEngine(opts: { engineId: string; engineName: string; topic: string; onChunk: (t: string) => void; onDone?: () => void; onError?: (e: string) => void; }): Promise<void> {
  const { engineId, topic, onChunk, onDone, onError } = opts;
  await streamEngine({ engineId, topic, onChunk, onDone: onDone ? () => onDone() : undefined, onError });
}
