export interface TimelineEngineDefinition {
  id: string; name: string; icon: string; color: string; gradient: string;
  tagline: string; description: string; placeholder: string; example: string; series?: string;
}

export const TIMELINE_ENGINES: TimelineEngineDefinition[] = [
  { id: "TimelineEngine",           name: "Timeline Engine",           icon: "📅", color: "#6366f1", gradient: "linear-gradient(135deg,#6366f1,#4f46e5)", tagline: "Timeline Architect",          description: "Constructs a world's complete historical timeline — eras, turning points, and the thread of cause and effect.",          placeholder: "What world timeline should I construct?",              example: "e.g. A world where time accelerates near the poles, creating civilizations that age faster than those at the equator",       series: "timeline" },
  { id: "AlternateHistoryEngine",   name: "Alternate History Engine",  icon: "🔀", color: "#7c3aed", gradient: "linear-gradient(135deg,#7c3aed,#6d28d9)", tagline: "Divergence Architect",        description: "Designs 'what if' divergence points — the moment history split and the world that followed from a single change.",      placeholder: "What alternate history should I design?",              example: "e.g. What if the printing press was never invented — how does knowledge hoard, who controls the world, what changes?",      series: "alternate"},
  { id: "ParallelTimelineEngine",   name: "Parallel Timeline Engine",  icon: "∞",  color: "#0891b2", gradient: "linear-gradient(135deg,#0891b2,#0e7490)", tagline: "Parallel Architect",          description: "Designs multiple simultaneous timelines — parallel realities that share origins but diverge in meaningful ways.",       placeholder: "What parallel timeline system should I design?",        example: "e.g. Three parallel timelines where the same war was won by a different side — and how that shapes three different worlds", series: "alternate"},
  { id: "TemporalParadoxEngine",    name: "Temporal Paradox Engine",   icon: "🌀", color: "#dc2626", gradient: "linear-gradient(135deg,#dc2626,#991b1b)", tagline: "Paradox Architect",           description: "Designs temporal paradoxes — causality loops, bootstrap paradoxes, and the narrative knots they create.",              placeholder: "What temporal paradox should I design?",               example: "e.g. A civilization that only exists because a time traveler went back to create it, but the traveler was born there",      series: "paradox"  },
  { id: "HistoricalDivergenceEngine",name:"Historical Divergence Engine",icon:"🗺️",color: "#d97706", gradient: "linear-gradient(135deg,#d97706,#b45309)", tagline: "Butterfly Effect Architect",  description: "Maps the butterfly effect in fictional history — how small moments cascade into civilization-altering consequences.",   placeholder: "What historical divergence should I design?",           example: "e.g. A single document lost at sea in 1200 CE that cascades into a completely different world order by 1800",              series: "timeline" },
  { id: "AncestralLineEngine",      name: "Ancestral Line Engine",     icon: "🌳", color: "#15803d", gradient: "linear-gradient(135deg,#15803d,#16a34a)", tagline: "Dynasty Architect",           description: "Traces bloodlines and dynasties across centuries — births, deaths, alliances, betrayals, and the weight of legacy.",  placeholder: "What ancestral line or dynasty should I trace?",        example: "e.g. A ruling family where every third generation is cursed with identical gifts and identical moral failures",             series: "cycle"    },
  { id: "FutureHistoryEngine",      name: "Future History Engine",     icon: "🔭", color: "#1d4ed8", gradient: "linear-gradient(135deg,#1d4ed8,#1e40af)", tagline: "Future Architect",            description: "Writes history from the future's perspective — what the coming centuries will remember about the present moment.",     placeholder: "What future history should I write?",                  example: "e.g. How will 2500 historians describe our current era — what will they call it and what will they say we got wrong?",    series: "timeline" },
  { id: "CalendarSystemEngine",     name: "Calendar System Engine",    icon: "🗓️", color: "#ca8a04", gradient: "linear-gradient(135deg,#ca8a04,#a16207)", tagline: "Time-Keeping Architect",      description: "Invents fictional calendar and time-keeping systems — days, months, eras, and the cultural logic behind each unit.",   placeholder: "What calendar system should I design?",                example: "e.g. A culture that counts time in cycles of a specific comet, meaning their 'year' is 76 Earth years long",              series: "cycle"    },
  { id: "AgeTransitionEngine",      name: "Age Transition Engine",     icon: "⏳", color: "#be185d", gradient: "linear-gradient(135deg,#be185d,#db2777)", tagline: "Age Architect",               description: "Designs the moment one age ends and another begins — the collapse, the transition, and what survives the crossing.",  placeholder: "What age transition should I design?",                 example: "e.g. The last decade of the Age of Reason — what institutions fail, what new ideas rush in, who is left behind?",        series: "cycle"    },
  { id: "GenerationCycleEngine",    name: "Generation Cycle Engine",   icon: "👶", color: "#0f766e", gradient: "linear-gradient(135deg,#0f766e,#0d9488)", tagline: "Generation Architect",        description: "Designs how generations differ and repeat — the recurring patterns across time and the things each generation forgets.", placeholder: "What generational cycle should I design?",             example: "e.g. A world where every fourth generation believes itself to be the first to truly understand justice, and is wrong",     series: "cycle"    },
  { id: "PropheticTimelineEngine",  name: "Prophetic Timeline Engine", icon: "🔮", color: "#4b5563", gradient: "linear-gradient(135deg,#4b5563,#374151)", tagline: "Prophetic Architect",         description: "Designs timelines shaped by prophecy — how foreknowledge alters decisions and what happens when prophecies are wrong.", placeholder: "What prophetic timeline should I design?",              example: "e.g. A civilization that has been steering toward a prophecy for 800 years — and what happens the day it fails to occur", series: "paradox"  },
  { id: "CollapseTimelineEngine",   name: "Collapse Timeline Engine",  icon: "🌋", color: "#78350f", gradient: "linear-gradient(135deg,#78350f,#92400e)", tagline: "Collapse Architect",          description: "Designs civilizational collapse sequences — the cascade of failures, the last attempts, and what survives.",          placeholder: "What collapse timeline should I design?",              example: "e.g. A 200-year imperial collapse where each generation thinks they are the last to face the worst, and is wrong",         series: "alternate"},
  { id: "ChronologyEngine",         name: "Chronology Engine",         icon: "📜", color: "#6b7280", gradient: "linear-gradient(135deg,#6b7280,#4b5563)", tagline: "Chronology Architect",        description: "Orders and connects historical events into coherent chronological narratives — cause, effect, and sequence.",          placeholder: "What chronology should I construct?",                  example: "e.g. Map every major event in a fictional empire's last century and show how each one caused the next",                   series: "timeline" },
];

export interface TimelineSeriesDefinition { id: string; name: string; symbol: string; icon: string; gradient: string; description: string; engines: string[]; estimatedMinutes: number; }

export const TIMELINE_SERIES: TimelineSeriesDefinition[] = [
  { id: "timeline",  name: "TIMELINE-Series",  symbol: "TL", icon: "📅", gradient: "linear-gradient(135deg,#6366f1,#d97706,#6b7280)", description: "History Trifecta — Timeline, Historical Divergence, and Chronology — the spine of a fictional world's history.", engines: ["TimelineEngine","HistoricalDivergenceEngine","ChronologyEngine"],     estimatedMinutes: 3 },
  { id: "alternate", name: "ALTERNATE-Series", symbol: "AL", icon: "🔀", gradient: "linear-gradient(135deg,#7c3aed,#0891b2,#78350f)", description: "Divergence Trifecta — Alternate History, Parallel Timeline, and Collapse — the branching paths of a world.",      engines: ["AlternateHistoryEngine","ParallelTimelineEngine","CollapseTimelineEngine"], estimatedMinutes: 3 },
  { id: "paradox",   name: "PARADOX-Series",   symbol: "PX", icon: "🌀", gradient: "linear-gradient(135deg,#dc2626,#4b5563,#be185d)", description: "Paradox Trifecta — Temporal Paradox, Prophetic Timeline, and Future History — time folding back on itself.",      engines: ["TemporalParadoxEngine","PropheticTimelineEngine","FutureHistoryEngine"],    estimatedMinutes: 3 },
  { id: "cycle",     name: "CYCLE-Series",     symbol: "CY", icon: "🌳", gradient: "linear-gradient(135deg,#15803d,#ca8a04,#0f766e)", description: "Cycle Trifecta — Generation Cycle, Calendar System, and Age Transition — the rhythms and ages of a civilization.", engines: ["GenerationCycleEngine","CalendarSystemEngine","AgeTransitionEngine"],       estimatedMinutes: 3 },
  { id: "dynasty",   name: "DYNASTY-Series",   symbol: "DY", icon: "👶", gradient: "linear-gradient(135deg,#15803d,#6366f1,#be185d)", description: "Legacy Trifecta — Ancestral Line, Generation Cycle, and Age Transition — how power and memory pass through time.",   engines: ["AncestralLineEngine","GenerationCycleEngine","AgeTransitionEngine"],        estimatedMinutes: 3 },
];

export function getTimelineEngineById(id: string): TimelineEngineDefinition | undefined { return TIMELINE_ENGINES.find(e => e.id === id); }

export async function runTimelineEngine(opts: { engineId: string; engineName: string; topic: string; context?: string; onChunk: (t: string) => void; onDone?: () => void; onError?: (e: string) => void; }): Promise<void> {
  const { engineId, engineName, topic, context, onChunk, onDone, onError } = opts;
  try {
    const resp = await fetch("/api/openai/engine-run", { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ engineId, engineName, topic, context }) });
    if (!resp.ok || !resp.body) { onError?.(`Engine returned ${resp.status}`); return; }
    const reader = resp.body.getReader(); const decoder = new TextDecoder();
    while (true) {
      const { done, value } = await reader.read(); if (done) break;
      for (const line of decoder.decode(value).split("\n")) {
        if (!line.startsWith("data:")) continue;
        try { const p = JSON.parse(line.slice(5).trim()) as { content?: string; done?: boolean }; if (p.content) onChunk(p.content); if (p.done) onDone?.(); } catch { /* skip */ }
      }
    }
  } catch (err) { onError?.(String(err)); }
}
