export interface UrbanWorldEngineDefinition { id: string; name: string; icon: string; color: string; tagline: string; description: string; placeholder: string; example: string; series?: string; }
export interface UrbanWorldSeriesDefinition { id: string; name: string; symbol: string; icon: string; gradient: string; description: string; engines: string[]; estimatedMinutes: number; }

export const URBANWORLD_ENGINES: UrbanWorldEngineDefinition[] = [
  { id: "CityLayoutEngine",         name: "City Layout Engine",         icon: "🗺️", color: "#6366f1", tagline: "Urban Form Architect",      description: "Designs the macro-structure of a fictional city — its grid, its layers, its radial logic, and what its shape reveals about its founders.", placeholder: "What city should I design?",                          example: "e.g. A city built in concentric circles where social class is determined by which ring you live in — center means power",        series: "megacity"    },
  { id: "DistrictEngine",           name: "District Engine",            icon: "🏘️", color: "#d97706", tagline: "Neighborhood Architect",    description: "Designs the character of individual districts — their history, culture, economy, danger level, and what life looks and sounds like there.", placeholder: "What district or neighborhood should I design?",      example: "e.g. A market district that exists only at night — all vendors pack up before dawn and no one agrees on why this tradition started", series: "district"   },
  { id: "UndergroundEngine",        name: "Underground Engine",         icon: "⛏️", color: "#374151", tagline: "Underworld Architect",       description: "Designs what lives below a city — sewers, tunnels, forgotten districts, criminal networks, and what the city hides underground.",     placeholder: "What lies beneath this city?",                        example: "e.g. A fully functional city beneath the official one — older, smaller, and run by entirely different rules",                     series: "underground" },
  { id: "CriminalNetworkEngine",    name: "Criminal Network Engine",    icon: "🃏", color: "#dc2626", tagline: "Underworld Network Architect",description: "Designs criminal organizations — their structure, their codes, their relationship with officials, and what they actually provide.",    placeholder: "What criminal networks operate in this city?",         example: "e.g. An information broker guild that sells secrets to all factions — their neutrality enforced by the fact that everyone needs them", series: "underground" },
  { id: "ArchitectureEngine",       name: "Architecture Engine",        icon: "🏛️", color: "#be185d", tagline: "Building Architect",         description: "Designs the architectural language of a city — what buildings say about the civilization that built them and why.",                 placeholder: "What architectural style defines this city?",          example: "e.g. Every building has an external staircase to the roof — culturally, the roof is considered more important than the interior",   series: "megacity"    },
  { id: "StreetCultureEngine",      name: "Street Culture Engine",      icon: "🎨", color: "#15803d", tagline: "Street Life Architect",      description: "Designs street-level culture — what happens in public spaces, street vendors, public performance, graffiti, and informal life.",     placeholder: "What is street life like in this city?",              example: "e.g. A city where every intersection has a designated storyteller paid by the city — they are the city's unofficial historians",    series: "district"   },
  { id: "MarketEngine",             name: "Market Engine",              icon: "🛒", color: "#ca8a04", tagline: "Commerce Architect",         description: "Designs the economic heartbeat of a city — its markets, trade goods, price systems, and what people actually buy and sell.",          placeholder: "What does this city's economy look like?",            example: "e.g. A city whose primary export is memories — trained specialists extract and sell experiences from willing (and unwilling) donors", series: "megacity"   },
  { id: "PoliticalGeographyEngine", name: "Political Geography Engine", icon: "🗳️", color: "#1d4ed8", tagline: "Power Map Architect",        description: "Maps where power lives in a city — which districts control resources, which are contested, which are abandoned by governance.",     placeholder: "How is political power distributed across this city?", example: "e.g. A city where 3 districts have refused to pay taxes for 40 years — and the government has been too afraid to collect",          series: "district"   },
  { id: "SlumEngine",               name: "Slum Engine",                icon: "🏚️", color: "#78350f", tagline: "Margin Architect",           description: "Designs the margins of a city — slums, informal settlements, tent cities, and the full culture that develops at the edge.",          placeholder: "What does life at the city's margins look like?",     example: "e.g. A slum built entirely in the ruins of the city's former elite quarter — the residents use palace walls as housing foundations", series: "underground" },
  { id: "EliteQuarterEngine",       name: "Elite Quarter Engine",       icon: "🏰", color: "#0891b2", tagline: "Power Quarter Architect",    description: "Designs the elite neighborhoods of a fictional city — their walls, their customs, their relationship to the rest of the city.",       placeholder: "What does the city's elite quarter look like?",       example: "e.g. An elite quarter that hasn't allowed a new family in for 300 years — bloodlines enforced by private law",                     series: "district"   },
  { id: "TransportationEngine",     name: "Transportation Engine",      icon: "🚋", color: "#0f766e", tagline: "Movement Architect",         description: "Designs how people move through a city — transport systems, their social hierarchies, who has access, and who is excluded.",         placeholder: "How do people move through this city?",               example: "e.g. A city where the transportation system reflects class — the upper levels move quickly, the lower levels barely move at all",   series: "megacity"    },
  { id: "CityGhostEngine",          name: "City Ghost Engine",          icon: "👻", color: "#6b7280", tagline: "Urban Memory Architect",     description: "Designs the historical layers of a city — the ruins, the old neighborhoods, the buildings with too many stories, the places memory refuses to leave.", placeholder: "What ghosts haunt this city's past?",    example: "e.g. A city built on 11 previous cities — archaeologists keep finding new civilizations and the current one is worried about what's beneath the oldest", series: "underground" },
  { id: "BoundaryEngine",           name: "Boundary Engine",            icon: "🧱", color: "#4b5563", tagline: "Edge Architect",             description: "Designs the edges and borders of a city — walls, checkpoints, informal boundaries, and how the city polices who belongs.",          placeholder: "How does this city manage its borders and edges?",     example: "e.g. A city with no official borders — but everyone knows exactly where the safe zones end and the wilderness begins",              series: "megacity"    },
];

export const URBANWORLD_SERIES: UrbanWorldSeriesDefinition[] = [
  { id: "megacity",    name: "MEGACITY-Series",    symbol: "MC", icon: "🗺️", gradient: "linear-gradient(135deg,#6366f1,#be185d,#0f766e)", description: "Urban Core — Layout, Architecture, Market, Transport, and Boundary — the complete structure of a city.", engines: ["CityLayoutEngine","ArchitectureEngine","MarketEngine","TransportationEngine","BoundaryEngine"], estimatedMinutes: 5 },
  { id: "district",   name: "DISTRICT-Series",    symbol: "DI", icon: "🏘️", gradient: "linear-gradient(135deg,#d97706,#15803d,#1d4ed8)", description: "Neighborhood Life — District, Street Culture, Elite Quarter, and Political Geography — how people live.", engines: ["DistrictEngine","StreetCultureEngine","EliteQuarterEngine","PoliticalGeographyEngine"],     estimatedMinutes: 4 },
  { id: "underground",name: "UNDERGROUND-Series",  symbol: "UN", icon: "⛏️", gradient: "linear-gradient(135deg,#374151,#dc2626,#78350f)", description: "Below the City — Underground, Criminal Network, Slum, and City Ghost — what the city hides.",             engines: ["UndergroundEngine","CriminalNetworkEngine","SlumEngine","CityGhostEngine"],                 estimatedMinutes: 4 },
  { id: "collapse",   name: "COLLAPSE-Series",    symbol: "CL", icon: "🏚️", gradient: "linear-gradient(135deg,#78350f,#6b7280,#374151)", description: "Decay — Slum, City Ghost, and Underground — the trajectory of a city falling apart from the inside.",      engines: ["SlumEngine","CityGhostEngine","UndergroundEngine"],                                         estimatedMinutes: 3 },
  { id: "ruin",       name: "RUIN-Series",        symbol: "RU", icon: "👻", gradient: "linear-gradient(135deg,#6b7280,#4b5563,#374151)", description: "Dead Cities — City Ghost, Boundary, and Architecture — what remains when a city falls and why.",             engines: ["CityGhostEngine","BoundaryEngine","ArchitectureEngine"],                                    estimatedMinutes: 3 },
];

export async function runUrbanWorldEngine(opts: { engineId: string; engineName: string; topic: string; onChunk: (t: string) => void; onDone?: () => void; onError?: (e: string) => void; }): Promise<void> {
  const { engineId, engineName, topic, onChunk, onDone, onError } = opts;
  try {
    const resp = await fetch("/api/openai/engine-run", { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ engineId, engineName, topic }) });
    if (!resp.ok || !resp.body) { onError?.(`Engine returned ${resp.status}`); return; }
    const reader = resp.body.getReader(); const decoder = new TextDecoder();
    while (true) {
      const { done, value } = await reader.read(); if (done) break;
      for (const line of decoder.decode(value).split("\n")) {
        if (!line.startsWith("data:")) continue;
        try { const p = JSON.parse(line.slice(5).trim()) as { content?: string; done?: boolean }; if (p.content) onChunk(p.content); if (p.done) onDone?.(); } catch { /* skip */ }
      }
    }
  } catch (err) { onError?.(String(err)); }
}
