export interface VisualWorldEngineDefinition { id: string; name: string; icon: string; color: string; tagline: string; description: string; placeholder: string; example: string; series?: string; }
export interface VisualWorldSeriesDefinition { id: string; name: string; symbol: string; icon: string; gradient: string; description: string; engines: string[]; estimatedMinutes: number; }

export const VISUALWORLD_ENGINES: VisualWorldEngineDefinition[] = [
  { id: "ColorPaletteEngine",   name: "Color Palette Engine",   icon: "🎨", color: "#be185d", tagline: "Color World Architect",    description: "Designs the color language of a fictional world — which colors mean power, grief, celebration, danger, and holiness.",       placeholder: "What color language does this world use?",            example: "e.g. A world where white is the color of mourning and black the color of celebration — and the symbolic logic behind why",         series: "fashion"    },
  { id: "FashionCycleEngine",   name: "Fashion Cycle Engine",   icon: "👗", color: "#7c3aed", tagline: "Dress Architect",          description: "Designs how fashion works in a fictional world — trends, cycles, social signals, class markers, and forbidden styles.",         placeholder: "How does fashion work in this world?",                example: "e.g. A world where fashion is illegal — all clothing is standardized — and the black market in beautiful cloth is enormous",       series: "fashion"    },
  { id: "HeraldryEngine",       name: "Heraldry Engine",        icon: "🛡️", color: "#d97706", tagline: "Symbol Power Architect",   description: "Designs heraldic systems — coats of arms, family symbols, what they communicate about lineage, allegiance, and ambition.",     placeholder: "What heraldic system should I design?",              example: "e.g. A heraldry system where symbols can be challenged in combat — win and you take their symbol; lose and you lose yours",       series: "heraldry"   },
  { id: "FlagDesignEngine",     name: "Flag Design Engine",     icon: "🚩", color: "#dc2626", tagline: "Banner Architect",         description: "Designs the flags and banners of fictional nations — their symbols, the debates about changing them, and what flags die for.",    placeholder: "What flags and national symbols exist in this world?", example: "e.g. A nation whose flag has been changed 11 times — each change followed by a period of civil unrest as different factions claim each version", series: "heraldry" },
  { id: "VisualMotifEngine",    name: "Visual Motif Engine",    icon: "🌀", color: "#6366f1", tagline: "Pattern Architect",        description: "Designs recurring visual motifs in a fictional world — the patterns that appear everywhere because of what a culture values.",  placeholder: "What visual motifs define this culture?",             example: "e.g. A culture where the spiral appears in everything — architecture, clothing, tools — because their creation myth is spiral-shaped", series: "symbol"    },
  { id: "ArtMovementEngine",    name: "Art Movement Engine",    icon: "🖼️", color: "#0891b2", tagline: "Art History Architect",    description: "Creates the art movements of a fictional world — their manifestos, their controversies, what they were reacting against.",       placeholder: "What art movements exist in this world?",             example: "e.g. An art movement that creates works specifically designed to be ugly — beauty is considered propagandistic and dishonest",       series: "artmovement"},
  { id: "PropagandaArtEngine",  name: "Propaganda Art Engine",  icon: "📢", color: "#ca8a04", tagline: "State Art Architect",      description: "Designs the visual propaganda of a fictional state — what images power chooses to project and what it suppresses.",            placeholder: "What propaganda art does this state produce?",        example: "e.g. A state whose propaganda never shows leaders — only the results of their leadership — so no one can picture the ones in power", series: "artmovement"},
  { id: "FuneraryArtEngine",    name: "Funerary Art Engine",    icon: "⚱️", color: "#374151", tagline: "Death Art Architect",      description: "Designs the funerary art and death aesthetics of a fictional culture — how death is represented, memorialized, and beautified.",  placeholder: "How does this culture make art about death?",          example: "e.g. A culture where funeral art can only be made by the dying — commissioned from people in their last weeks",                    series: "symbol"    },
  { id: "BodyMarkingEngine",    name: "Body Marking Engine",    icon: "🎭", color: "#15803d", tagline: "Body Art Architect",       description: "Designs tattoos, scarification, body paint, and other body marking practices — their meanings, rituals, and social functions.",  placeholder: "What body marking traditions exist in this culture?",  example: "e.g. A culture where all important life events are marked on the body — by the end of a long life a person is fully covered",       series: "body"       },
  { id: "MaskDesignEngine",     name: "Mask Design Engine",     icon: "🎪", color: "#78350f", tagline: "Mask Architect",           description: "Designs the masks of a fictional world — ceremonial masks, social masks, masks of power — and what happens when masks come off.", placeholder: "What masks exist in this culture and why?",           example: "e.g. A culture where everyone is required to wear a mask in public — and removing it in front of someone is the highest intimacy", series: "body"       },
  { id: "CostumeEngine",        name: "Costume Engine",         icon: "🧣", color: "#0f766e", tagline: "Garment Architect",        description: "Designs the specific garments of a fictional world — what people wear for work, ceremony, war, and mourning, and why.",         placeholder: "What costumes and garments define this world?",       example: "e.g. A world where your profession is woven into your clothing in a way only trained eyes can read — credentials in fabric",         series: "fashion"    },
  { id: "StreetArtEngine",      name: "Street Art Engine",      icon: "✏️", color: "#6b7280", tagline: "Urban Art Architect",      description: "Designs street art and graffiti culture in a fictional world — what people paint when they're not supposed to and what it means.", placeholder: "What is street art like in this fictional world?",    example: "e.g. A city where government-approved street art has become so dominant that illegal street art is now just blank white rectangles", series: "artmovement"},
  { id: "ForbiddenImageEngine", name: "Forbidden Image Engine", icon: "🚫", color: "#4b5563", tagline: "Banned Image Architect",   description: "Designs images that are illegal, taboo, or dangerous in a fictional world — what cannot be depicted and what happens to those who depict it.", placeholder: "What images are forbidden in this world?",   example: "e.g. A world where depicting someone's face without permission is a criminal act — all portraits require signed consent",            series: "symbol"    },
];

export const VISUALWORLD_SERIES: VisualWorldSeriesDefinition[] = [
  { id: "fashion",     name: "FASHION-Series",      symbol: "FA", icon: "👗", gradient: "linear-gradient(135deg,#be185d,#7c3aed,#0f766e)", description: "Visual Identity — Color Palette, Fashion, and Costume — how a world dresses and what that reveals.",  engines: ["ColorPaletteEngine","FashionCycleEngine","CostumeEngine"],                  estimatedMinutes: 3 },
  { id: "heraldry",    name: "HERALDRY-Series",     symbol: "HE", icon: "🛡️", gradient: "linear-gradient(135deg,#d97706,#dc2626,#6366f1)", description: "Power Symbols — Heraldry, Flags, and Visual Motif — the visual language of institutions and states.",   engines: ["HeraldryEngine","FlagDesignEngine","VisualMotifEngine"],                    estimatedMinutes: 3 },
  { id: "artmovement", name: "ART-MOVEMENT-Series", symbol: "AM", icon: "🖼️", gradient: "linear-gradient(135deg,#0891b2,#ca8a04,#6b7280)", description: "Creative Culture — Art Movement, Propaganda Art, and Street Art — the full art history of a world.",  engines: ["ArtMovementEngine","PropagandaArtEngine","StreetArtEngine"],                estimatedMinutes: 3 },
  { id: "body",        name: "BODY-Series",         symbol: "BO", icon: "🎭", gradient: "linear-gradient(135deg,#15803d,#78350f,#374151)", description: "Embodied Culture — Body Marking, Mask Design, and Funerary Art — how a culture marks the body.",      engines: ["BodyMarkingEngine","MaskDesignEngine","FuneraryArtEngine"],                 estimatedMinutes: 3 },
  { id: "symbol",      name: "SYMBOL-Series",       symbol: "SY", icon: "🌀", gradient: "linear-gradient(135deg,#6366f1,#374151,#4b5563)", description: "Meaning Systems — Visual Motif, Forbidden Image, and Funerary Art — what images mean and who controls them.", engines: ["VisualMotifEngine","ForbiddenImageEngine","FuneraryArtEngine"],          estimatedMinutes: 3 },
];

export async function runVisualWorldEngine(opts: { engineId: string; engineName: string; topic: string; onChunk: (t: string) => void; onDone?: () => void; onError?: (e: string) => void; }): Promise<void> {
  const { engineId, engineName, topic, onChunk, onDone, onError } = opts;
  try {
    const resp = await fetch("/api/openai/engine-run", { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ engineId, engineName, topic }) });
    if (!resp.ok || !resp.body) { onError?.(`Engine returned ${resp.status}`); return; }
    const reader = resp.body.getReader(); const decoder = new TextDecoder();
    while (true) {
      const { done, value } = await reader.read(); if (done) break;
      for (const line of decoder.decode(value).split("\n")) {
        if (!line.startsWith("data:")) continue;
        try { const p = JSON.parse(line.slice(5).trim()) as { content?: string; done?: boolean }; if (p.content) onChunk(p.content); if (p.done) onDone?.(); } catch { /* skip */ }
      }
    }
  } catch (err) { onError?.(String(err)); }
}
