import { streamEngine } from "@/controller";
export interface WarloreEngineDefinition { id: string; name: string; icon: string; color: string; tagline: string; description: string; placeholder: string; example: string; series?: string; }
export interface WarloreSeriesDefinition { id: string; name: string; symbol: string; icon: string; gradient: string; description: string; engines: string[]; estimatedMinutes: number; }

export const WARLORE_ENGINES: WarloreEngineDefinition[] = [
  { id: "ArmyDesignEngine",      name: "Army Design Engine",       icon: "⚔️", color: "#dc2626", tagline: "Force Architect",          description: "Designs the structure of a fictional army — unit types, command hierarchy, conscription systems, and what soldiers are trained to believe.",   placeholder: "What army should I design?",                        example: "e.g. An army organized around family units — your regiment is your blood relatives, which creates fierce loyalty and catastrophic grief",   series: "army"     },
  { id: "TacticsEngine",         name: "Tactics Engine",           icon: "🗺️", color: "#7c3aed", tagline: "Battle Architect",         description: "Designs battlefield tactics and doctrines — formations, maneuvers, terrain use, and the tactical philosophy that guides how this army fights.", placeholder: "What tactical doctrine should this army follow?",    example: "e.g. A cavalry civilization that has never lost a battle fought in open plains but never learned to fight anywhere else",                  series: "army"     },
  { id: "SiegeEngine",           name: "Siege Engine",             icon: "🏰", color: "#d97706", tagline: "Siege Architect",          description: "Designs siege warfare — how cities are attacked and defended, the engineering involved, and the psychological brutality of the siege.",      placeholder: "How does siege warfare work in this world?",         example: "e.g. Sieges are won by cutting off information rather than food — a city that doesn't know the war's outcome cannot choose to surrender",   series: "siege"    },
  { id: "NavalWarfareEngine",    name: "Naval Warfare Engine",     icon: "⚓", color: "#0891b2", tagline: "Naval Architect",          description: "Designs naval warfare — ship designs, ocean battle tactics, piracy, blockades, and what controls of the sea means for a civilization.",     placeholder: "How does naval warfare work in this world?",         example: "e.g. A civilization where all major battles are naval and land armies are considered a sign of weakness and failure",                      series: "naval"    },
  { id: "SpyNetworkEngine",      name: "Spy Network Engine",       icon: "🕵️", color: "#374151", tagline: "Shadow War Architect",     description: "Designs intelligence organizations — their methods, their covers, their relationship to civilian life, and what they consider ethical.",      placeholder: "What spy network should I design?",                  example: "e.g. A spy network where every agent believes they are the only real agent — all others are suspected plants",                            series: "shadowwar"},
  { id: "WeaponForgeEngine",     name: "Weapon Forge Engine",      icon: "🔨", color: "#78350f", tagline: "Weapon Architect",         description: "Designs fictional weapons — their construction, their cultural meaning, the rituals around carrying them, and what losing yours means.",   placeholder: "What weapons should exist in this world?",           example: "e.g. A culture where your weapon is legally considered part of your body — disarming someone in public is assault",                        series: "army"     },
  { id: "PropagandaEngine",      name: "Propaganda Engine",        icon: "📢", color: "#be185d", tagline: "Propaganda Architect",     description: "Designs how a military state shapes civilian belief — the myths it creates about war, heroes, enemies, and sacrifice.",                   placeholder: "What propaganda does this military state produce?",  example: "e.g. A state that has re-named all its wars 'Corrections' — there has not been a war in 200 years, only 23 Corrections",                 series: "shadowwar"},
  { id: "PeaceTreatyEngine",     name: "Peace Treaty Engine",      icon: "🕊️", color: "#15803d", tagline: "Peace Architecture",       description: "Designs the architecture of peace — what terms are negotiated, what is left unsaid, and why the peace will eventually fail.",             placeholder: "What peace treaty should I design?",                example: "e.g. A peace treaty with 47 articles — 46 were agreed, one was left blank to be filled in later and never has been",                       series: "aftermath"},
  { id: "MercenaryEngine",       name: "Mercenary Engine",         icon: "💰", color: "#ca8a04", tagline: "Hired Force Architect",    description: "Designs mercenary companies — their culture, their code, their specialties, and the complicated ethics of professional violence.",          placeholder: "What mercenary company should I design?",            example: "e.g. A mercenary company that refuses to fight civilians but will take any military contract — and is in high demand for it",               series: "army"     },
  { id: "WarEconomyEngine",      name: "War Economy Engine",       icon: "📊", color: "#1d4ed8", tagline: "War Economy Architect",    description: "Designs the economics of warfare — who profits, who pays, how wars are financed, and what economies look like after prolonged conflict.",    placeholder: "What is the war economy of this world?",             example: "e.g. A civilization where war is the primary economic driver — peace would cause a financial collapse no one has a plan for",               series: "aftermath"},
  { id: "MilitaryTraditionEngine",name: "Military Tradition Engine",icon: "🎖️", color: "#4b5563", tagline: "War Culture Architect",   description: "Designs the cultural traditions of military life — rituals, songs, superstitions, coming-of-age ceremonies, and the mythology of service.",  placeholder: "What military traditions exist in this culture?",    example: "e.g. A tradition where soldiers burn their civilian name when they enlist and take a new name, returned only if they are dishonored",       series: "siege"    },
  { id: "WarCrimeEngine",        name: "War Crime Engine",         icon: "⚖️", color: "#6b7280", tagline: "Atrocity Architect",       description: "Designs how a civilization defines, documents, and adjudicates war crimes — and who has the power to decide what counts.",               placeholder: "How are war crimes defined and handled in this world?",example: "e.g. A civilization that has no concept of war crimes — all acts in war are considered legal — and what that world actually looks like", series: "aftermath"},
  { id: "AftermathEngine",       name: "Aftermath Engine",         icon: "🌑", color: "#0f766e", tagline: "Post-War Architect",       description: "Designs the aftermath of war — occupied territories, refugee populations, collective trauma, and the long shadow of conflict on a culture.",   placeholder: "What does the aftermath of war look like in this world?",example: "e.g. A post-war generation that has no framework for peace — they understand war's logic perfectly and peace confuses them",           series: "aftermath"},
];

export const WARLORE_SERIES: WarloreSeriesDefinition[] = [
  { id: "army",      name: "ARMY-Series",       symbol: "AR", icon: "⚔️", gradient: "linear-gradient(135deg,#dc2626,#7c3aed,#78350f)", description: "Force Design — Army, Tactics, Weapons, and Mercenaries — the complete structure of how this civilization makes war.", engines: ["ArmyDesignEngine","TacticsEngine","WeaponForgeEngine","MercenaryEngine"],   estimatedMinutes: 4 },
  { id: "siege",     name: "SIEGE-Series",      symbol: "SI", icon: "🏰", gradient: "linear-gradient(135deg,#d97706,#4b5563,#6366f1)", description: "Siege Warfare — Siege, Military Tradition, and Naval — the architecture of taking and holding places.",            engines: ["SiegeEngine","MilitaryTraditionEngine","NavalWarfareEngine"],              estimatedMinutes: 3 },
  { id: "naval",     name: "NAVAL-Series",      symbol: "NV", icon: "⚓", gradient: "linear-gradient(135deg,#0891b2,#1d4ed8,#0f766e)", description: "Sea Power — Naval Warfare, War Economy, and Mercenaries — control of the sea and those who sell it.",               engines: ["NavalWarfareEngine","WarEconomyEngine","MercenaryEngine"],                  estimatedMinutes: 3 },
  { id: "shadowwar", name: "SHADOW-WAR-Series", symbol: "SW", icon: "🕵️", gradient: "linear-gradient(135deg,#374151,#be185d,#6b7280)", description: "Hidden War — Spy Network and Propaganda — the war that happens before the first shot is fired.",                   engines: ["SpyNetworkEngine","PropagandaEngine"],                                      estimatedMinutes: 2 },
  { id: "aftermath", name: "AFTERMATH-Series",  symbol: "AF", icon: "🕊️", gradient: "linear-gradient(135deg,#15803d,#ca8a04,#0f766e)", description: "After War — Peace Treaty, War Economy, War Crimes, and Aftermath — what victory and defeat actually cost.",        engines: ["PeaceTreatyEngine","WarEconomyEngine","WarCrimeEngine","AftermathEngine"], estimatedMinutes: 4 },
];

export async function runWarloreEngine(opts: { engineId: string; engineName: string; topic: string; onChunk: (t: string) => void; onDone?: () => void; onError?: (e: string) => void; }): Promise<void> {
  const { engineId, topic, onChunk, onDone, onError } = opts;
  await streamEngine({ engineId, topic, onChunk, onDone: onDone ? () => onDone() : undefined, onError });
}
